


cheatAreas = {

	--BG1 Areas
	
	{"AR0002", "(BG)  Temple de Heaum (N)"},
	{"AR0004", "(BG)  Maison de Bheren, L1 (N)"},
	{"AR0005", "(BG)  Maison de Bheren, L2 (Ange, le chat) (N)"},
	{"AR0006", "(BG)  Maison de Rinnie, L1 (N)"},
	{"AR0007", "(BG)  Maison de Rinnie, L2 (N)"},
	{"AR0008", "(BG)  Maison 1, L1 (N)"},
	{"AR0009", "(BG)  Maison 1, L2 (N)"},
	{"AR0010", "(BG)  Maison de Jardak, L1 (N)"},
	{"AR0011", "(BG)  Maison de Jardak, L2 (N)"},
	{"AR0012", "(BG)  Maison 2, L1 (N)"},
	{"AR0013", "(BG)  Maison 2, L2 (N)"},
	{"AR0014", "(BG)  Maison 3, L1 (N)"},
	{"AR0015", "(BG)  Maison 3, L2 (N)"},
	{"AR0016", "(BG)  Maison 4, L1 (N)"},
	{"AR0017", "(BG)  Maison 4, L2 (N)"},
	{"AR0018", "(BG)  Maison 5, L1 (N)"},
	{"AR0019", "(BG)  Maison 5, L2 (N)"},
	{"AR0020", "(BG)  Maison 6, L1 (N)"},
	{"AR0021", "(BG)  Maison 6, L2 (N)"},
	{"AR0100", "  La Porte de Baldur, NORD-OUEST"},
	{"AR0101", "(BG)  Domaine Écudargent, L1 (NO)"},
	{"AR0102", "(BG)  Domaine Écudargent, L2 Skie (NO)"},
	{"AR0103", "(BG)  Taverne de l'Esturgeon Sautillant, L1 (NE)"},
	{"AR0104", "(BG)  Taverne de l'Esturgeon Sautillant, L2 (NE)"},
	{"AR0105", "(BG)  Auberge de la Lame et des Étoiles, L1 (SE)"},
	{"AR0106", "(BG)  Auberge de la Lame et des Étoiles, L2 (SE)"},
	{"AR0107", "(BG)  Auberge de la Lame et des Étoiles, L3 (SE)"},
	{"AR0108", "(BG)  Palais Ducal, L1 (N)"},
	{"AR0109", "(BG)  Palais Ducal, L2 (N)"},
	{"AR0110", "(BG)  Palais Ducal, L3 (N)"},
	{"AR0111", "(BG)  Palais Ducal, Sous-sol du palais (N)"},
	{"AR0112", "(BG)  Caves Souterraines, (NE)"},
	{"AR0114", "(BG)  Taverne de la Sirène Rougissante, L1 (NE)"},
	{"AR0115", "(BG)  Taverne de la Sirène Rougissante, L2 (NE)"},
	{"AR0116", "(BG)  Auberge du Heaume et de la Cape, L1 (NO)"},
	{"AR0117", "(BG)  Auberge du Heaume et de la Cape, L2 (NO)"},
	{"AR0118", "(BG)  Auberge du Heaume et de la Cape, L3 (NO)"},
	{"AR0119", "(BG)  Auberge des Trois Vieilles Chopes, L1 (N)"},
	{"AR0120", "(BG)  Auberge des Trois Vieilles Chopes, L2 (N)"},
	{"AR0121", "(BG)  Auberge des Trois Vieilles Chopes, L3 (N)"},
	{"AR0123", "(BG)  Ville souterraine, Ruines (E)"},
	{"AR0125", "(BG)  Temple de Bhaal, (E)"},
	{"AR0126", "(BG)  Maison de Ragevite, (O)"},
	{"AR0127", "(BG)  Ligue des Marchands, L1 (SO)"},
	{"AR0128", "(BG)  Ligue des Marchands, L2 (SO)"},
	{"AR0129", "(BG)  Ligue des Marchands, L3 (SO)"},
	{"AR0130", "(BG)  Maison des Merveilles, Alora (O)"},
	{"AR0131", "(BG)  Temple de Gond, (O)"},
	{"AR0132", "(BG)  Manoir de la Dame, (O)"},
	{"AR0133", "(BG)  Auberge de la Lanterne assourdie, D1 (S)"},
	{"AR0134", "(BG)  Auberge de la Lanterne assourdie, D2 (S)"},
	{"AR0135", "(BG)  Auberge de la Lanterne assourdie, D3 (S)"},
	{"AR0136", "(BG)  Auberge de la Lanterne assourdie, D4 (S)"},
	{"AR0137", "(BG)  Tour de Ramazith, L1 (N)"},
	{"AR0138", "(BG)  Tour de Ramazith, L6 (N)"},
	{"AR0139", "(BG)  Tour de Ramazith, L2 (N)"},
	{"AR0140", "(BG)  Tour de Ramazith, L3 (N)"},
	{"AR0141", "(BG)  Tour de Ramazith, L4 (N)"},
	{"AR0142", "(BG)  Tour de Ramazith, L5 (N)"},
	{"AR0143", "(BG)  Domaine Oberon, L1 (C)"},
	{"AR0144", "(BG)  Domaine Oberon, L2 (C)"},
	{"AR0145", "(BG)  Domaine Oberon, L3 (C)"},
	{"AR0146", "(BG)  Labyrinthe de la Guilde des voleurs, (E)"},
	{"AR0148", "(BG)  Vers la guilde des Voleurs, Entree 5 (E)"},
	{"AR0149", "(BG)  Chapelle d'Ilmater (NE)"},
	{"AR0150", "(BG)  Vers la guilde des Voleurs, Entree 2 (E)"},
	{"AR0151", "(BG)  Vers la guilde des Voleurs, Entree 3 (E)"},
	{"AR0152", "(BG)  Vers la guilde des Voleurs, Entree 4 (E)"},
	{"AR0153", "(BG)  Guilde des voleurs de l'Ombre, (E)"},
	{"AR0154", "(BG)  Taverne de Keexie, L1 (E)"},
	{"AR0155", "(BG)  Maison 3, L1 (NO)"},
	{"AR0156", "(BG)  Maison 3, L2 (NO)"},
	{"AR0157", "(BG)  Maison de Quinn, L1 (NO)"},
	{"AR0158", "(BG)  Maison de Quinn,  L2 (NO)"},
	{"AR0159", "(BG)  Maison 1, L1 (NO)"},
	{"AR0160", "(BG)  Maison 1, L2 (NO)"},
	{"AR0161", "(BG)  Manoir de Degrodel (NO)"},
	{"AR0162", "(BG)  Manoir des jumelles,( Louise et Laerta) L1 (NO)"},
	{"AR0163", "(BG)  Maison 2, L1 (NO)"},
	{"AR0164", "(BG)  Maison 2, L2 (NO)"},
	{"AR0165", "(BG)  Auberge, L1 (NO)"},
	{"AR0166", "(BG)  Auberge, L2 (NO)"},
	{"AR0167", "(BG)  Maison de Pheirkas, L1 (NO)"},
	{"AR0168", "(BG)  Maison de Pheirkas, L2 (NO)"},
	{"AR0169", "(BG)  Maison 4, L1 (NO)"},
	{"AR0170", "(BG)  Maison 4, L2 (NO)"},
	{"AR0171", "(BG)  Taverne de Keexie, L2 (E)"},
	{"AR0200", "  La Porte de Baldur, NORD"},
	{"AR0224", "(BG)  Égouts, Ouest (O)"},
	{"AR0225", "(BG)  Égouts, Central (C)"},
	{"AR0226", "(BG)  Égouts, Est (E)"},
	{"AR0300", "  La Porte de Baldur, NORD-EST"},
	{"AR0302", "(BG)  Maison 2, L1 (NE)"},
	{"AR0303", "(BG)  Maison 2, L2 (NE)"},
	{"AR0304", "(BG)  Bazar (NE)"},
	{"AR0305", "(BG)  Maison 1, L1 (NE)"},
	{"AR0306", "(BG)  Maison 1, L2 (NE)"},
	{"AR0307", "(BG)  Ligue des marchands, L1 (NE)"},
	{"AR0308", "(BG)  Ligue des marchands, L2 (NE)"},
	{"AR0400", "(SC)  En amont de la Chionthar"},
	{"AR0401", "(SC)  Fermes sur la Chionthar, (Ajantis)"},
	{"AR0500", "(ToSC)  Tour de Durlag"},
	{"AR0501", "(ToSC)  Tour de Durlag, Sous-sol"},
	{"AR0502", "(ToSC)  Tour de Durlag, L1"},
	{"AR0503", "(ToSC)  Tour de Durlag, L2"},
	{"AR0504", "(ToSC)  Tour de Durlag, L3"},
	{"AR0505", "(ToSC)  Tour de Durlag, L4"},
	{"AR0506", "(ToSC)  Tour de Durlag, Échiquier"},
	{"AR0507", "(ToSC)  Tour de Durlag, Défi glace"},
	{"AR0508", "(ToSC)  Tour de Durlag, Défi feu"},
	{"AR0509", "(ToSC)  Tour de Durlag, Défi air"},
	{"AR0510", "(ToSC)  Tour de Durlag, Défi terre"},
	{"AR0511", "(ToSC)  Tour de Durlag, D1"},
	{"AR0512", "(ToSC)  Tour de Durlag, D2"},
	{"AR0513", "(ToSC)  Tour de Durlag, D3"},
	{"AR0514", "(ToSC)  Tour de Durlag, D4"},
	{"AR0515", "(ToSC)  Tour de Durlag, Golem de pierre"},
	{"AR0516", "(ToSC)  Tour de Durlag, Chevalier demon"},
	{"AR0600", "  La Porte de Baldur, OUEST"},
	{"AR0601", "(BG)  Les Sept Soleils, L1 (SO)"},
	{"AR0602", "(BG)  Les Sept Soleils, L2 (SO)"},
	{"AR0603", "(BG)  Les Sept Soleils, Sous-sol (SO)"},
	{"AR0606", "(BG)  Siege du Poing Enflamme, Sous-sol (SO)"},
	{"AR0607", "(BG)  Siege du Poing Enflamme, L1 (SO)"},
	{"AR0608", "(BG)  Siege du Poing Enflamme, L2 (SO)"},
	{"AR0609", "(BG)  Temple d'Umberlee, (Quais) (S)"},
	{"AR0611", "(BG)  Trône de Fer, Sous-sol (S)"},
	{"AR0612", "(BG)  Trône de Fer, L2 (S)"},
	{"AR0613", "(BG)  Trône de Fer, L3 (S)"},
	{"AR0614", "(BG)  Trône de Fer, L4 (S)"},
	{"AR0615", "(BG)  Trône de Fer, L5 (S)"},
	{"AR0616", "(BG)  Trône de Fer, L1 (S)"},
	{"AR0617", "(BG)  Maison de Tremain Belde'ar, L1 (O)"},
	{"AR0618", "(BG)  Maison de Tremain Belde'ar, L2 (O)"},
	{"AR0619", "(BG)  Maison de Fenten, L1 (O)"},
	{"AR0620", "(BG)  Maison de Fenten, L2 (O)"},
	{"AR0621", "(BG)  Trône de Fer, Toit (S)"},
	{"AR0700", "  La Porte de Baldur, CENTRE DE LA VILLE"},
	{"AR0702", "(BG)  Bâtisse du Maître du Port, (Quais) (S)"},
	{"AR0703", "(BG)  Bazar Magique, L1 (E)"},
	{"AR0704", "(BG)  Bazar Magique, L2 (E)"},
	{"AR0705", "(BG)  Taverne du Chant de l'elfe, L1 (E)"},
	{"AR0706", "(BG)  Taverne du Chant de l'elfe, L2 (E)"},
	{"AR0707", "(BG)  Maison 3, L1 (C)"},
	{"AR0708", "(BG)  Maison 3, L2 (C)"},
	{"AR0709", "(BG)  Maison 2, L1 (C)"},
	{"AR0710", "(BG)  Maison 2, L2 (C)"},
	{"AR0711", "(BG)  Maison 1, L1 (C)"},
	{"AR0712", "(BG)  Maison 1, L2 (C)"},
	{"AR0713", "(BG)  Maison 5, L1 (C)"},
	{"AR0714", "(BG)  Maison 5, L2 (C)"},
	{"AR0715", "(BG)  Maison de Nadine, L1 (C)"},
	{"AR0716", "(BG)  Maison de Nadine, L2 (C)"},
	{"AR0717", "(BG)  Maison 6, L1 (C)"},
	{"AR0718", "(BG)  Maison 6, L2 (C)"},
	{"AR0719", "(BG)  Manoir de Felonius Gist, (C)"},
	{"AR0720", "(BG)  Taverne de Drakon, (C)"},
	{"AR0721", "(BG)  Magasin de volailles, (Poulets enragés) (C)"},
	{"AR0722", "(BG)  Maison 4, L1 (C)"},
	{"AR0723", "(BG)  Maison 4, L2 (C)"},
	{"AR0724", "(BG)  Tente de jeux 1, (C)"},
	{"AR0725", "(BG)  Tente de jeux 2, (C)"},
	{"AR0726", "(BG)  Tente du devin, (C)"},
	{"AR0800", "  La Porte de Baldur, EST"},
	{"AR0801", "(BG)  Maison 6, L1 (E)"},
	{"AR0802", "(BG)  Maison 6, L2 (E)"},
	{"AR0803", "(BG)  Magasin d'armes de Maltz, L1 (E)"},
	{"AR0804", "(BG)  Magasin d'armes de Maltz, L2 (E)"},
	{"AR0805", "(BG)  Maison d'Arkion, L1 (E)"},
	{"AR0806", "(BG)  Maison d'Arkion, L2 (E)"},
	{"AR0807", "(BG)  Auberge, L1 (E)"},
	{"AR0808", "(BG)  Auberge, L2 (E)"},
	{"AR0809", "(BG)  Magasin du Silence, (E)"},
	{"AR0810", "(BG)  Magasin d'Aello la Chance, (E)"},
	{"AR0811", "(BG)  Maison 1, L1 (E)"},
	{"AR0812", "(BG)  Maison 1, L2 (E)"},
	{"AR0813", "(BG)  Maison de Nemphre, L1 (SE)"},
	{"AR0814", "(BG)  Maison de Nemphre, L2 (SE)"},
	{"AR0900", "(SC)  Travers du Ver, (Quayle)"},
	{"AR0901", "(SC)  Maison de Tenya, (Travers du Ver)"},
	{"AR1000", "  BARBE D'ULGOTH"},
	{"AR1001", "(ToSC)  Auberge de la Barbe d'Ulgoth"},
	{"AR1002", "(ToSC)  Aec'Letec le demon, D1 (Barbe d'Ulgoth)"},
	{"AR1003", "(ToSC)  Culte d'Aec'Letec, L1 (Barbe d'Ulgoth)"},
	{"AR1004", "(ToSC)  Maison de Mendas, (Barbe d'Ulgoth)"},
	{"AR1005", "(ToSC)  Maison de Therella, (Barbe d'Ulgoth)"},
	{"AR1006", "(ToSC)  Maison 2, (Barbe d'Ulgoth"},
	{"AR1007", "(ToSC)  Maison 1, (Barbe d'Ulgoth"},
	{"AR1008", "(ToSC)  Île des glaces"},
	{"AR1009", "(ToSC)  Île des glaces, Labyrinthe L1"},
	{"AR1010", "(ToSC)  Île des glaces, Labyrinthe L2"},
	{"AR1100", "  La Porte de Baldur, SUD-OUEST, (Tiax)"},
	{"AR1101", "(BG)  Maison de Wiven, L1 (SO)"},
	{"AR1102", "(BG)  Maison de Wiven, L2 (SO)"},
	{"AR1103", "(BG)  Maison 3, L1 (SO)"},
	{"AR1104", "(BG)  Maison 3, L2 (SO)"},
	{"AR1105", "(BG)  Maison 1, L1 (SO)"},
	{"AR1106", "(BG)  Maison 1, L2 (SO)"},
	{"AR1107", "(BG)  Maison 2, L1 (SO)"},
	{"AR1108", "(BG)  Maison 2, L2 (SO)"},
	{"AR1109", "(BG)  Taverne, L1 (SO)"},
	{"AR1110", "(BG)  Taverne, L2 (SO)"},
	{"AR1111", "(BG)  Maison de Sunin, (SO)"},
	{"AR1112", "(BG)  Magasin d'armes 1, (SO)"},
	{"AR1113", "(BG)  La vieille auberge, L1 (SO)"},
	{"AR1114", "(BG)  La vieille auberge, L2 (SO)"},
	{"AR1115", "(BG)  Magasin de potions 2, (SO)"},
	{"AR1116", "(BG)  Magasin d'armes 2, (SO)"},
	{"AR1117", "(BG)  Magasin de potions 1, (SO)"},
	{"AR1200", "  Les quais de la Porte de Baldur, SUD"},
	{"AR1201", "(BG)  Manoir des ogres-mages, L1 (S)"},
	{"AR1202", "(BG)  Manoir des ogres-mages, L2 (S)"},
	{"AR1203", "(BG)  Maison 2, L1 (S)"},
	{"AR1204", "(BG)  Maison 2, L2 (S)"},
	{"AR1205", "(BG)  Maison 1, L1 (S)"},
	{"AR1206", "(BG)  Maison 1, L2 (S)"},
	{"AR1207", "(BG)  Entrepôt, (Basilic) (S)"},
	{"AR1208", "(BG)  Entrepôt de Noralee, (Quais) (S)"},
	{"AR1209", "(BG)  Maison de Larriaz, L1 (S)"},
	{"AR1210", "(BG)  Maison de Larriaz, L2 (S)"},
	{"AR1211", "(BG)  Maison de Ghorak, L1 (S)"},
	{"AR1212", "(BG)  Maison de Ghorak, L2 (S)"},
	{"AR1213", "(BG)  Maison de Cordyr, L1 (S)"},
	{"AR1214", "(BG)  Maison de Cordyr, L2 (S)"},
	{"AR1215", "(BG)  Taverne de Jopalin, (Quais) (S)"},
	{"AR1300", "  La Porte de Baldur, SUD-EST"},
	{"AR1301", "(BG)  Entrepôt, (SE)"},
	{"AR1302", "(BG)  Magasin d'Al le Bien-Équilibre, (SE)"},
	{"AR1303", "(BG)  Entrepôt de Nadarin, (SE)"},
	{"AR1304", "(BG)  Maison 3, L1 (SE)"},
	{"AR1305", "(BG)  Maison 3, L2 (SE)"},
	{"AR1306", "(BG)  Auberge, L1 (SE)"},
	{"AR1307", "(BG)  Auberge, L2 (SE)"},
	{"AR1308", "(BG)  Maison 4, L1 (SE)"},
	{"AR1309", "(BG)  Maison 4, L2 (SE)"},
	{"AR1310", "(BG)  Maison 2, L1 (SE)"},
	{"AR1311", "(BG)  Maison 2, L2 (SE)"},
	{"AR1312", "(BG)  Maison de Gantolandan, L1 (SE)"},
	{"AR1313", "(BG)  Maison de Gantolandan, L2 (SE)"},
	{"AR1314", "(BG)  Maison 1, L1 (SE)"},
	{"AR1315", "(BG)  Maison 1, L2 (SE)"},
	{"AR1316", "(BG)  Cambriolage, L1 (Taxek et Michael) (SE)"},
	{"AR1317", "(BG)  Cambriolage, L2 (Taxek et Michael) (SE)"},
	{"AR1320", "(BG)  Magasin 1, Bazar (SE)"},
	{"AR1400", "(SC)  En aval du Chionthar"},
	{"AR1401", "(SC)  Fosse des Ankhegs, (Chionthar)"},
	{"AR1402", "(SC)  Maison 1, (Chionthar)"},
	{"AR1403", "(SC)  Maison 2, (Chionthar)"},
	{"AR1404", "(SC)  Maison du fermier Brun, (Chionthar)"},
	{"AR1500", "(ToSC)  Île perdue de Baldurien, Nord"},
	{"AR1501", "(ToSC)  Épave de Baldurien, D1 (N)"},
	{"AR1502", "(ToSC)  Épave de Baldurien, D2 (N)"},
	{"AR1503", "(ToSC)  Épave de Baldurien, D3 (N)"},
	{"AR1504", "(ToSC)  Épave de Baldurien, D4 (N)"},
	{"AR1505", "(ToSC)  Maison de Dradeel, (Île perdue) (N)"},
	{"AR1600", "(B-M)  Le Vieux chêne de Bois-Manteau, Faldorn (3)"},
	{"AR1601", "(B-M)  Maison du Vieux chêne, L1 (3)"},
	{"AR1602", "(B-M)  Maison du Vieux chêne, L2 (3)"},
	{"AR1603", "(B-M)  Peter et les Wyvernes, Vieux chêne"},
	{"AR1700", "(B-M)  La Caverne de Bois-Manteau, (4)"},
	{"AR1800", "(B-M)  Les Mines de Bois-Manteau, (5)"},
	{"AR1801", "(B-M)  Mines de Bois-Manteau, D1"},
	{"AR1802", "(B-M)  Mines de Bois-Manteau, D3"},
	{"AR1803", "(B-M)  Mines de Bois-Manteau, D4"},
	{"AR1804", "(B-M)  Mines de Bois-Manteau, D2 (Yeslick)"},
	{"AR1805", "(B-M)  Mines de Bois-Manteau, Caserne L1"},
	{"AR1806", "(B-M)  Mines de Bois-Manteau, Caserne L2"},
	{"AR1807", "(B-M)  Mines de Bois-Manteau, Monte-charge"},
	{"AR1808", "(B-M)  Mines de Bois-Manteau, Entrepôt"},
	{"AR1809", "(B-M)  Mines de Bois-Manteau, Entree"},
	{"AR1900", "(C-B)  Le Camp des bandits"},
	{"AR1901", "(C-B)  Tente des chefs des bandits"},
	{"AR1902", "(C-B)  Tente 2, Ardenor Crush"},
	{"AR1903", "(C-B)  Grotte des Gnolls, Garclax"},
	{"AR1904", "(C-B)  Tente de Tersus"},
	{"AR1905", "(C-B)  Tente 1, Knott"},
	{"AR1906", "(C-B)  Tente 3"},
	{"AR1907", "(C-B)  Tente 4, Taugosz Khosann"},
	{"AR2000", "(ToSC)  Île perdue de Baldurien, Sud"},
	{"AR2001", "(ToSC)  Grande hutte, Île perdue (S)"},
	{"AR2002", "(ToSC)  Hutte de la meneuse, (Kaishas) (S)"},
	{"AR2003", "(ToSC)  Hutte 3, (Île perdue) (S)"},
	{"AR2004", "(ToSC)  Hutte 2, (Île perdue) (S)"},
	{"AR2005", "(ToSC)  Hutte 4, (Île perdue) (S)"},
	{"AR2006", "(ToSC)  Hutte 1, (Île perdue) (S)"},
	{"AR2007", "(ToSC)  Hutte du pêcheur, (Île perdue) (S)"},
	{"AR2008", "(ToSC)  Hutte de commerce 2, (Île perdue) (S)"},
	{"AR2009", "(ToSC)  Hutte de commerce 1, (Île perdue) (S)"},
	{"AR2010", "(ToSC)  Hutte de commerce 4, (Île perdue) (S)"},
	{"AR2011", "(ToSC)  Hutte de commerce 3, (Île perdue) (S)"},
	{"AR2012", "(ToSC)  Caverne des loups-garous, (S)"},
	{"AR2100", "(B-M)  Les Falaises de Bois-Manteau, (2)"},
	{"AR2101", "(B-M)  Nid d'araignée, Centeol (2)"},
	{"AR2200", "(B-M)  Le Pavillon de chasse de Bois-Manteau, Coran (1)"},
	{"AR2215", "(B-M)  Pavillon de chasse, L1 (1)"},
	{"AR2300", "(A-B)  Auberge de BRASAMICAL"},
	{"AR2301", "(A-B)  Auberge de Brasamical, L1 (Jaheira, Khalid)"},
	{"AR2302", "(A-B)  Auberge de Brasamical, L2"},
	{"AR2303", "(A-B)  Auberge de Brasamical, L3"},
	{"AR2304", "(A-B)  Temple de la sagesse"},
	{"AR2305", "(A-B)  Maison"},
	{"AR2306", "(A-B)  Maison de Joia"},
	{"AR2400", "(SC)  Valpeld, (Viconia)"},
	{"AR2600", "(C-S)  Château-Suif, Prologue"},
	{"AR2602", "(C-S)  Quartiers du pretre"},
	{"AR2605", "(C-S)  Infirmerie"},
	{"AR2606", "(C-S)  Entrepôt"},
	{"AR2607", "(C-S)  Baraquement"},
	{"AR2608", "(C-S)  Château-Suif, Bibliothèque L1"},
	{"AR2609", "(C-S)  Château-Suif, Bibliothèque L2"},
	{"AR2610", "(C-S)  Château-Suif, Bibliothèque L3"},
	{"AR2611", "(C-S)  Château-Suif, Bibliothèque L4"},
	{"AR2612", "(C-S)  Château-Suif, Bibliothèque L5"},
	{"AR2613", "(C-S)  Château-Suif, Entree des Catacombes"},
	{"AR2614", "(C-S)  Château-Suif, Bibliothèque L6"},
	{"AR2615", "(C-S)  Château-Suif, Catacombes L1"},
	{"AR2616", "(C-S)  Auberge de Château-Suif, L1"},
	{"AR2617", "(C-S)  Auberge de Château-Suif, L2"},
	{"AR2618", "(C-S)  Caserne"},
	{"AR2619", "(C-S)  Château-Suif, Catacombes L2"},
	{"AR2626", "(C-S)  Chapitre 6, Château-Suif"},
	{"AR2627", "(C-S)  Chapitre 6, Quartiers du prêtre"},
	{"AR2628", "(C-S)  Chapitre 6, Infirmerie"},
	{"AR2629", "(C-S)  Chapitre 6, Auberge L1"},
	{"AR2630", "(C-S)  Chapitre 6, Auberge L2"},
	{"AR2631", "(C-S)  Chapitre 6, Caserne"},
	{"AR2632", "(C-S)  Chapitre 6, Baraquement"},
	{"AR2633", "(C-S)  Chapitre 6, Infirmerie"},
	{"AR2643", "(C-S)  Entraînement au combat de groupe d’Obe"},
	{"AR2700", "(SC)  Voie du Lion, (Imoen, Xzar, Montaron)"},
	{"AR2800", "(SC)  Croisée des chemins"},
	{"AR2900", "(SC)  Bois de Lars"},
	{"AR3000", "(SC)  Bois des araignées"},
	{"AR3100", "(SC)  Cote des épaves"},
	{"AR3200", "(SC)  Haute Haie, (Kivan)"},
	{"AR3201", "(SC)  Maison"},
	{"AR3202", "(SC)  Demeure de Thalantyr"},
	{"AR3300", "  BÉRÉGOST, (Neera, Garrick, Kagain)"},
	{"AR3301", "(B)  Forge de Grondemarteau"},
	{"AR3302", "(B)  Maison 19"},
	{"AR3303", "(B)  Auberge de la Gerbe Rouge, L2"},
	{"AR3304", "(B)  Jongleur Jovial, L1"},
	{"AR3305", "(B)  Jongleur Jovial, L2 principale"},
	{"AR3306", "(B)  Jongleur Jovial, L2 secondaire"},
	{"AR3307", "(B)  Magicien Ardent, L1"},
	{"AR3308", "(B)  Magicien Ardent, L2"},
	{"AR3309", "(B)  Maison 13, L1"},
	{"AR3310", "(B)  Maison 13, L2"},
	{"AR3311", "(B)  Maison 12, L1"},
	{"AR3312", "(B)  Maison 12, L2"},
	{"AR3313", "(B)  Maison de Mirianne, L1"},
	{"AR3314", "(B)  Maison de Mirianne, L2"},
	{"AR3315", "(B)  Maison de Landrin"},
	{"AR3316", "(B)  Maison 18"},
	{"AR3317", "(B)  Maison de Borland"},
	{"AR3318", "(B)  Maison 15"},
	{"AR3319", "(B)  Maison 16"},
	{"AR3320", "(B)  Manoir Travenhurst, L1"},
	{"AR3321", "(B)  Manoir Travenhurst, L2"},
	{"AR3322", "(B)  Quartier des serviteurs du Manoir"},
	{"AR3323", "(B)  Maison 20, L1"},
	{"AR3324", "(B)  Maison 20, L2"},
	{"AR3325", "(B)  Maison 23, L1"},
	{"AR3326", "(B)  Maison 23, L2"},
	{"AR3327", "(B)  Maison 14, L1"},
	{"AR3328", "(B)  Maison 14, L2"},
	{"AR3329", "(B)  Maison d'Alain, L1"},
	{"AR3330", "(B)  Maison d'Alain, L2"},
	{"AR3331", "(B)  Maison de Mr. Colquetle, L1"},
	{"AR3332", "(B)  Maison de Mr. Colquetle, L2"},
	{"AR3333", "(B)  Maison de Perleflamme Cheveux d’elfe, L1"},
	{"AR3334", "(B)  Maison de Perleflamme Cheveux d’elfe, L2"},
	{"AR3335", "(B)  Maison 10, L1"},
	{"AR3336", "(B)  Maison 10, L2"},
	{"AR3337", "(B)  Maison 22, L1"},
	{"AR3338", "(B)  Maison 22, L2"},
	{"AR3339", "(B)  Maison 01, L1"},
	{"AR3340", "(B)  Maison 01, L2"},
	{"AR3341", "(B)  Maison 02, L1"},
	{"AR3342", "(B)  Maison 02, L2"},
	{"AR3343", "(B)  Maison 03"},
	{"AR3344", "(B)  Maison 07"},
	{"AR3345", "(B)  Maison 04 L1"},
	{"AR3346", "(B)  Maison 04 L2"},
	{"AR3347", "(B)  Maison des Greycart, L1"},
	{"AR3348", "(B)  Maison des Greycart, L2"},
	{"AR3349", "(B)  Maison 06, L1"},
	{"AR3350", "(B)  Maison 06, L2"},
	{"AR3351", "(B)  Auberge de Feldpost, L1"},
	{"AR3352", "(B)  Auberge de Feldpost, L2"},
	{"AR3353", "(B)  Boutique de Kagain"},
	{"AR3354", "(B)  Maison, 09"},
	{"AR3355", "(B)  Maison, 08"},
	{"AR3356", "(B)  Maison, 08"},
	{"AR3357", "(B)  Auberge de la Gerbe Rouge, L1"},
	{"AR3400", "(B)  Temple de Lathandre"},
	{"AR3401", "(B)  Vestibule du Temple de Lathandre"},
	{"AR3402", "(B)  Temple de Lathandre, Intérieur"},
	{"AR3500", "(SC)  Jardins de Mutamin"},
	{"AR3600", "(SC)  Phare, (Safana)"},
	{"AR3601", "(SC)  Grotte de Black Alaric"},
	{"AR3700", "(SC)  Canyons rouges"},
	{"AR3800", "(SC)  Route de Nashkel"},
	{"AR3802", "(SC)  Grotte de la Route de Nashkel"},
	{"AR3900", "(SC)  École d’Ulcaster"},
	{"AR3901", "(SC)  Ruines de l'école d’Ulcaster"},
	{"AR4000", "  GULLYKIN"},
	{"AR4001", "(G)  Maison de Jenkal, L1"},
	{"AR4002", "(G)  Maison de Jenkal, Cellier"},
	{"AR4003", "(G)  Temple de Yondalla, L1"},
	{"AR4004", "(G)  Temple de Yondalla, Cellier"},
	{"AR4005", "(G)  Maison 1, L1"},
	{"AR4006", "(G)  Maison 1, Cellier"},
	{"AR4007", "(G)  Maison 3, L1"},
	{"AR4008", "(G)  Maison 3, Cellier"},
	{"AR4009", "(G)  Maison 4, L1"},
	{"AR4010", "(G)  Maison 4, Cellier"},
	{"AR4011", "(G)  Maison 5, L1"},
	{"AR4012", "(G)  Maison 5, Cellier"},
	{"AR4013", "(G)  Maison 2, L1"},
	{"AR4014", "(G)  Maison 2, Cellier"},
	{"AR4100", "(SC)  Site archéologique"},
	{"AR4101", "(SC)  Tombe"},
	{"AR4200", "(SC)  Lac dans la campagne"},
	{"AR4300", "(SC)  Passe de Nashkel"},
	{"AR4400", "(SC)  Plaines de Flammevin"},
	{"AR4401", "(SC)  Grotte des plaines de Flammevin"},
	{"AR4500", "(SC)  Pont de Flammevin"},
	{"AR4501", "(B-M)  Grotte des Wyvernes de Bois-Manteau, (4)"},
	{"AR4600", "(SC)  Rivière de l'Ours"},
	{"AR4700", "(SC)  Village Xvart"},
	{"AR4701", "(SC)  Grotte d'Ursa l'ours"},
	{"AR4800", "  NASHKEL, (Minsc, Edwin, Rasaad)"},
	{"AR4801", "(N)  Auberge de Nashkel"},
	{"AR4802", "(N)  Temple de Heaum"},
	{"AR4803", "(N)  Magasin de Nashkel"},
	{"AR4804", "(N)  Manoir de Nashkel, L1"},
	{"AR4805", "(N)  Manoir de Nashkel, L2"},
	{"AR4806", "(N)  Maison de Joseph"},
	{"AR4807", "(N)  Maison 1"},
	{"AR4808", "(N)  Maison 2"},
	{"AR4809", "(N)  Taverne du Dragon Qui Rote"},
	{"AR4810", "(N)  Caserne"},
	{"AR4900", "(N-f)  Festival de Nashkel, (Branwen)"},
	{"AR4901", "(N-f)  Marchand d’armures"},
	{"AR4902", "(N-f)  Lotus noir"},
	{"AR4903", "(N-f)  Tente de jeux, Vitiare"},
	{"AR4904", "(N-f)  Tente de jeux"},
	{"AR4905", "(N-f)  Marchand de potions rares"},
	{"AR4906", "(N-f)  Tente de Zordral"},
	{"AR4907", "(N-f)  Marchand d’objets magiques"},
	{"AR4908", "(N-f)  Marchand d’armes de mêlée"},
	{"AR4909", "(N-f)  Marchand d’armes de jet"},
	{"AR5000", "(SC)  Vallée des Tombes"},
	{"AR5001", "(SC)  Tombes de la Vallée des Tombes"},
	{"AR5100", "(SC)  Forteresse gnoll, (Dynahéir)"},
	{"AR5101", "(SC)  Grotte de la forteresse, (Xvarts)"},
	{"AR5102", "(SC)  Grotte de la forteresse, (Traité)"},
	{"AR5103", "(SC)  Grotte de la forteresse, (Vers charognards)"},
	{"AR5200", "(SC)  Chutes de la dryade"},
	{"AR5201", "(SC)  Ruines de Flammevin"},
	{"AR5202", "(SC)  Caverne des Chutes de la dryade"},
	{"AR5300", "(SC)  Forêt des feuilles écarlates"},
	{"AR5400", "(N-m)  Mines de Nashkel"},
	{"AR5401", "(N-m)  Mines, L1"},
	{"AR5402", "(N-m)  Mines, L2"},
	{"AR5403", "(N-m)  Mines, L3"},
	{"AR5404", "(N-m)  Mines, L4"},
	{"AR5405", "(N-m)  Mines, Repère de Mulahey (Xan)"},
	{"AR5406", "(N-m)  Réserve des Mines de Nashkel"},
	{"AR5500", "(SC)  Montagnes des Grouilleux"},
	{"AR5506", "(C-S)  Cavernes sous Château-Suif"},
	{"AR5600", "  Aléatoire, Plaine 1"},
	{"AR5601", "  Aléatoire, Plaine 2"},
	{"AR5700", "  Aléatoire, Canyon 1"},
	{"AR5701", "  Aléatoire, Canyon 2"},
	{"AR5800", "  Aléatoire, Falaise 1"},
	{"AR5801", "  Aléatoire, Falaise 2"},
	{"AR5900", "  Aléatoire, Prairie 1"},
	{"AR5901", "  Aléatoire, Prairie 2"},
	{"AR6000", "  Aléatoire, Forêt 1"},
	{"AR6001", "  Aléatoire, Forêt 2"},
	{"AR6100", "  Aléatoire, Route"},
	{"OH1000", "  Aléatoire, (Dorn recrutement)"},
	{"OH2000", "(SC)  Enclave d'Adoy, (Quête de Neera)"},
	{"OH2010", "(SC)  Enclave d'Adoy, intérieur"},
	{"OH3000", "(SC)  Pics Brumeux, (Quête de Rasaad)"},
	{"OH3010", "(SC)  Temple de la Lune Noire, Entrée"},
	{"OH3020", "(SC)  Temple de la Lune Noire, Geôles"},
	{"OH3100", "(SC)  Temple de la Lune Noire, Sommet"},
	
	--BP1 Areas
	
	{"OH9310", "(FN1)  Arène 1"},
	{"OH9350", "(FN1)  Arène 2"},
	{"OH9360", "(FN1)  Zone de repos"},
	
	--Tutorial Areas
	
	{"TU0015", "(Tuto)  Palais Ducal, 1er étage (Commencement)"},
	{"TU0016", "(Tuto)  Palais Ducal, 2eme étage"},
	{"TU0017", "(Tuto)  Palais Ducal, 3eme étage"},
	{"TU0018", "(Tuto)  Palais Ducal, Sous-sol"},

	--SOD Areas

	{"BD0010", "(SoD)  Palais Ducal"},
	{"BD0020", "(SoD)  Bazar Magique / Taverne du Chant de l'elfe"},
	{"BD0030", "(SoD)  Siege du Poing Enflamme"},
	{"BD0040", "(SoD)  Auberge des Trois Vieilles Chopes"},
	{"BD0050", "(SoD)  Trône de Fer"},
	{"BD0060", "  Aléatoire, Entree de la Caverne"},
	{"BD0061", "  Aléatoire, Intérieur de la Caverne"},
	{"BD0062", "  Aléatoire, Bassin de la Caverne"},
	{"BD0063", "  Aléatoire, Embuscade"},
	{"BD0064", "  Aléatoire, Chemin dans la forêt"},
	{"BD0065", "  Aléatoire, Territoire sauvage"},
	{"BD0066", "  Aléatoire, Trou béant"},
	{"BD0067", "  Aléatoire, Intérieur du trou béant"},
	{"BD0070", "Cinématique du Bassin, L'homme à la capuche"},
	{"BD0071", "Cinématique du Bassin, Caelar"},
	{"BD0100", "(SoD)  Palais Ducal, L2"},
	{"BD0101", "(SoD)  Palais Ducal, Le grand depart"},
	{"BD0102", "(SoD)  Palais Ducal, L1"},
	{"BD0103", "(SoD)  Palais Ducal, L3"},
	{"BD0104", "(SoD)  Siege du Poing Enflamme"},
	{"BD0105", "(SoD)  Siege du Poing Enflamme, Sous-sol"},
	{"BD0106", "(SoD)  Auberge des Trois Vieilles Chopes, L1"},
	{"BD0107", "(SoD)  Auberge des Trois Vieilles Chopes, L2"},
	{"BD0108", "(SoD)  Auberge des Trois Vieilles Chopes, L3"},
	{"BD0109", "(SoD)  Taverne du Chant de l'elfe, L1"},
	{"BD0110", "(SoD)  Taverne du Chant de l'elfe, L2"},
	{"BD0111", "(SoD)  Trône de Fer, L1"},
	{"BD0112", "(SoD)  Porte de Baldur Est, Le grand depart"},
	{"BD0113", "(SoD)  Caverne des Vers, (Rivière souterraine)"},
	{"BD0114", "(SoD)  Trou des araignées, (Forêt des dragons)"},
	{"BD0115", "(SoD)  Grotte du Vampire, (Forêt de la Voie Côtière)"},
	{"BD0116", "(SoD)  Palais Ducal, Sous-sol"},
	{"BD0117", "(SoD)  Palais Ducal, Sous-sol"},
	{"BD0118", "Cinématique du Bassin, Imoen"},
	{"BD0120", "(SoD)  Donjon de Korlasz, L1"},
	{"BD0121", "(SoD)  Bazar Magique, L1"},
	{"BD0122", "(SoD)  Bazar Magique, L2"},
	{"BD0130", "(SoD)  Donjon de Korlasz, L2"},
	{"BD1000", "(SoD)  Pont de la Voie Côtière"},
	{"BD1010", "(SoD)  Grotte du Mimique, (Défilé du Trépassé)"},
	{"BD1100", "(SoD)  Site d'excavation nain, (Pont de la Voie Côtière)"},
	{"BD1200", "(SoD)  Repaire de la liche, (Site d'excavation nain)"},
	{"BD2000", "(SoD)  Pont de Boreskyr / Fort-du-Pont"},
	{"BD2010", "(SoD)  Grotte, (Fort-du-Pont)"},
	{"BD2100", "(SoD)  Fort-du-Pont"},
	{"BD3000", "(SoD)  Camp de la coalition"},
	{"BD4000", "(SoD)  Château Paldragon"},
	{"BD4100", "(SoD)  Château Paldragon, L1"},
	{"BD4300", "(SoD)  Château Paldragon, Sous-sols"},
	{"BD4400", "(SoD)  Avernus, (Portail)"},
	{"BD4500", "(SoD)  Le pont d'Avernus"},
	{"BD4600", "(SoD)  Tour de basalte, (Avernus)"},
	{"BD4601", "(SoD)  Élévateur, (Avernus)"},
	{"BD4700", "(SoD)  Sommet de l'Avernus, (Belhifet)"},
	{"BD5000", "(SoD)  Entree de la Rivière souterraine"},
	{"BD5100", "(SoD)  Rivière souterraine"},
	{"BD5110", "(SoD)  Grotte de l'Ettin, (Rivière souterraine)"},
	{"BD5200", "(SoD)  Les terriers sous le Château Paldragon"},
	{"BD5300", "(SoD)  Kanaglym"},
	{"BD6000", "(SoD)  Égouts / Caverne"},
	{"BD6200", "(SoD)  Sortie des égouts / Groupe pour BG2"},
	{"BD6100", "(SoD)  Transition / Fin de SoD"},
	{"BD7000", "(SoD)  Forêt de la Voie Côtière"},
	{"BD7100", "(SoD)  Bois des Griffes de Troll"},
	{"BD7110", "(SoD)  Grotte des Trolls"},
	{"BD7200", "(SoD)  Forêt des dragons"},
	{"BD7210", "(SoD)  Caverne aux Dragons, (Forêt des dragons)"},
	{"BD7220", "(SoD)  Grotte des Gobelours, (Caverne aux Dragons)"},
	{"BD7230", "(SoD)  Temple de Cyric, (Grotte des Gobelours)"},
	{"BD7300", "(SoD)  Défilé du Trépassé"},
	{"BD7310", "(SoD)  Cave dissimulée, (Défilé du Trépassé)"},
	{"BD7400", "(SoD)  Bosquet d'Ecorsang"},
	{"BD7410", "(SoD)  Cave du vampire, (Bosquet d'Ecorsang)"},
	
	--SoA Areas
	
	{"AR0011", "(Rêve)  Souvenirs de Château-Suif"},
	{"AR0012", "(Rêve)  Attire la bête ici... c'est ta seule chance"},
	{"AR0013", "(Rêve)  Ce que vous pouvez être"},
	{"AR0014", "(Rêve)  Un, deux, trois, quatre... CINQ"},
	{"AR0020", "  LES PORTES DE LA VILLE"},
	{"AR0021", "(P)  Auberge du Crâne Tordu, L1"},
	{"AR0022", "(P)  Auberge du Crâne Tordu, L2"},
	{"AR0028", "(Rêve)  Abandonnez une partie de vous même"},
	{"AR0041", "  Aléatoire, Ville 1"},
	{"AR0042", "  Aléatoire, Forêt 1"},
	{"AR0043", "  Aléatoire, Forêt 2 (Roche)"},
	{"AR0044", "  Aléatoire, Forêt 3 (sable)"},
	{"AR0045", "  Aléatoire, Ville 2"},
	{"AR0046", "  Aléatoire, Ville 3 (pont)"},
	{"AR0060", "Néant"},
	{"AR0061", "Néant"},
	{"AR0062", "Néant"},
	{"AR0063", "Néant"},
	{"AR0064", "Néant"},
	{"AR0065", "Néant"},
	{"AR0069", "(Ciné)  Qu'ils pourrissent à Spellhold !"},
	{"AR0070", "(Ciné)  Irenicus prend le contrôle de Spellhold"},
	{"AR0071", "(Ciné)  Imoen perd son Âme à Spellhold (Chapitre )')"},
	{"AR0072", "(Ciné)  Irenicus et Bodhi à Ust Natha (Chapitre )"},
	{"AR0082", "(P)  Auberge du Crâne Tordu, Liche"},
	{"AR0083", "(Rêve)  Apprendre à contrôler l'Echorcheur"},
	{"AR0084", "(Rêve) Tout est question de puissance"},
	{"AR0085", "(Rêve)  Ellésime et L'Arbre de Vie"},
	{"AR0086", "(CLUA)  Zone Boisée / Têtes de pierre"},
	{"AR0087", "(Ciné)  Diner avec les elfes"},
	{"AR0201", "(D-t)  Vers le village des goules et l'antre, (Œil Aveugle)"},
	{"AR0202", "(D-t)  Culte de l'Œil Aveugle"},
	{"AR0203", "(D-t)  Temple du dieu oublié, (Œil Aveugle)"},
	{"AR0204", "(D-t)  Les adeptes oubliés, (Œil Aveugle)"},
	{"AR0205", "(D-t)  L'antre de l'Œil Aveugle"},
	{"AR0206", "(D-t)  Le village des goules, (Œil Aveugle)"},
	{"AR0300", "  LES QUAIS"},
	{"AR0301", "(Q)  Guilde de Mae’Var, Planque"},
	{"AR0302", "(Q)  Guilde de Mae’Var, L1"},
	{"AR0303", "(Q)  Guilde de Mae’Var, L2"},
	{"AR0304", "(Q)  Guilde de Mae’Var, L3 (Edwin)"},
	{"AR0305", "(Q)  Guilde des Voleurs de l’Ombre, L1"},
	{"AR0306", "(Q)  Guilde des Voleurs de l’Ombre, L2 (Renal Bloodscalp)"},
	{"AR0307", "(Q)  Guilde des Voleurs de l’Ombre, L3 (Aran Linvail)"},
	{"AR0308", "(Q)  Domaine des Ménestrels, L1"},
	{"AR0309", "(Q)  Domaine des Ménestrels, L2"},
	{"AR0310", "(Q)  Taverne de la Bonté Marine, Pirates"},
	{"AR0311", "(B-q)  Maison de Gaelan Bayle, L1, (Chapitre 2)"},
	{"AR0312", "(B-q)  Maison de Gaelan Bayle, L2"},
	{"AR0313", "(Q)  Taverne de la Bonté Marine, L1"},
	{"AR0314", "(Q)  Taverne de la Bonté Marine, L2"},
	{"AR0315", "(Q)  Maison de Rayic Gethras, L1"},
	{"AR0316", "(Q)  Maison de Rayic Gethras, L2"},
	{"AR0317", "(Q)  Maison de Rayic Gethras, L3"},
	{"AR0318", "(Q)  Entrepôt"},
	{"AR0319", "(Q)  Temple d’Oghma"},
	{"AR0321", "(Q)  Guilde de Charname, Planque"},
	{"AR0322", "(Q)  Guilde de Charname, L1"},
	{"AR0323", "(Q)  Guilde de Charname, L2"},
	{"AR0324", "(Q)  Guilde de Charname, L3"},
	{"AR0325", "(Q)  Maison de Valygar Corthala, L1"},
	{"AR0326", "(Q)  Maison de Valygar Corthala, L1"},
	{"AR0327", "(Q)  Détruire la Guilde pour Bodhi, L1"},
	{"AR0328", "(Q)  Détruire la Guilde pour Bodhi, L2"},
	{"AR0329", "(Q)  Détruire la Guilde pour Bodhi, L3 (Aran Linvail)"},
	{"AR0330", "(Q)  Maison abandonnée, L1 (Kangaxx)"},
	{"AR0331", "(Q)  Maison abandonnée, Cellier (Kangaxx)"},
	{"AR0332", "(Q)  Caserne, L1"},
	{"AR0333", "(Q)  Caserne, L2"},
	{"AR0334", "(Q)  Forge de Cromwell"},
	{"AR0335", "(Q)  Maison, (Au dessus de la forge)"},
	{"AR0400", "  LES BAS QUARTIERS"},
	{"AR0401", "(B-q)  Maison de la famille Jansen, Cellier"},
	{"AR0402", "(B-q)  Maison de la famille Jansen, L1"},
	{"AR0403", "(B-q)  Maison de la famille Jansen, L2"},
	{"AR0404", "(B-q)  Les égouts"},
	{"AR0405", "(B-q)  Repaire des esclavagistes"},
	{"AR0406", "(B-q)  La Couronne de Cuivre, (Nalia, Anomen, Clara, Korgan)"},
	{"AR0407", "(Q)  Maison de Prebek et Sanasha"},
	{"AR0408", "(B-q)  Temple d’Ilmater"},
	{"AR0409", "(B-q)  Maison abandonnée, Baron Ployer"},
	{"AR0410", "(B-q)  Salle de navigation, (Sphere planaire)"},
	{"AR0411", "(B-q)  Sphere planaire"},
	{"AR0412", "(B-q)  Salle de la Fournaise, (Sphere planaire)"},
	{"AR0413", "(B-q)  Noyau de puissance, (Sphere planaire)"},
	{"AR0414", "(B-q)  Enfer, (Sphere planaire)"},
	{"AR0415", "(Q)  Maison, L1 (à gauche de la caserne)"},
	{"AR0416", "(Q)  Maison, L2 (à gauche de la caserne)"},
	{"AR0417", "(B-q)  Maison de Borinall"},
	{"AR0418", "(B-q)  Myconides, (Les égouts)"},
	{"AR0419", "(B-q)  Myconides, (Sphere planaire)"},
	{"AR0420", "(B-q)  Hommes-Lézard, (Sphere planaire)"},
	{"AR0500", "  DISTRICT DU PONT"},
	{"AR0501", "(Pont)  Échoppe du tanneur, L1"},
	{"AR0502", "(Pont)  Échoppe du tanneur, Cellier"},
	{"AR0503", "(Pont)  Échoppe du tanneur, Quais"},
	{"AR0504", "(Pont)  Domaine Saerk Farrahd, L1"},
	{"AR0505", "(Pont)  Domaine Saerk Farrahd, L2"},
	{"AR0506", "(Pont)  Domaine Balthis"},
	{"AR0507", "(Pont)  Maison barricadée, L1"},
	{"AR0508", "(Pont)  Maison barricadée, L2"},
	{"AR0509", "(Pont)  Auberge des Cinq Chopes, L1"},
	{"AR0510", "(Pont)  Auberge des Cinq Chopes, Théâtre"},
	{"AR0511", "(Pont)  Auberge des Cinq Chopes, L2"},
	{"AR0512", "(Pont)  Temple de Heaum"},
	{"AR0513", "(Pont)  Auberge de Delosar, L1"},
	{"AR0514", "(Pont)  Auberge de Delosar, L2"},
	{"AR0515", "(Pont)  Auberge de Delosar, L3"},
	{"AR0516", "(Pont)  Prison Planaire"},
	{"AR0517", "(Pont)  Cellule des Githyankis, (Prison Planaire)"},
	{"AR0518", "(Pont)  Cellule des Muloups, (Prison Planaire)"},
	{"AR0519", "(Pont)  Cellule des Éfrits, (Prison Planaire)"},
	{"AR0520", "(Pont)  Cellule des Minotaures, (Prison Planaire)"},
	{"AR0521", "(Pont)  Cellule des Golems, (Prison Planaire)"},
	{"AR0522", "(Pont)  Auberge des Cinq Chopes, (Forteresse)"},
	{"AR0523", "(Pont)  Théâtre, (Forteresse du Barde)"},
	{"AR0525", "(Pont)  Maison, L1 (Liche élémentaire)"},
	{"AR0526", "(Pont)  Sarcophage de la Liche élémentaire"},
	{"AR0527", "(Pont)  Maison du poissonnier, L1"},
	{"AR0528", "(Pont)  Maison du poissonnier, L2"},
	{"AR0529", "(Pont)  Planque de Neb"},
	{"AR0530", "(Pont)  Entrepôt, (Groupe maléfique)"},
	{"AR0531", "(Pont)  Maison de roturiers"},
	{"AR0600", "(W)  Chapiteau, Illusion"},
	{"AR0601", "(W)  Donjon d'Irenicus, Plan de l'air"},
	{"AR0602", "(W)  Donjon d'Irenicus, L1 (Imoen, Jaheira, Minsc)"},
	{"AR0603", "(W)  Donjon d'Irenicus, L2 (Yoshimo)"},
	{"AR0604", "(W)  Chapiteau, Illusion L1, (Aerie)"},
	{"AR0605", "(W)  Chapiteau, Illusion L2"},
	{"AR0606", "(W)  Chapiteau, Illusion L3, (Kalah)"},
	{"AR0607", "(W)  Le Chapiteau, (Quayle)"},
	{"AR0700", "  LA PROMENADE DE WAUKYNE"},
	{"AR0701", "(D-t)  Les égouts"},
	{"AR0702", "(W)  Le Marché de l'Aventurier"},
	{"AR0703", "(W)  Temple d'Ilmater"},
	{"AR0704", "(W)  Auberge du Bonrepos (Mithrest)"},
	{"AR0705", "(D-t)  Planque de Mekrath, égouts, (Haer'Dalis)"},
	{"AR0706", "(W)  Armurier / Fabricant de flèches"},
	{"AR0707", "(W)  Échoppe d'Enge"},
	{"AR0708", "(W)  Maison de Cernd"},
	{"AR0709", "(W)  Antre des Sept Vaux, L1"},
	{"AR0710", "(W)  Maison de Fennecia"},
	{"AR0711", "(D-t)  Planque des Illithids, (égouts)"},
	{"AR0712", "(W)  Antre des Sept Vaux, L2"},
	{"AR0713", "(W)  Restaurant, (Au dessus de la maison de Cernd)"},
	{"AR0714", "(Ciné)  Irenicus à la promenade de Waukyne"},
	{"AR0800", "  DISTRICT DU CIMETIÈRE"},
	{"AR0801", "(C)  Catacombes,(Détruire la Guilde pour Aran)"},
	{"AR0802", "(C)  Catacombes, (Parchemin Néthère, Livre de Kaza)"},
	{"AR0803", "(C)  Antre de Bodhi, (Détruire la Guilde pour Aran)"},
	{"AR0804", "(C)  Bosquet de Pai'Na"},
	{"AR0805", "(C)  Crypte, Nord"},
	{"AR0806", "(C)  Crypte, (Roi de la crypte)"},
	{"AR0807", "(C)  Crypte, Est"},
	{"AR0808", "(C)  Catacombes, (L'Âme d'Imoen, Romance)"},
	{"AR0809", "(C)  Antre de Bodhi, (L'Âme d'Imoen, Romance)"},
	{"AR0810", "(C)  Crypte, Sud"},
	{"AR0811", "(C)  Crypte, Sud-Est"},
	{"AR0812", "(C)  Crypte 1 centrale"},
	{"AR0813", "(C)  Crypte 2 centrale"},
	{"AR0900", "  DISTRICT DU TEMPLE"},
	{"AR0901", "(D-t)  Temple de Heaum"},
	{"AR0902", "(D-t)  Temple de Lathandre"},
	{"AR0903", "(D-t)  Ordre du Cœur Radieux"},
	{"AR0904", "(D-t)  Temple de Talos"},
	{"AR0905", "(D-t)  Domaine Pimlico"},
	{"AR0906", "(D-t)  Cour gardée, L1"},
	{"AR0907", "(D-t)  Cour gardée, L2"},
	{"AR1000", "  DISTRICT DU GOUVERNEMENT"},
	{"AR1001", "(G)  Domaine Delryn"},
	{"AR1002", "(G)  Bâtiment du Conseil des Six"},
	{"AR1003", "(G)  Domaine Firecam"},
	{"AR1004", "(G)  Domaine Deril, (Quête de Cernd)"},
	{"AR1005", "(G)  Prison"},
	{"AR1006", "(G)  Domaine Jysstev, (Quête du prêtre)"},
	{"AR1007", "(G)  Maison, Nord"},
	{"AR1008", "(Pont)  Rune Tordue"},
	{"AR1009", "(G)  Maison d'Isaea Roenall"},
	{"AR1010", "(G)  Temple de Waukyne"},
	{"AR1100", "(Imn)  Collines d'Umar"},
	{"AR1101", "(Imn)  Cabane de Valygar"},
	{"AR1102", "(Imn)  Cabane de Merella"},
	{"AR1103", "(Imn)  Maison de Jermien"},
	{"AR1104", "(Imn)  Maison du maire Lloyd"},
	{"AR1105", "(Imn)  Auberge d'Imnesvale"},
	{"AR1106", "(Imn)  Grotte d'Umar"},
	{"AR1107", "(Imn)  Forteresse du rôdeur"},
	{"AR1200", "(C-L)  Collines de Lancevent"},
	{"AR1201", "(C-L)  Donjon de Firkraag, Entrée"},
	{"AR1202", "(C-L)  Donjon de Firkraag, , Labyrinthe"},
	{"AR1203", "(C-L)  Tanière de Firkraag"},
	{"AR1204", "(C-L)  Cabane de Garren Lancevent"},
	{"AR1300", "(Arn)  Forteresse De'Arnise, (Assiégée)"},
	{"AR1301", "(Arn)  Sous-sols De'Arnise, (Torgal)"},
	{"AR1302", "(Arn)  Forteresse De'Arnise, L1"},
	{"AR1303", "(Arn)  Forteresse De'Arnise, L2"},
	{"AR1304", "(Arn)  Forteresse De'Arnise, (Libérée)"},
	{"AR1305", "(Arn)  Forteresse du guerrier, Sous-sols"},
	{"AR1306", "(Arn)  Forteresse du guerrier, L1"},
	{"AR1307", "(Arn)  Forteresse du guerrier, L2"},
	{"AR1400", "(Um)  Ruines du temple (Illuminé)"},
	{"AR1401", "(Um)  Donjon du Temple"},
	{"AR1402", "(Um)  Tanière de Thaxll'ssillyia"},
	{"AR1403", "(Um)  Grotte du loup, (Anath)"},
	{"AR1404", "(Um)  Ruines du temple, (Ténèbre)"},
	{"AR1500", "(SP)  Asile de Spellhold"},
	{"AR1501", "(SP)  Salle de la terre (Jugement)"},
	{"AR1502", "(SP)  Salle du feu, (Jugement)"},
	{"AR1503", "(SP)  Salle des spores, (Jugement)"},
	{"AR1504", "(SP)  Salle piégée (Jugement)"},
	{"AR1505", "(SP)  Salle des leviers (Jugement)"},
	{"AR1506", "(SP)  Salle des Trolls, (Jugement)"},
	{"AR1507", "(SP)  Salle des Kobolds, (Jugement)"},
	{"AR1508", "(SP)  Jugement Final"},
	{"AR1509", "(SP)  Salle des Myconides, (Jugement)"},
	{"AR1510", "(SP)  Salle des Sahuagins, (Jugement)"},
	{"AR1511", "(SP)  Dîner (Jugement)"},
	{"AR1512", "(SP)  Le Vampire et l'Enfant, L1 (Imoen)"},
	{"AR1513", "(SP)  Le Vampire et l'Enfant, L2"},
	{"AR1514", "(SP)  Le Vampire et l'Enfant, L3 (L'Écorcheur)"},
	{"AR1515", "(SP)  Asile de Spellhold, L1 (Coordinateur) "},
	{"AR1516", "(SP)  Asile de Spellhold, L2 (Rituel)"},
	{"AR1600", "  BRYNNLAW"},
	{"AR1601", "(Bry)  Demeure de Desharik"},
	{"AR1602", "(Bry)  Auberge du Singe vulgaire"},
	{"AR1603", "(Bry)  Magasin"},
	{"AR1604", "(Bry)  Temple d'Umberlee"},
	{"AR1605", "(Bry)  Maison de Perth l'adepte"},
	{"AR1606", "(Bry)  Maison de Cayia"},
	{"AR1607", "(MER)  L'assaut des Githyanki"},
	{"AR1608", "(Bry)  Passage de la Maison Close"},
	{"AR1609", "(Bry)  Chambre à Coucher"},
	{"AR1610", "(Bry)  Prison de la Maison Close"},
	{"AR1611", "(Bry)  Entrée de la Maison Close"},
	{"AR1612", "(Bry)  Cuisine de la Maison Close"},
	{"AR1613", "(Bry)  Chambre à Coucher, (Capitaine Rerdes)"},
	{"AR1700", "(Amn)  Passe du Petit Croc"},
	{"AR1800", "(Amn)  Forêt de nord"},
	{"AR1900", "(B-d)  Bosquet des druides"},
	{"AR1901", "(B-d)  Bosquet, (Faldorn)"},
	{"AR1902", "(B-d)  Marchande de potions, (Ihtafeer)"},
	{"AR1904", "(B-d)  Tertre aux trolls"},
	{"AR1905", "(B-d)  Tour de l'ogre"},
	{"AR2000", "  FRANC-MARCHÉ"},
	{"AR2001", "(F-M)  Forgeron"},
	{"AR2002", "(F-M)  Maison Fentan"},
	{"AR2006", "(F-M)  Maison de Tiri"},
	{"AR2007", "(F-M)  Domaine du Haut Marchand, (Logan Coprith)"},
	{"AR2008", "(F-M)  Temple de Waukyne"},
	{"AR2009", "(F-M)  Prison de Franc-Marché"},
	{"AR2010", "(F-M)  Taverne de Vyatri"},
	{"AR2011", "(F-M)  Domaine Alibakkar"},
	{"AR2012", "(F-M)  Domaine Lurraxol"},
	{"AR2013", "(F-M)  Crypte de Franc-Marché"},
	{"AR2014", "(F-M)  Tente des djinns"},
	{"AR2015", "(F-M)  Tente du marchand"},
	{"AR2016", "(F-M)  Tente de Raffee"},
	{"AR2017", "(F-M)  Tente de Madame Jeanne"},
	{"AR2018", "(CLUA)  Tente"},
	{"AR2100", "(O-T)  Ombre-Terre, (Chapitre 5)"},
	{"AR2101", "(O-T)  Tunnels du sud, (Orbe ancien)"},
	{"AR2102", "(O-T)  Tanière d'Adalon"},
	{"AR2200", "  UST NATHA"},
	{"AR2201", "(O-T)  Temple de Lolth"},
	{"AR2202", "(O-T)  Taverne d'Ust Natha, L1"},
	{"AR2203", "(O-T)  Taverne d'Ust Natha, L1"},
	{"AR2204", "(O-T)  Société des Combattantes"},
	{"AR2205", "(O-T)  Société des Combattants"},
	{"AR2206", "(O-T)  Demeure de Qilue"},
	{"AR2207", "(O-T)  Tour de Deirex"},
	{"AR2208", "(O-T)  Planque de Jarlaxle"},
	{"AR2209", "(O-T)  Demeure Jae'llat"},
	{"AR2210", "(O-T)  Tour de Deirex, Sous-sol"},
	{"AR2300", "(MER)  La cité des Sahuagins"},
	{"AR2400", "(O-T)  Tunnels de l'est, Maître-Cerveau"},
	{"AR2401", "(O-T)  Vers la surface"},
	{"AR2402", "(O-T)  Tunnels de l'ouest, Prince Kuo-Toa"},
	{"AR2500", "(Amn)  Sortie de l'ombre-terre, (Elhan, Chapitre 6)"},
	{"AR2600", "(Amn)  Forêt de Téthyr, (Safana, Coran)"},
	{"AR2601", "  Aléatoire, Drizzt Do'Urden"},
	{"AR2602", "(Amn)  Cave dans la Forêt de Téthyr"},
	{"AR2603", "(Amn)  Cabane de Coran"},
	{"AR2700", "(CLUA)  Zone Boisée / Têtes de pierre"},
	{"AR2800", "  SULDANESSELLAR, (Chapitre 7 / 19)"},
	{"AR2801", "(Sun)  Maison de la grande prêtresse Demin"},
	{"AR2802", "(Sun)  Maison de la Corne"},
	{"AR2803", "(Sun)  Temple de Rillifane, (Suneer)"},
	{"AR2804", "(Sun)  Vers L'Arbre de Vie (Entrée cachée)"},
	{"AR2805", "(Sun)  Vers L'Arbre de Vie (Entrée révélée)"},
	{"AR2806", "(Sun)  L'Arbre de Vie"},
	{"AR2807", "(Sun)  Tanière de Nizidramanii'yt"},
	{"AR2808", "(Sun)  Maison de la Lune"},
	{"AR2809", "(Sun)  Maison du talisman, Énigme"},
	{"AR2810", "(Sun)  Maison du prêtre"},
	{"AR2811", "(Sun)  Maison du harpiste"},
	{"AR2812", "(Sun)  Temple de Rillifane / Fin de SoA"},
	{"AR2900", "(SoA)  Les Abysses / Fin de SoA"},
	{"AR2901", "(SoA)  Peur, Larme de Bhaal"},
	{"AR2902", "(SoA)  Fierté, Larme de Bhaal"},
	{"AR2903", "(SoA)  Cupidité, Larme de Bhaal"},
	{"AR2904", "(SoA)  Égoïste, Larme de Bhaal"},
	{"AR2905", "(SoA)  Colère, Larme de Bhaal"},
	{"AR2906", "Néant"},
	{"OH4000", "(SoA)  Amphithéâtre abandonné, Quête de Rasaad"},
	{"OH4010", "(SoA)  Les Larmes de Séluné, Quête de Rasaad"},
	{"OH4100", "(SoA)  Temple des hérétiques, Quête de Rasaad"},
	{"OH4101", "(SoA)  Intérieur du temple, Quête de Rasaad"},
	{"OH5000", "(SoA)  Le mariage au Cœur Radieux, Quête de Dorn"},
	{"OH5100", "(SoA)  Gorge de la Résurrection, Quête de Dorn"},
	{"OH5110", "(SoA)  Caverne de la Résurrection, Quête de Dorn"},
	{"OH5120", "(SoA)  Arbre de la Résurrection, Quête de Dorn"},
	{"OH5200", "(SoA)  Rivière de la Résurrection, Quête de Dorn"},
	{"OH5300", "(SoA)  Camp heaumite, Quête de Dorn"},
	{"OH6000", "(SoA)  Forêt Sauvage, Quête de Neera"},
	{"OH6010", "(SoA)  Rencontre aléatoire avec Neera"},
	{"OH6100", "(SoA)  Le Refuge Caché, Quête de Neera"},
	{"OH6200", "(SoA)  Le Refuge détruit, Quête de Neera"},
	{"OH6300", "(SoA)  Enclave des Sorciers Rouges, Quête de Neera"},
	{"OH7000", "(SoA)  Tombe de Dragomir, Quête de Hexxat"},
	{"OH7100", "(SoA)  Tombe inférieur Ouest, Quête de Hexxat"},
	{"OH7200", "(SoA)  Tombe inférieur Est, Quête de Hexxat"},
	
	--BP2  Areas
	
	{"OH8000", "(FN2)  Comptoir de Suzail"},
	{"OH8100", "(FN2)  Zone de repos"},
	{"OH8200", "(FN2)  Arène 1"},
	{"OH8300", "(FN2)  Arène 2"},
	{"OH8400", "(FN2)  Arène 3"},
	
	--Expansion Areas
	
	{"AR3000", "(ToB)  La Tour de Garde"},
	{"AR3001", "(Tour de Garde)  L'Autel, (1)"},
	{"AR3003", "(Tour de Garde)  La boussole, (3)"},
	{"AR3004", "(Tour de Garde)  Diantrefosse, (3)"},
	{"AR3005", "(Tour de Garde)  Tieffelins"},
	{"AR3006", "(Tour de Garde)  Succube, (3)"},
	{"AR3007", "(Tour de Garde)  Arbre, Cambion, (3)"},
	{"AR3008", "(Tour de Garde)  Menhir, (3)"},
	{"AR3009", "(Tour de Garde)  Salle de l'entropie, (3)"},
	{"AR3010", "(Tour de Garde)  Obelisk, (3)"},
	{"AR3011", "(Tour de Garde)  Elfe Fou, Journal, (3)"},
	{"AR3012", "(Tour de Garde)  Tahazzar, (3)"},
	{"AR3013", "(Tour de Garde)  Ka'rashur, (3)"},
	{"AR3014", "(Tour de Garde)  Spectre démoniaque, (3)"},
	{"AR3015", "(Tour de Garde)  Aesgareth, (3)"},
	{"AR3016", "(Tour de Garde)  Démon Chromatique, (2)"},
	{"AR3017", "(Tour de Garde)  Machine de Lum le Fou, (4)"},
	{"AR3018", "(Tour de Garde)  Saladrex le dragon, (4)"},
	{"AR3019", "(Tour de Garde)  Le fantôme d'Helmite, (5)"},
	{"AR3020", "(Tour de Garde)  L'Emprisonné, (6)"},
	{"AR3021", "(Tour de Garde)  Domaine des Illithids, (4)"},
	{"AR3022", "(Tour de Garde)  Githyankis Anti-Paladins, (4)"},
	{"AR3023", "(Tour de Garde)  Jeu de rôle, (5)"},
	{"AR3024", "(Tour de Garde)  Dragon, Épreuve d'Helmite (5)"},
	{"AR3025", "(Tour de Garde)  Horde, Épreuve d'Helmite (5)"},
	{"AR3026", "(Tour de Garde)  Diablotin, Épreuve d'Helmite (5)"},
	{"AR3027", "(Tour de Garde)  Crypte de la Demi-Liche, (4)"},
	
	--ToB Areas
	
	{"AR4000", "(ToB)  Forêt des Esprit, ILLASERA (Chapitre 8)"},
	{"AR4500", "(ToB)  Antichambre, (Sarevok)"},
	{"AR5000", "  SARADUSH"},
	{"AR5001", "(Gromnir)  Château de Saradush"},
	{"AR5002", "(Gromnir)  Planque de GROMNIR"},
	{"AR5003", "(S)  Taverne de l'Arbre à Chopines"},
	{"AR5004", "(S)  Temple de Waukyne"},
	{"AR5005", "(S)  Caserne de Gromnir"},
	{"AR5006", "(S)  Prison de Saradush"},
	{"AR5007", "(Gromnir)  Sous-sols du Château"},
	{"AR5008", "(S)  Demeure de Kiser, L1"},
	{"AR5009", "(CLUA)  Demeure de Kiser, L2"},
	{"AR5010", "(S)  Demeure de la comtesse Santele"},
	{"AR5011", "(S)  Archives des Arcanes, Lazarus Librarus"},
	{"AR5012", "(S)  Maison de paysans"},
	{"AR5013", "(S)  Égouts de Saradush"},
	{"AR5014", "(S)  Demeure de Kiser, Cellier"},
	{"AR5015", "(S)  Quartier général de la milice"},
	{"AR5016", "(S)  Cellules de la milice"},
	{"AR5200", "(Yaga-Shura)  Les Monts de la Marche"},
	{"AR5201", "(Yaga-Shura)  Montagne des géants du feu"},
	{"AR5202", "(Yaga-Shura)  Forêt de Mir, (Nyalee)"},
	{"AR5203", "(Yaga-Shura)  Camp de YAGA-SHURA"},
	{"AR5204", "(Yaga-Shura)  Cœur de Yaga-Shura"},
	{"AR5500", "  AMKETHRAN, (Chapitre 9 / 21)"},
	{"AR5501", "(Balthazar)  Taverne d'Amkethran"},
	{"AR5502", "(Balthazar)  Kerrick le forgeron, Lazarus Librarus"},
	{"AR5503", "(Balthazar)  Temple de Waukyne, (Chyil)"},
	{"AR5504", "(Balthazar)  Caverne des contrebandiers"},
	{"AR5505", "(Balthazar)  Demeure de BALTHAZAR"},
	{"AR5506", "(Balthazar)  Maison de roturiers"},
	{"AR5507", "(Balthazar)  Maison vide"},
	{"AR5508", "(Balthazar)  Maison de Majira et Faheed"},
	{"AR5509", "(Balthazar)  Grotte des Morts, (Vongoethe la liche)"},
	{"AR6000", "(Abazigal)  Enclave d'Abazigal, (Draconis)"},
	{"AR6001", "(Abazigal)  Entrée de l'Enclave"},
	{"AR6002", "(Abazigal)  Kuo-toa, Cellule, Corde, (Puits Est 2)"},
	{"AR6003", "(Abazigal)  Iycanth le fou, Statues, (Puits Central 3)"},
	{"AR6004", "(Abazigal)  Vers l'antre, Fll'Yissetat, (Puits Sud 4)"},
	{"AR6005", "(Abazigal)  Tanière d'ABAZIGAL"},
	{"AR6008", "(Abazigal)  Salamandres de glace, (Puits Ouest 1)"},
	{"AR6011", "(Abazigal)  Orbes Anciens, (Pédoncule)"},
	{"AR6012", "(Abazigal)  Maison de la respiration"},
	{"AR6100", "(Sendai)  Enclave de Sendai"},
	{"AR6101", "(Sendai)  Entrée de l'Enclave"},
	{"AR6102", "(Sendai)  Tunnel du Nord, (Duergars)"},
	{"AR6103", "(Sendai)  Tunnel du Sud, (Araignées)"},
	{"AR6104", "(Sendai)  Vers la maison d'Odamaron"},
	{"AR6105", "(Sendai)  Prêtresse Diaytha, L2"},
	{"AR6106", "(Sendai)  Capitaine Egeissag, L3"},
	{"AR6107", "(Sendai)  Mithykyll Le flagelleur mental, L3"},
	{"AR6108", "(Sendai)  Repaire de SENDAI"},
	{"AR6109", "(Sendai)  Caserne de elfes noirs"},
	{"AR6110", "(Sendai)  Maison d'Odamaron la liche, L1"},
	{"AR6111", "(Sendai)  Maison du Bûcheron"},
	{"AR6200", "(ToB)  Le Trône de Bhaal / Fin du Jeu"},
	{"AR6300", "(ToB)  Oasis du Téthyr"},
	{"AR6400", "(ToB)  Forêt du Nord, (Téthyr, Rivière)"},
	{"OH4200", "(ToB)  Rocheprofonde, Quête de Rasaad"},
	{"OH4210", "(ToB)  Clan de Rocheprofonde, Quête de Rasaad"},
	{"OH4220", "(ToB)  Mines de Rocheprofonde, Quête de Rasaad"},
	{"OH4230", "(ToB)  Plan de l'ombre, Quête de Rasaad"},
	{"OH4290", "(ToB)  l'embuscade des Sharrans, Quête de Rasaad"},
	{"OH5400", "(ToB)  Clairière de la forêt, Quête de Dorn"},
	{"OH5500", "(ToB)  Lunia, Quête de Dorn"},
	{"OH6400", "(ToB)  Clairière, Quête de Neera"},
	{"OH6450", "(ToB)  Arène des Fosses noires, Quête de Neera"},
	{"OH6460", "(ToB)  Salle de repos des Fosses noires, Quête de Neera"},
	{"OH6500", "(ToB)  Domaine Thayen, Quête de Neera"},
	{"OH7300", "(ToB)  Labyrinthe de Korkorran, Quête de Hexxat"},
	{"OH7310", "(ToB)  Scene with L, Quête de Hexxat"},
}