ACTION_IF FILE_EXISTS_IN_GAME ~bgee.lua~ BEGIN
	COPY_EXISTING ~bgee.lua~ ~override/bgee.lua~

	// CheatsAreas pour BGEE
	
	REPLACE_TEXTUALLY ~{"BG0002", "N Baldur's Gate: Temple of Helm"},~                                          ~{"BG0002", "(BG)  Temple de Heaum (N)"},~
	REPLACE_TEXTUALLY ~{"BG0004", "N Baldur's Gate: Bheren's House L1"},~                                       ~{"BG0004", "(BG)  Maison de Bheren, L1 (N)"},~
	REPLACE_TEXTUALLY ~{"BG0005", "N Baldur's Gate: Bheren's House L2"},~                                       ~{"BG0005", "(BG)  Maison de Bheren, L2 (Ange, le chat) (N)"},~
	REPLACE_TEXTUALLY ~{"BG0006", "N Baldur's Gate: Rinnie's House L1"},~                                       ~{"BG0006", "(BG)  Maison de Rinnie, L1 (N)"},~
	REPLACE_TEXTUALLY ~{"BG0007", "N Baldur's Gate: Rinnie's House L2"},~                                       ~{"BG0007", "(BG)  Maison de Rinnie, L2 (N)"},~
	REPLACE_TEXTUALLY ~{"BG0008", "N Baldur's Gate: House1 L1"},~                                               ~{"BG0008", "(BG)  Maison 1, L1 (N)"},~
	REPLACE_TEXTUALLY ~{"BG0009", "N Baldur's Gate: House1 L2"},~                                               ~{"BG0009", "(BG)  Maison 1, L2 (N)"},~
	REPLACE_TEXTUALLY ~{"BG0010", "N Baldur's Gate: Jardak's House L1"},~                                       ~{"BG0010", "(BG)  Maison de Jardak, L1 (N)"},~
	REPLACE_TEXTUALLY ~{"BG0011", "N Baldur's Gate: Jardak's House L2"},~                                       ~{"BG0011", "(BG)  Maison de Jardak, L2 (N)"},~
	REPLACE_TEXTUALLY ~{"BG0012", "N Baldur's Gate: House2 L1"},~                                               ~{"BG0012", "(BG)  Maison 2, L1 (N)"},~
	REPLACE_TEXTUALLY ~{"BG0013", "N Baldur's Gate: House2 L2"},~                                               ~{"BG0013", "(BG)  Maison 2, L2 (N)"},~
	REPLACE_TEXTUALLY ~{"BG0014", "N Baldur's Gate: House3 L1"},~                                               ~{"BG0014", "(BG)  Maison 3, L1 (N)"},~
	REPLACE_TEXTUALLY ~{"BG0015", "N Baldur's Gate: House3 L2"},~                                               ~{"BG0015", "(BG)  Maison 3, L2 (N)"},~
	REPLACE_TEXTUALLY ~{"BG0016", "N Baldur's Gate: House4 L1"},~                                               ~{"BG0016", "(BG)  Maison 4, L1 (N)"},~
	REPLACE_TEXTUALLY ~{"BG0017", "N Baldur's Gate: House4 L2"},~                                               ~{"BG0017", "(BG)  Maison 4, L2 (N)"},~
	REPLACE_TEXTUALLY ~{"BG0018", "N Baldur's Gate: House5 L1"},~                                               ~{"BG0018", "(BG)  Maison 5, L1 (N)"},~
	REPLACE_TEXTUALLY ~{"BG0019", "N Baldur's Gate: House5 L2"},~                                               ~{"BG0019", "(BG)  Maison 5, L2 (N)"},~
	REPLACE_TEXTUALLY ~{"BG0020", "N Baldur's Gate: House6 L1"},~                                               ~{"BG0020", "(BG)  Maison 6, L1 (N)"},~
	REPLACE_TEXTUALLY ~{"BG0021", "N Baldur's Gate: House6 L2"},~                                               ~{"BG0021", "(BG)  Maison 6, L2 (N)"},~
	REPLACE_TEXTUALLY ~{"BG0100", "NW Baldur's Gate"},~                                                         ~{"BG0100", "  La Porte de Baldur, NORD-OUEST"},~
	REPLACE_TEXTUALLY ~{"BG0101", "NW Baldur's Gate: Silvershield Estate L1"},~                                 ~{"BG0101", "(BG)  Domaine Écudargent, L1 (NO)"},~
	REPLACE_TEXTUALLY ~{"BG0102", "NW Baldur's Gate: Silvershield Estate L2"},~                                 ~{"BG0102", "(BG)  Domaine Écudargent, L2 Skie (NO)"},~
	REPLACE_TEXTUALLY ~{"BG0103", "NE Baldur's Gate: Splurging Sturgeon L1"},~                                  ~{"BG0103", "(BG)  Taverne de l'Esturgeon Sautillant, L1 (NE)"},~
	REPLACE_TEXTUALLY ~{"BG0104", "NE Baldur's Gate: Splurging Sturgeon L2"},~                                  ~{"BG0104", "(BG)  Taverne de l'Esturgeon Sautillant, L2 (NE)"},~
	REPLACE_TEXTUALLY ~{"BG0105", "SE Baldur's Gate: Blade & Stars L1"},~                                       ~{"BG0105", "(BG)  Auberge de la Lame et des Étoiles, L1 (SE)"},~
	REPLACE_TEXTUALLY ~{"BG0106", "SE Baldur's Gate: Blade & Stars L2"},~                                       ~{"BG0106", "(BG)  Auberge de la Lame et des Étoiles, L2 (SE)"},~
	REPLACE_TEXTUALLY ~{"BG0107", "SE Baldur's Gate: Blade & Stars L3"},~                                       ~{"BG0107", "(BG)  Auberge de la Lame et des Étoiles, L3 (SE)"},~
	REPLACE_TEXTUALLY ~{"BG0108", "N Baldur's Gate: Ducal Palace L1"},~                                         ~{"BG0108", "(BG)  Palais Ducal, L1 (N)"},~
	REPLACE_TEXTUALLY ~{"BG0109", "N Baldur's Gate: Ducal Palace L2"},~                                         ~{"BG0109", "(BG)  Palais Ducal, L2 (N)"},~
	REPLACE_TEXTUALLY ~{"BG0110", "N Baldur's Gate: Ducal Palace L3"},~                                         ~{"BG0110", "(BG)  Palais Ducal, L3 (N)"},~
	REPLACE_TEXTUALLY ~{"BG0111", "N Baldur's Gate: Ducal Palace Cellar"},~                                     ~{"BG0111", "(BG)  Palais Ducal, Sous-sol du palais (N)"},~
	REPLACE_TEXTUALLY ~{"BG0112", "Baldur's Gate Undercellars"},~                                               ~{"BG0112", "(BG)  Caves Souterraines, (NE)"},~
	REPLACE_TEXTUALLY ~{"BG0114", "NE Baldur's Gate: Blushing Mermaid L1"},~                                    ~{"BG0114", "(BG)  Taverne de la Sirène Rougissante, L1 (NE)"},~
	REPLACE_TEXTUALLY ~{"BG0115", "NE Baldur's Gate: Blushing Mermaid L2"},~                                    ~{"BG0115", "(BG)  Taverne de la Sirène Rougissante, L2 (NE)"},~
	REPLACE_TEXTUALLY ~{"BG0116", "NW Baldur's Gate: Helm & Cloak L1"},~                                        ~{"BG0116", "(BG)  Auberge du Heaume et de la Cape, L1 (NO)"},~
	REPLACE_TEXTUALLY ~{"BG0117", "NW Baldur's Gate: Helm & Cloak L2"},~                                        ~{"BG0117", "(BG)  Auberge du Heaume et de la Cape, L2 (NO)"},~
	REPLACE_TEXTUALLY ~{"BG0118", "NW Baldur's Gate: Helm & Cloak L3"},~                                        ~{"BG0118", "(BG)  Auberge du Heaume et de la Cape, L3 (NO)"},~
	REPLACE_TEXTUALLY ~{"BG0119", "N Baldur's Gate: Three Old Kegs L1"},~                                       ~{"BG0119", "(BG)  Auberge des Trois Vieilles Chopes, L1 (N)"},~
	REPLACE_TEXTUALLY ~{"BG0120", "N Baldur's Gate: Three Old Kegs L2"},~                                       ~{"BG0120", "(BG)  Auberge des Trois Vieilles Chopes, L2 (N)"},~
	REPLACE_TEXTUALLY ~{"BG0121", "N Baldur's Gate: Three Old Kegs L3"},~                                       ~{"BG0121", "(BG)  Auberge des Trois Vieilles Chopes, L3 (N)"},~
	REPLACE_TEXTUALLY ~{"BG0123", "Undercity"},~                                                                ~{"BG0123", "(BG)  Ville souterraine, Ruines (E)"},~
	REPLACE_TEXTUALLY ~{"BG0125", "Undercity: Temple of Bhaal"},~                                               ~{"BG0125", "(BG)  Temple de Bhaal, (E)"},~
	REPLACE_TEXTUALLY ~{"BG0126", "W Baldur's Gate: Ragefast's House"},~                                        ~{"BG0126", "(BG)  Maison de Ragevite, (O)"},~
	REPLACE_TEXTUALLY ~{"BG0127", "SW Baldur's Gate: Merchant League L1"},~                                     ~{"BG0127", "(BG)  Ligue des Marchands, L1 (SO)"},~
	REPLACE_TEXTUALLY ~{"BG0128", "SW Baldur's Gate: Merchant League L2"},~                                     ~{"BG0128", "(BG)  Ligue des Marchands, L2 (SO)"},~
	REPLACE_TEXTUALLY ~{"BG0129", "SW Baldur's Gate: Merchant League L3"},~                                     ~{"BG0129", "(BG)  Ligue des Marchands, L3 (SO)"},~
	REPLACE_TEXTUALLY ~{"BG0130", "W Baldur's Gate: Hall of Wonders"},~                                         ~{"BG0130", "(BG)  Maison des Merveilles, Alora (O)"},~
	REPLACE_TEXTUALLY ~{"BG0131", "W Baldur's Gate: High House of Wonders"},~                                   ~{"BG0131", "(BG)  Temple de Gond, (O)"},~
	REPLACE_TEXTUALLY ~{"BG0132", "W Baldur's Gate: Lady's House"},~                                            ~{"BG0132", "(BG)  Manoir de la Dame, (O)"},~
	REPLACE_TEXTUALLY ~{"BG0133", "Baldur's Gate Docks: Low Lantern D1"},~                                      ~{"BG0133", "(BG)  Auberge de la Lanterne assourdie, D1 (S)"},~
	REPLACE_TEXTUALLY ~{"BG0134", "Baldur's Gate Docks: Low Lantern D2"},~                                      ~{"BG0134", "(BG)  Auberge de la Lanterne assourdie, D2 (S)"},~
	REPLACE_TEXTUALLY ~{"BG0135", "Baldur's Gate Docks: Low Lantern D3"},~                                      ~{"BG0135", "(BG)  Auberge de la Lanterne assourdie, D3 (S)"},~
	REPLACE_TEXTUALLY ~{"BG0136", "Baldur's Gate Docks: Low Lantern D4"},~                                      ~{"BG0136", "(BG)  Auberge de la Lanterne assourdie, D4 (S)"},~
	REPLACE_TEXTUALLY ~{"BG0137", "N Baldur's Gate: Ramazith's Tower L1"},~                                     ~{"BG0137", "(BG)  Tour de Ramazith, L1 (N)"},~
	REPLACE_TEXTUALLY ~{"BG0138", "N Baldur's Gate: Ramazith's Tower L6"},~                                     ~{"BG0138", "(BG)  Tour de Ramazith, L6 (N)"},~
	REPLACE_TEXTUALLY ~{"BG0139", "N Baldur's Gate: Ramazith's Tower L2"},~                                     ~{"BG0139", "(BG)  Tour de Ramazith, L2 (N)"},~
	REPLACE_TEXTUALLY ~{"BG0140", "N Baldur's Gate: Ramazith's Tower L3"},~                                     ~{"BG0140", "(BG)  Tour de Ramazith, L3 (N)"},~
	REPLACE_TEXTUALLY ~{"BG0141", "N Baldur's Gate: Ramazith's Tower L4"},~                                     ~{"BG0141", "(BG)  Tour de Ramazith, L4 (N)"},~
	REPLACE_TEXTUALLY ~{"BG0142", "N Baldur's Gate: Ramazith's Tower L5"},~                                     ~{"BG0142", "(BG)  Tour de Ramazith, L5 (N)"},~
	REPLACE_TEXTUALLY ~{"BG0143", "Central Baldur's Gate: Oberon's Estate L1"},~                                ~{"BG0143", "(BG)  Domaine Oberon, L1 (C)"},~
	REPLACE_TEXTUALLY ~{"BG0144", "Central Baldur's Gate: Oberon's Estate L2"},~                                ~{"BG0144", "(BG)  Domaine Oberon, L2 (C)"},~
	REPLACE_TEXTUALLY ~{"BG0145", "Central Baldur's Gate: Oberon's Estate L3"},~                                ~{"BG0145", "(BG)  Domaine Oberon, L3 (C)"},~
	REPLACE_TEXTUALLY ~{"BG0146", "Thieves' Maze"},~                                                            ~{"BG0146", "(BG)  Labyrinthe de la Guilde des voleurs, (E)"},~
	REPLACE_TEXTUALLY ~{"BG0148", "E Baldur's Gate: House5"},~                                                  ~{"BG0148", "(BG)  Vers la guilde des Voleurs, Entree 5 (E)"},~
	REPLACE_TEXTUALLY ~{"BG0149", "NE Baldur's Gate: Ilmater's Shrine"},~                                       ~{"BG0149", "(BG)  Chapelle d'Ilmater (NE)"},~
	REPLACE_TEXTUALLY ~{"BG0150", "E Baldur's Gate: House2"},~                                                  ~{"BG0150", "(BG)  Vers la guilde des Voleurs, Entree 2 (E)"},~
	REPLACE_TEXTUALLY ~{"BG0151", "E Baldur's Gate: House3"},~                                                  ~{"BG0151", "(BG)  Vers la guilde des Voleurs, Entree 3 (E)"},~
	REPLACE_TEXTUALLY ~{"BG0152", "E Baldur's Gate: House4"},~                                                  ~{"BG0152", "(BG)  Vers la guilde des Voleurs, Entree 4 (E)"},~
	REPLACE_TEXTUALLY ~{"BG0153", "E Baldur's Gate: Thieves' Guild"},~                                          ~{"BG0153", "(BG)  Guilde des voleurs de l'Ombre, (E)"},~
	REPLACE_TEXTUALLY ~{"BG0154", "E Baldur's Gate: Keexie Tavern L1"},~                                        ~{"BG0154", "(BG)  Taverne de Keexie, L1 (E)"},~
	REPLACE_TEXTUALLY ~{"BG0155", "NW Baldur's Gate: House3 L1"},~                                              ~{"BG0155", "(BG)  Maison 3, L1 (NO)"},~
	REPLACE_TEXTUALLY ~{"BG0156", "NW Baldur's Gate: House3 L2"},~                                              ~{"BG0156", "(BG)  Maison 3, L2 (NO)"},~
	REPLACE_TEXTUALLY ~{"BG0157", "NW Baldur's Gate: Quinn's House L1"},~                                       ~{"BG0157", "(BG)  Maison de Quinn, L1 (NO)"},~
	REPLACE_TEXTUALLY ~{"BG0158", "NW Baldur's Gate: Quinn's House L2"},~                                       ~{"BG0158", "(BG)  Maison de Quinn,  L2 (NO)"},~
	REPLACE_TEXTUALLY ~{"BG0159", "NW Baldur's Gate: House1 L1"},~                                              ~{"BG0159", "(BG)  Maison 1, L1 (NO)"},~
	REPLACE_TEXTUALLY ~{"BG0160", "NW Baldur's Gate: House1 L2"},~                                              ~{"BG0160", "(BG)  Maison 1, L2 (NO)"},~
	REPLACE_TEXTUALLY ~{"BG0161", "NW Baldur's Gate: Degrodel's House"},~                                       ~{"BG0161", "(BG)  Manoir de Degrodel (NO)"},~
	REPLACE_TEXTUALLY ~{"BG0162", "NW Baldur's Gate: Laerta's House L1"},~                                      ~{"BG0162", "(BG)  Manoir des jumelles,( Louise et Laerta) L1 (NO)"},~
	REPLACE_TEXTUALLY ~{"BG0163", "NW Baldur's Gate: House2 L1"},~                                              ~{"BG0163", "(BG)  Maison 2, L1 (NO)"},~
	REPLACE_TEXTUALLY ~{"BG0164", "NW Baldur's Gate: House2 L2"},~                                              ~{"BG0164", "(BG)  Maison 2, L2 (NO)"},~
	REPLACE_TEXTUALLY ~{"BG0165", "NW Baldur's Gate: Tavern L1"},~                                              ~{"BG0165", "(BG)  Auberge, L1 (NO)"},~
	REPLACE_TEXTUALLY ~{"BG0166", "NW Baldur's Gate: Tavern L2"},~                                              ~{"BG0166", "(BG)  Auberge, L2 (NO)"},~
	REPLACE_TEXTUALLY ~{"BG0167", "NW Baldur's Gate: Pheirkas' House L1"},~                                     ~{"BG0167", "(BG)  Maison de Pheirkas, L1 (NO)"},~
	REPLACE_TEXTUALLY ~{"BG0168", "NW Baldur's Gate: Pheirkas' House L2"},~                                     ~{"BG0168", "(BG)  Maison de Pheirkas, L2 (NO)"},~
	REPLACE_TEXTUALLY ~{"BG0169", "NW Baldur's Gate: House4 L1"},~                                              ~{"BG0169", "(BG)  Maison 4, L1 (NO)"},~
	REPLACE_TEXTUALLY ~{"BG0170", "NW Baldur's Gate: House4 L2"},~                                              ~{"BG0170", "(BG)  Maison 4, L2 (NO)"},~
	REPLACE_TEXTUALLY ~{"BG0171", "E Baldur's Gate: Keexie Tavern L2"},~                                        ~{"BG0171", "(BG)  Taverne de Keexie, L2 (E)"},~
	REPLACE_TEXTUALLY ~{"BG0200", "N Baldur's Gate"},~                                                          ~{"BG0200", "  La Porte de Baldur, NORD"},~
	REPLACE_TEXTUALLY ~{"BG0224", "W Sewers"},~                                                                 ~{"BG0224", "(BG)  Égouts, Ouest (O)"},~
	REPLACE_TEXTUALLY ~{"BG0225", "Central Sewers"},~                                                           ~{"BG0225", "(BG)  Égouts, Central (C)"},~
	REPLACE_TEXTUALLY ~{"BG0226", "E Sewers"},~                                                                 ~{"BG0226", "(BG)  Égouts, Est (E)"},~
	REPLACE_TEXTUALLY ~{"BG0300", "NE Baldur's Gate"},~                                                         ~{"BG0300", "  La Porte de Baldur, NORD-EST"},~
	REPLACE_TEXTUALLY ~{"BG0302", "NE Baldur's Gate: House2 L1"},~                                              ~{"BG0302", "(BG)  Maison 2, L1 (NE)"},~
	REPLACE_TEXTUALLY ~{"BG0303", "NE Baldur's Gate: House2 L2"},~                                              ~{"BG0303", "(BG)  Maison 2, L2 (NE)"},~
	REPLACE_TEXTUALLY ~{"BG0304", "NE Baldur's Gate: Store"},~                                                  ~{"BG0304", "(BG)  Bazar (NE)"},~
	REPLACE_TEXTUALLY ~{"BG0305", "NE Baldur's Gate: House1 L1"},~                                              ~{"BG0305", "(BG)  Maison 1, L1 (NE)"},~
	REPLACE_TEXTUALLY ~{"BG0306", "NE Baldur's Gate: House1 L2"},~                                              ~{"BG0306", "(BG)  Maison 1, L2 (NE)"},~
	REPLACE_TEXTUALLY ~{"BG0307", "NE Baldur's Gate: Counting House L1"},~                                      ~{"BG0307", "(BG)  Ligue des marchands, L1 (NE)"},~
	REPLACE_TEXTUALLY ~{"BG0308", "NE Baldur's Gate: Counting House L2"},~                                      ~{"BG0308", "(BG)  Ligue des marchands, L2 (NE)"},~
	REPLACE_TEXTUALLY ~{"BG0400", "Upper Chionthar"},~                                                          ~{"BG0400", "(SC)  En amont de la Chionthar"},~
	REPLACE_TEXTUALLY ~{"BG0401", "Upper Chionthar: Farmhouse"},~                                               ~{"BG0401", "(SC)  Fermes sur la Chionthar, (Ajantis)"},~
	REPLACE_TEXTUALLY ~{"BG0500", "Durlag's Tower"},~                                                           ~{"BG0500", "(ToSC)  Tour de Durlag"},~
	REPLACE_TEXTUALLY ~{"BG0501", "Durlag's Tower: Cellar"},~                                                   ~{"BG0501", "(ToSC)  Tour de Durlag, Sous-sol"},~
	REPLACE_TEXTUALLY ~{"BG0502", "Durlag's Tower: L1"},~                                                       ~{"BG0502", "(ToSC)  Tour de Durlag, L1"},~
	REPLACE_TEXTUALLY ~{"BG0503", "Durlag's Tower: L2"},~                                                       ~{"BG0503", "(ToSC)  Tour de Durlag, L2"},~
	REPLACE_TEXTUALLY ~{"BG0504", "Durlag's Tower: L3"},~                                                       ~{"BG0504", "(ToSC)  Tour de Durlag, L3"},~
	REPLACE_TEXTUALLY ~{"BG0505", "Durlag's Tower: L4"},~                                                       ~{"BG0505", "(ToSC)  Tour de Durlag, L4"},~
	REPLACE_TEXTUALLY ~{"BG0506", "Durlag's Tower: Chessboard"},~                                               ~{"BG0506", "(ToSC)  Tour de Durlag, Échiquier"},~
	REPLACE_TEXTUALLY ~{"BG0507", "Durlag's Tower: Ice Chamber"},~                                              ~{"BG0507", "(ToSC)  Tour de Durlag, Défi glace"},~
	REPLACE_TEXTUALLY ~{"BG0508", "Durlag's Tower: Fire Chamber"},~                                             ~{"BG0508", "(ToSC)  Tour de Durlag, Défi feu"},~
	REPLACE_TEXTUALLY ~{"BG0509", "Durlag's Tower: Air Chamber"},~                                              ~{"BG0509", "(ToSC)  Tour de Durlag, Défi air"},~
	REPLACE_TEXTUALLY ~{"BG0510", "Durlag's Tower: Earth Chamber"},~                                            ~{"BG0510", "(ToSC)  Tour de Durlag, Défi terre"},~
	REPLACE_TEXTUALLY ~{"BG0511", "Durlag's Tower: D1"},~                                                       ~{"BG0511", "(ToSC)  Tour de Durlag, D1"},~
	REPLACE_TEXTUALLY ~{"BG0512", "Durlag's Tower: D2"},~                                                       ~{"BG0512", "(ToSC)  Tour de Durlag, D2"},~
	REPLACE_TEXTUALLY ~{"BG0513", "Durlag's Tower: D3"},~                                                       ~{"BG0513", "(ToSC)  Tour de Durlag, D3"},~
	REPLACE_TEXTUALLY ~{"BG0514", "Durlag's Tower: D4"},~                                                       ~{"BG0514", "(ToSC)  Tour de Durlag, D4"},~
	REPLACE_TEXTUALLY ~{"BG0515", "Durlag's Tower: Compass Room"},~                                             ~{"BG0515", "(ToSC)  Tour de Durlag, Golem de pierre"},~
	REPLACE_TEXTUALLY ~{"BG0516", "Durlag's Tower: Demonknight's Chamber"},~                                    ~{"BG0516", "(ToSC)  Tour de Durlag, Chevalier demon"},~
	REPLACE_TEXTUALLY ~{"BG0600", "W Baldur's Gate"},~                                                          ~{"BG0600", "  La Porte de Baldur, OUEST"},~
	REPLACE_TEXTUALLY ~{"BG0601", "SW Baldur's Gate: Seven Suns L1"},~                                          ~{"BG0601", "(BG)  Les Sept Soleils, L1 (SO)"},~
	REPLACE_TEXTUALLY ~{"BG0602", "SW Baldur's Gate: Seven Suns L2"},~                                          ~{"BG0602", "(BG)  Les Sept Soleils, L2 (SO)"},~
	REPLACE_TEXTUALLY ~{"BG0603", "SW Baldur's Gate: Seven Suns Cellar"},~                                      ~{"BG0603", "(BG)  Les Sept Soleils, Sous-sol (SO)"},~
	REPLACE_TEXTUALLY ~{"BG0606", "SW Baldur's Gate: Flaming Fist HQ Cellar"},~                                 ~{"BG0606", "(BG)  Siege du Poing Enflamme, Sous-sol (SO)"},~
	REPLACE_TEXTUALLY ~{"BG0607", "SW Baldur's Gate: Flaming Fist HQ L1"},~                                     ~{"BG0607", "(BG)  Siege du Poing Enflamme, L1 (SO)"},~
	REPLACE_TEXTUALLY ~{"BG0608", "SW Baldur's Gate: Flaming Fist HQ L2"},~                                     ~{"BG0608", "(BG)  Siege du Poing Enflamme, L2 (SO)"},~
	REPLACE_TEXTUALLY ~{"BG0609", "Baldur's Gate Docks: Water-Queen's House"},~                                 ~{"BG0609", "(BG)  Temple d'Umberlee, (Quais) (S)"},~
	REPLACE_TEXTUALLY ~{"BG0611", "Baldur's Gate Docks: Iron Throne Cellar"},~                                  ~{"BG0611", "(BG)  Trône de Fer, Sous-sol (S)"},~
	REPLACE_TEXTUALLY ~{"BG0612", "Baldur's Gate Docks: Iron Throne L2"},~                                      ~{"BG0612", "(BG)  Trône de Fer, L2 (S)"},~
	REPLACE_TEXTUALLY ~{"BG0613", "Baldur's Gate Docks: Iron Throne L3"},~                                      ~{"BG0613", "(BG)  Trône de Fer, L3 (S)"},~
	REPLACE_TEXTUALLY ~{"BG0614", "Baldur's Gate Docks: Iron Throne L4"},~                                      ~{"BG0614", "(BG)  Trône de Fer, L4 (S)"},~
	REPLACE_TEXTUALLY ~{"BG0615", "Baldur's Gate Docks: Iron Throne L5"},~                                      ~{"BG0615", "(BG)  Trône de Fer, L5 (S)"},~
	REPLACE_TEXTUALLY ~{"BG0616", "Baldur's Gate Docks: Iron Throne L1"},~                                      ~{"BG0616", "(BG)  Trône de Fer, L1 (S)"},~
	REPLACE_TEXTUALLY ~{"BG0617", "W Baldur's Gate: Tremain's House L1"},~                                      ~{"BG0617", "(BG)  Maison de Tremain Belde'ar, L1 (O)"},~
	REPLACE_TEXTUALLY ~{"BG0618", "W Baldur's Gate: Tremain's House L2"},~                                      ~{"BG0618", "(BG)  Maison de Tremain Belde'ar, L2 (O)"},~
	REPLACE_TEXTUALLY ~{"BG0619", "W Baldur's Gate: Fenten's House L1"},~                                       ~{"BG0619", "(BG)  Maison de Fenten, L1 (O)"},~
	REPLACE_TEXTUALLY ~{"BG0620", "W Baldur's Gate: Fenten's House L2"},~                                       ~{"BG0620", "(BG)  Maison de Fenten, L2 (O)"},~
	REPLACE_TEXTUALLY ~{"BG0621", "Baldur's Gate Docks: Iron Throne Roof"},~                                    ~{"BG0621", "(BG)  Trône de Fer, Toit (S)"},~
	REPLACE_TEXTUALLY ~{"BG0700", "Central Baldur's Gate"},~                                                    ~{"BG0700", "  La Porte de Baldur, CENTRE DE LA VILLE"},~
	REPLACE_TEXTUALLY ~{"BG0702", "Baldur's Gate Docks: Harbormaster"},~                                        ~{"BG0702", "(BG)  Bâtisse du Maître du Port, (Quais) (S)"},~
	REPLACE_TEXTUALLY ~{"BG0703", "E Baldur's Gate: Sorcerous Sundries L1"},~                                   ~{"BG0703", "(BG)  Bazar Magique, L1 (E)"},~
	REPLACE_TEXTUALLY ~{"BG0704", "E Baldur's Gate: Sorcerous Sundries L2"},~                                   ~{"BG0704", "(BG)  Bazar Magique, L2 (E)"},~
	REPLACE_TEXTUALLY ~{"BG0705", "E Baldur's Gate: Elfsong Tavern L1"},~                                       ~{"BG0705", "(BG)  Taverne du Chant de l'elfe, L1 (E)"},~
	REPLACE_TEXTUALLY ~{"BG0706", "E Baldur's Gate: Elfsong Tavern L2"},~                                       ~{"BG0706", "(BG)  Taverne du Chant de l'elfe, L2 (E)"},~
	REPLACE_TEXTUALLY ~{"BG0707", "Central Baldur's Gate: House3 L1"},~                                         ~{"BG0707", "(BG)  Maison 3, L1 (C)"},~
	REPLACE_TEXTUALLY ~{"BG0708", "Central Baldur's Gate: House3 L2"},~                                         ~{"BG0708", "(BG)  Maison 3, L2 (C)"},~
	REPLACE_TEXTUALLY ~{"BG0709", "Central Baldur's Gate: House2 L1"},~                                         ~{"BG0709", "(BG)  Maison 2, L1 (C)"},~
	REPLACE_TEXTUALLY ~{"BG0710", "Central Baldur's Gate: House2 L2"},~                                         ~{"BG0710", "(BG)  Maison 2, L2 (C)"},~
	REPLACE_TEXTUALLY ~{"BG0711", "Central Baldur's Gate: House1 L1"},~                                         ~{"BG0711", "(BG)  Maison 1, L1 (C)"},~
	REPLACE_TEXTUALLY ~{"BG0712", "Central Baldur's Gate: House1 L2"},~                                         ~{"BG0712", "(BG)  Maison 1, L2 (C)"},~
	REPLACE_TEXTUALLY ~{"BG0713", "Central Baldur's Gate: House5 L1"},~                                         ~{"BG0713", "(BG)  Maison 5, L1 (C)"},~
	REPLACE_TEXTUALLY ~{"BG0714", "Central Baldur's Gate: House5 L2"},~                                         ~{"BG0714", "(BG)  Maison 5, L2 (C)"},~
	REPLACE_TEXTUALLY ~{"BG0715", "Central Baldur's Gate: Nadine's House L1"},~                                 ~{"BG0715", "(BG)  Maison de Nadine, L1 (C)"},~
	REPLACE_TEXTUALLY ~{"BG0716", "Central Baldur's Gate: Nadine's House L2"},~                                 ~{"BG0716", "(BG)  Maison de Nadine, L2 (C)"},~
	REPLACE_TEXTUALLY ~{"BG0717", "Central Baldur's Gate: House6 L1"},~                                         ~{"BG0717", "(BG)  Maison 6, L1 (C)"},~
	REPLACE_TEXTUALLY ~{"BG0718", "Central Baldur's Gate: House6 L2"},~                                         ~{"BG0718", "(BG)  Maison 6, L2 (C)"},~
	REPLACE_TEXTUALLY ~{"BG0719", "Central Baldur's Gate: Felonius' Manor"},~                                   ~{"BG0719", "(BG)  Manoir de Felonius Gist, (C)"},~
	REPLACE_TEXTUALLY ~{"BG0720", "Central Baldur's Gate: Drakon Tavern"},~                                     ~{"BG0720", "(BG)  Taverne de Drakon, (C)"},~
	REPLACE_TEXTUALLY ~{"BG0721", "Central Baldur's Gate: Poultry Store"},~                                     ~{"BG0721", "(BG)  Magasin de volailles, (Poulets enragés) (C)"},~
	REPLACE_TEXTUALLY ~{"BG0722", "Central Baldur's Gate: House4 L1"},~                                         ~{"BG0722", "(BG)  Maison 4, L1 (C)"},~
	REPLACE_TEXTUALLY ~{"BG0723", "Central Baldur's Gate: House4 L2"},~                                         ~{"BG0723", "(BG)  Maison 4, L2 (C)"},~
	REPLACE_TEXTUALLY ~{"BG0724", "Central Baldur's Gate: Gambling Tent 1"},~                                   ~{"BG0724", "(BG)  Tente de jeux 1, (C)"},~
	REPLACE_TEXTUALLY ~{"BG0725", "Central Baldur's Gate: Gambling Tent 2"},~                                   ~{"BG0725", "(BG)  Tente de jeux 2, (C)"},~
	REPLACE_TEXTUALLY ~{"BG0726", "Central Baldur's Gate: Diviner's Tent"},~                                    ~{"BG0726", "(BG)  Tente du devin, (C)"},~
	REPLACE_TEXTUALLY ~{"BG0800", "E Baldur's Gate"},~                                                          ~{"BG0800", "  La Porte de Baldur, EST"},~
	REPLACE_TEXTUALLY ~{"BG0801", "E Baldur's Gate: House6 L1"},~                                               ~{"BG0801", "(BG)  Maison 6, L1 (E)"},~
	REPLACE_TEXTUALLY ~{"BG0802", "E Baldur's Gate: House6 L2"},~                                               ~{"BG0802", "(BG)  Maison 6, L2 (E)"},~
	REPLACE_TEXTUALLY ~{"BG0803", "E Baldur's Gate: Maltz' Weapon Shop L1"},~                                   ~{"BG0803", "(BG)  Magasin d'armes de Maltz, L1 (E)"},~
	REPLACE_TEXTUALLY ~{"BG0804", "E Baldur's Gate: Maltz' Weapon Shop L2"},~                                   ~{"BG0804", "(BG)  Magasin d'armes de Maltz, L2 (E)"},~
	REPLACE_TEXTUALLY ~{"BG0805", "E Baldur's Gate: Arkion's House L1"},~                                       ~{"BG0805", "(BG)  Maison d'Arkion, L1 (E)"},~
	REPLACE_TEXTUALLY ~{"BG0806", "E Baldur's Gate: Arkion's House L2"},~                                       ~{"BG0806", "(BG)  Maison d'Arkion, L2 (E)"},~
	REPLACE_TEXTUALLY ~{"BG0807", "E Baldur's Gate: Inn L1"},~                                                  ~{"BG0807", "(BG)  Auberge, L1 (E)"},~
	REPLACE_TEXTUALLY ~{"BG0808", "E Baldur's Gate: Inn L2"},~                                                  ~{"BG0808", "(BG)  Auberge, L2 (E)"},~
	REPLACE_TEXTUALLY ~{"BG0809", "E Baldur's Gate: Silence's Shop"},~                                          ~{"BG0809", "(BG)  Magasin du Silence, (E)"},~
	REPLACE_TEXTUALLY ~{"BG0810", "E Baldur's Gate: Lucky Aello's"},~                                           ~{"BG0810", "(BG)  Magasin d'Aello la Chance, (E)"},~
	REPLACE_TEXTUALLY ~{"BG0811", "E Baldur's Gate: House1 L1"},~                                               ~{"BG0811", "(BG)  Maison 1, L1 (E)"},~
	REPLACE_TEXTUALLY ~{"BG0812", "E Baldur's Gate: House1 L2"},~                                               ~{"BG0812", "(BG)  Maison 1, L2 (E)"},~
	REPLACE_TEXTUALLY ~{"BG0813", "SE Baldur's Gate: Nemphre's House L1"},~                                     ~{"BG0813", "(BG)  Maison de Nemphre, L1 (SE)"},~
	REPLACE_TEXTUALLY ~{"BG0814", "SE Baldur's Gate: Nemphre's House L2"},~                                     ~{"BG0814", "(BG)  Maison de Nemphre, L2 (SE)"},~
	REPLACE_TEXTUALLY ~{"BG0900", "Wyrm's Crossing"},~                                                          ~{"BG0900", "(SC)  Travers du Ver, (Quayle)"},~
	REPLACE_TEXTUALLY ~{"BG0901", "Wyrm's Crossing: Tenya's House"},~                                           ~{"BG0901", "(SC)  Maison de Tenya, (Travers du Ver)"},~
	REPLACE_TEXTUALLY ~{"BG1000", "Ulgoth's Beard"},~                                                           ~{"BG1000", "  BARBE D'ULGOTH"},~
	REPLACE_TEXTUALLY ~{"BG1001", "Ulgoth's Beard: Inn"},~                                                      ~{"BG1001", "(ToSC)  Auberge de la Barbe d'Ulgoth"},~
	REPLACE_TEXTUALLY ~{"BG1002", "Ulgoth's Beard: Demon's Chamber"},~                                          ~{"BG1002", "(ToSC)  Aec'Letec le demon, D1 (Barbe d'Ulgoth)"},~
	REPLACE_TEXTUALLY ~{"BG1003", "Ulgoth's Beard: Storehouse"},~                                               ~{"BG1003", "(ToSC)  Culte d'Aec'Letec, L1 (Barbe d'Ulgoth)"},~
	REPLACE_TEXTUALLY ~{"BG1004", "Ulgoth's Beard: Mendas' House"},~                                            ~{"BG1004", "(ToSC)  Maison de Mendas, (Barbe d'Ulgoth)"},~
	REPLACE_TEXTUALLY ~{"BG1005", "Ulgoth's Beard: Therella's House"},~                                         ~{"BG1005", "(ToSC)  Maison de Therella, (Barbe d'Ulgoth)"},~
	REPLACE_TEXTUALLY ~{"BG1006", "Ulgoth's Beard: House2"},~                                                   ~{"BG1006", "(ToSC)  Maison 2, (Barbe d'Ulgoth"},~
	REPLACE_TEXTUALLY ~{"BG1007", "Ulgoth's Beard: House1"},~                                                   ~{"BG1007", "(ToSC)  Maison 1, (Barbe d'Ulgoth"},~
	REPLACE_TEXTUALLY ~{"BG1008", "Ice Island"},~                                                               ~{"BG1008", "(ToSC)  Île des glaces"},~
	REPLACE_TEXTUALLY ~{"BG1009", "Ice Island: Maze L1"},~                                                      ~{"BG1009", "(ToSC)  Île des glaces, Labyrinthe L1"},~
	REPLACE_TEXTUALLY ~{"BG1010", "Ice Island: Maze L2"},~                                                      ~{"BG1010", "(ToSC)  Île des glaces, Labyrinthe L2"},~
	REPLACE_TEXTUALLY ~{"BG1100", "SW Baldur's Gate"},~                                                         ~{"BG1100", "  La Porte de Baldur, SUD-OUEST, (Tiax)"},~
	REPLACE_TEXTUALLY ~{"BG1101", "SW Baldur's Gate: Wiven's House L1"},~                                       ~{"BG1101", "(BG)  Maison de Wiven, L1 (SO)"},~
	REPLACE_TEXTUALLY ~{"BG1102", "SW Baldur's Gate: Wiven's House L2"},~                                       ~{"BG1102", "(BG)  Maison de Wiven, L2 (SO)"},~
	REPLACE_TEXTUALLY ~{"BG1103", "SW Baldur's Gate: House3 L1"},~                                              ~{"BG1103", "(BG)  Maison 3, L1 (SO)"},~
	REPLACE_TEXTUALLY ~{"BG1104", "SW Baldur's Gate: House3 L2"},~                                              ~{"BG1104", "(BG)  Maison 3, L2 (SO)"},~
	REPLACE_TEXTUALLY ~{"BG1105", "SW Baldur's Gate: House1 L1"},~                                              ~{"BG1105", "(BG)  Maison 1, L1 (SO)"},~
	REPLACE_TEXTUALLY ~{"BG1106", "SW Baldur's Gate: House1 L2"},~                                              ~{"BG1106", "(BG)  Maison 1, L2 (SO)"},~
	REPLACE_TEXTUALLY ~{"BG1107", "SW Baldur's Gate: House2 L1"},~                                              ~{"BG1107", "(BG)  Maison 2, L1 (SO)"},~
	REPLACE_TEXTUALLY ~{"BG1108", "SW Baldur's Gate: House2 L2"},~                                              ~{"BG1108", "(BG)  Maison 2, L2 (SO)"},~
	REPLACE_TEXTUALLY ~{"BG1109", "SW Baldur's Gate: Tavern L1"},~                                              ~{"BG1109", "(BG)  Taverne, L1 (SO)"},~
	REPLACE_TEXTUALLY ~{"BG1110", "SW Baldur's Gate: Tavern L2"},~                                              ~{"BG1110", "(BG)  Taverne, L2 (SO)"},~
	REPLACE_TEXTUALLY ~{"BG1111", "SW Baldur's Gate: Sunin's House"},~                                          ~{"BG1111", "(BG)  Maison de Sunin, (SO)"},~
	REPLACE_TEXTUALLY ~{"BG1112", "SW Baldur's Gate: Weapons Store 1"},~                                        ~{"BG1112", "(BG)  Magasin d'armes 1, (SO)"},~
	REPLACE_TEXTUALLY ~{"BG1113", "SW Baldur's Gate: Ye Olde Inn L1"},~                                         ~{"BG1113", "(BG)  La vieille auberge, L1 (SO)"},~
	REPLACE_TEXTUALLY ~{"BG1114", "SW Baldur's Gate: Ye Olde Inn L2"},~                                         ~{"BG1114", "(BG)  La vieille auberge, L2 (SO)"},~
	REPLACE_TEXTUALLY ~{"BG1115", "SW Baldur's Gate: Potions Store 2"},~                                        ~{"BG1115", "(BG)  Magasin de potions 2, (SO)"},~
	REPLACE_TEXTUALLY ~{"BG1116", "SW Baldur's Gate: Weapons Store 2"},~                                        ~{"BG1116", "(BG)  Magasin d'armes 2, (SO)"},~
	REPLACE_TEXTUALLY ~{"BG1117", "SW Baldur's Gate: Potions Store 1"},~                                        ~{"BG1117", "(BG)  Magasin de potions 1, (SO)"},~
	REPLACE_TEXTUALLY ~{"BG1200", "Baldur's Gate Docks"},~                                                      ~{"BG1200", "  Les quais de la Porte de Baldur, SUD"},~
	REPLACE_TEXTUALLY ~{"BG1201", "Baldur's Gate Docks: Ogre Magi House L1"},~                                  ~{"BG1201", "(BG)  Manoir des ogres-mages, L1 (S)"},~
	REPLACE_TEXTUALLY ~{"BG1202", "Baldur's Gate Docks: Ogre Magi House L2"},~                                  ~{"BG1202", "(BG)  Manoir des ogres-mages, L2 (S)"},~
	REPLACE_TEXTUALLY ~{"BG1203", "Baldur's Gate Docks: House2 L1"},~                                           ~{"BG1203", "(BG)  Maison 2, L1 (S)"},~
	REPLACE_TEXTUALLY ~{"BG1204", "Baldur's Gate Docks: House2 L2"},~                                           ~{"BG1204", "(BG)  Maison 2, L2 (S)"},~
	REPLACE_TEXTUALLY ~{"BG1205", "Baldur's Gate Docks: House1 L1"},~                                           ~{"BG1205", "(BG)  Maison 1, L1 (S)"},~
	REPLACE_TEXTUALLY ~{"BG1206", "Baldur's Gate Docks: House1 L2"},~                                           ~{"BG1206", "(BG)  Maison 1, L2 (S)"},~
	REPLACE_TEXTUALLY ~{"BG1207", "Baldur's Gate Docks: Basilisk Warehouse"},~                                  ~{"BG1207", "(BG)  Entrepôt, (Basilic) (S)"},~
	REPLACE_TEXTUALLY ~{"BG1208", "Baldur's Gate Docks: Noralee's Warehouse"},~                                 ~{"BG1208", "(BG)  Entrepôt de Noralee, (Quais) (S)"},~
	REPLACE_TEXTUALLY ~{"BG1209", "Baldur's Gate Docks: Larriaz' House L1"},~                                   ~{"BG1209", "(BG)  Maison de Larriaz, L1 (S)"},~
	REPLACE_TEXTUALLY ~{"BG1210", "Baldur's Gate Docks: Larriaz' House L2"},~                                   ~{"BG1210", "(BG)  Maison de Larriaz, L2 (S)"},~
	REPLACE_TEXTUALLY ~{"BG1211", "Baldur's Gate Docks: Ghorak's House L1"},~                                   ~{"BG1211", "(BG)  Maison de Ghorak, L1 (S)"},~
	REPLACE_TEXTUALLY ~{"BG1212", "Baldur's Gate Docks: Ghorak's House L2"},~                                   ~{"BG1212", "(BG)  Maison de Ghorak, L2 (S)"},~
	REPLACE_TEXTUALLY ~{"BG1213", "Baldur's Gate Docks: Cordyr's House L1"},~                                   ~{"BG1213", "(BG)  Maison de Cordyr, L1 (S)"},~
	REPLACE_TEXTUALLY ~{"BG1214", "Baldur's Gate Docks: Cordyr's House L2"},~                                   ~{"BG1214", "(BG)  Maison de Cordyr, L2 (S)"},~
	REPLACE_TEXTUALLY ~{"BG1215", "Baldur's Gate Docks: Jopalin's Tavern"},~                                    ~{"BG1215", "(BG)  Taverne de Jopalin, (Quais) (S)"},~
	REPLACE_TEXTUALLY ~{"BG1300", "SE Baldur's Gate"},~                                                         ~{"BG1300", "  La Porte de Baldur, SUD-EST"},~
	REPLACE_TEXTUALLY ~{"BG1301", "SE Baldur's Gate: Warehouse"},~                                              ~{"BG1301", "(BG)  Entrepôt, (SE)"},~
	REPLACE_TEXTUALLY ~{"BG1302", "SE Baldur's Gate: General Store 2"},~                                        ~{"BG1302", "(BG)  Magasin d'Al le Bien-Équilibre, (SE)"},~
	REPLACE_TEXTUALLY ~{"BG1303", "SE Baldur's Gate: Nadarin's Warehouse"},~                                    ~{"BG1303", "(BG)  Entrepôt de Nadarin, (SE)"},~
	REPLACE_TEXTUALLY ~{"BG1304", "SE Baldur's Gate: House3 L1"},~                                              ~{"BG1304", "(BG)  Maison 3, L1 (SE)"},~
	REPLACE_TEXTUALLY ~{"BG1305", "SE Baldur's Gate: House3 L2"},~                                              ~{"BG1305", "(BG)  Maison 3, L2 (SE)"},~
	REPLACE_TEXTUALLY ~{"BG1306", "SE Baldur's Gate: Inn L1"},~                                                 ~{"BG1306", "(BG)  Auberge, L1 (SE)"},~
	REPLACE_TEXTUALLY ~{"BG1307", "SE Baldur's Gate: Inn L2"},~                                                 ~{"BG1307", "(BG)  Auberge, L2 (SE)"},~
	REPLACE_TEXTUALLY ~{"BG1308", "SE Baldur's Gate: House4 L1"},~                                              ~{"BG1308", "(BG)  Maison 4, L1 (SE)"},~
	REPLACE_TEXTUALLY ~{"BG1309", "SE Baldur's Gate: House4 L2"},~                                              ~{"BG1309", "(BG)  Maison 4, L2 (SE)"},~
	REPLACE_TEXTUALLY ~{"BG1310", "SE Baldur's Gate: House2 L1"},~                                              ~{"BG1310", "(BG)  Maison 2, L1 (SE)"},~
	REPLACE_TEXTUALLY ~{"BG1311", "SE Baldur's Gate: House2 L2"},~                                              ~{"BG1311", "(BG)  Maison 2, L2 (SE)"},~
	REPLACE_TEXTUALLY ~{"BG1312", "SE Baldur's Gate: Gantolandan's House L1"},~                                 ~{"BG1312", "(BG)  Maison de Gantolandan, L1 (SE)"},~
	REPLACE_TEXTUALLY ~{"BG1313", "SE Baldur's Gate: Gantolandan's House L2"},~                                 ~{"BG1313", "(BG)  Maison de Gantolandan, L2 (SE)"},~
	REPLACE_TEXTUALLY ~{"BG1314", "SE Baldur's Gate: House1 L1"},~                                              ~{"BG1314", "(BG)  Maison 1, L1 (SE)"},~
	REPLACE_TEXTUALLY ~{"BG1315", "SE Baldur's Gate: House1 L2"},~                                              ~{"BG1315", "(BG)  Maison 1, L2 (SE)"},~
	REPLACE_TEXTUALLY ~{"BG1316", "SE Baldur's Gate: Taxek's House L1"},~                                       ~{"BG1316", "(BG)  Cambriolage, L1 (Taxek et Michael) (SE)"},~
	REPLACE_TEXTUALLY ~{"BG1317", "SE Baldur's Gate: Taxek's House L2"},~                                       ~{"BG1317", "(BG)  Cambriolage, L2 (Taxek et Michael) (SE)"},~
	REPLACE_TEXTUALLY ~{"BG1320", "SE Baldur's Gate: General Store 1"},~                                        ~{"BG1320", "(BG)  Magasin 1, Bazar (SE)"},~
	REPLACE_TEXTUALLY ~{"BG1400", "Lower Chionthar"},~                                                          ~{"BG1400", "(SC)  En aval du Chionthar"},~
	REPLACE_TEXTUALLY ~{"BG1401", "Lower Chionthar: Ankheg Pit"},~                                              ~{"BG1401", "(SC)  Fosse des Ankhegs, (Chionthar)"},~
	REPLACE_TEXTUALLY ~{"BG1402", "Lower Chionthar: House1"},~                                                  ~{"BG1402", "(SC)  Maison 1, (Chionthar)"},~
	REPLACE_TEXTUALLY ~{"BG1403", "Lower Chionthar: House2"},~                                                  ~{"BG1403", "(SC)  Maison 2, (Chionthar)"},~
	REPLACE_TEXTUALLY ~{"BG1404", "Lower Chionthar: Farmer Brun's House"},~                                     ~{"BG1404", "(SC)  Maison du fermier Brun, (Chionthar)"},~
	REPLACE_TEXTUALLY ~{"BG1500", "Balduran's Isle (North)"},~                                                  ~{"BG1500", "(ToSC)  Île perdue de Baldurien, Nord"},~
	REPLACE_TEXTUALLY ~{"BG1501", "Balduran's Isle (North): Ship D1"},~                                         ~{"BG1501", "(ToSC)  Épave de Baldurien, D1 (N)"},~
	REPLACE_TEXTUALLY ~{"BG1502", "Balduran's Isle (North): Ship D2"},~                                         ~{"BG1502", "(ToSC)  Épave de Baldurien, D2 (N)"},~
	REPLACE_TEXTUALLY ~{"BG1503", "Balduran's Isle (North): Ship D3"},~                                         ~{"BG1503", "(ToSC)  Épave de Baldurien, D3 (N)"},~
	REPLACE_TEXTUALLY ~{"BG1504", "Balduran's Isle (North): Ship D4"},~                                         ~{"BG1504", "(ToSC)  Épave de Baldurien, D4 (N)"},~
	REPLACE_TEXTUALLY ~{"BG1505", "Balduran's Isle (North): Dradeel's House"},~                                 ~{"BG1505", "(ToSC)  Maison de Dradeel, (Île perdue) (N)"},~
	REPLACE_TEXTUALLY ~{"BG1600", "Cloakwood Grove"},~                                                          ~{"BG1600", "(B-M)  Le Vieux chêne de Bois-Manteau, Faldorn (3)"},~
	REPLACE_TEXTUALLY ~{"BG1601", "Cloakwood Grove: Treehouse L1"},~                                            ~{"BG1601", "(B-M)  Maison du Vieux chêne, L1 (3)"},~
	REPLACE_TEXTUALLY ~{"BG1602", "Cloakwood Grove: Treehouse L2"},~                                            ~{"BG1602", "(B-M)  Maison du Vieux chêne, L2 (3)"},~
	REPLACE_TEXTUALLY ~{"BG1603", "Cloakwood Grove: Peter's Cave"},~                                            ~{"BG1603", "(B-M)  Peter et les Wyvernes, Vieux chêne"},~
	REPLACE_TEXTUALLY ~{"BG1700", "Cloakwood Crossings"},~                                                      ~{"BG1700", "(B-M)  La Caverne de Bois-Manteau, (4)"},~
	REPLACE_TEXTUALLY ~{"BG1800", "Cloakwood Mines"},~                                                          ~{"BG1800", "(B-M)  Les Mines de Bois-Manteau, (5)"},~
	REPLACE_TEXTUALLY ~{"BG1801", "Cloakwood Mines: L1"},~                                                      ~{"BG1801", "(B-M)  Mines de Bois-Manteau, D1"},~
	REPLACE_TEXTUALLY ~{"BG1802", "Cloakwood Mines: L3"},~                                                      ~{"BG1802", "(B-M)  Mines de Bois-Manteau, D3"},~
	REPLACE_TEXTUALLY ~{"BG1803", "Cloakwood Mines: L4"},~                                                      ~{"BG1803", "(B-M)  Mines de Bois-Manteau, D4"},~
	REPLACE_TEXTUALLY ~{"BG1804", "Cloakwood Mines: L2"},~                                                      ~{"BG1804", "(B-M)  Mines de Bois-Manteau, D2 (Yeslick)"},~
	REPLACE_TEXTUALLY ~{"BG1805", "Cloakwood Mines: Barracks L1"},~                                             ~{"BG1805", "(B-M)  Mines de Bois-Manteau, Caserne L1"},~
	REPLACE_TEXTUALLY ~{"BG1806", "Cloakwood Mines: Barracks L2"},~                                             ~{"BG1806", "(B-M)  Mines de Bois-Manteau, Caserne L2"},~
	REPLACE_TEXTUALLY ~{"BG1807", "Cloakwood Mines: Mine Lift"},~                                               ~{"BG1807", "(B-M)  Mines de Bois-Manteau, Monte-charge"},~
	REPLACE_TEXTUALLY ~{"BG1808", "Cloakwood Mines: Storehouse"},~                                              ~{"BG1808", "(B-M)  Mines de Bois-Manteau, Entrepôt"},~
	REPLACE_TEXTUALLY ~{"BG1809", "Cloakwood Mines: Mine Shed"},~                                               ~{"BG1809", "(B-M)  Mines de Bois-Manteau, Entree"},~
	REPLACE_TEXTUALLY ~{"BG1900", "Bandit Camp"},~                                                              ~{"BG1900", "(C-B)  Le Camp des bandits"},~
	REPLACE_TEXTUALLY ~{"BG1901", "Bandit Camp: Raemon's Tent"},~                                               ~{"BG1901", "(C-B)  Tente des chefs des bandits"},~
	REPLACE_TEXTUALLY ~{"BG1902", "Bandit Camp: Tent2"},~                                                       ~{"BG1902", "(C-B)  Tente 2, Ardenor Crush"},~
	REPLACE_TEXTUALLY ~{"BG1903", "Bandit Camp: Gnoll Cave"},~                                                  ~{"BG1903", "(C-B)  Grotte des Gnolls, Garclax"},~
	REPLACE_TEXTUALLY ~{"BG1904", "Bandit Camp: Tersus' Tent"},~                                                ~{"BG1904", "(C-B)  Tente de Tersus"},~
	REPLACE_TEXTUALLY ~{"BG1905", "Bandit Camp: Tent1"},~                                                       ~{"BG1905", "(C-B)  Tente 1, Knott"},~
	REPLACE_TEXTUALLY ~{"BG1906", "Bandit Camp: Tent3"},~                                                       ~{"BG1906", "(C-B)  Tente 3"},~
	REPLACE_TEXTUALLY ~{"BG1907", "Bandit Camp: Tent4"},~                                                       ~{"BG1907", "(C-B)  Tente 4, Taugosz Khosann"},~
	REPLACE_TEXTUALLY ~{"BG2000", "Balduran's Isle (South)"},~                                                  ~{"BG2000", "(ToSC)  Île perdue de Baldurien, Sud"},~
	REPLACE_TEXTUALLY ~{"BG2001", "Balduran's Isle (South): Great Hut"},~                                       ~{"BG2001", "(ToSC)  Grande hutte, Île perdue (S)"},~
	REPLACE_TEXTUALLY ~{"BG2002", "Balduran's Isle (South): Kaishas' Hut"},~                                    ~{"BG2002", "(ToSC)  Hutte de la meneuse, (Kaishas) (S)"},~
	REPLACE_TEXTUALLY ~{"BG2003", "Balduran's Isle (South): Large Hut 3"},~                                     ~{"BG2003", "(ToSC)  Hutte 3, (Île perdue) (S)"},~
	REPLACE_TEXTUALLY ~{"BG2004", "Balduran's Isle (South): Large Hut 2"},~                                     ~{"BG2004", "(ToSC)  Hutte 2, (Île perdue) (S)"},~
	REPLACE_TEXTUALLY ~{"BG2005", "Balduran's Isle (South): Large Hut 4"},~                                     ~{"BG2005", "(ToSC)  Hutte 4, (Île perdue) (S)"},~
	REPLACE_TEXTUALLY ~{"BG2006", "Balduran's Isle (South): Large Hut 1"},~                                     ~{"BG2006", "(ToSC)  Hutte 1, (Île perdue) (S)"},~
	REPLACE_TEXTUALLY ~{"BG2007", "Balduran's Isle (South): Harbor Hut"},~                                      ~{"BG2007", "(ToSC)  Hutte du pêcheur, (Île perdue) (S)"},~
	REPLACE_TEXTUALLY ~{"BG2008", "Balduran's Isle (South): Store Hut 2"},~                                     ~{"BG2008", "(ToSC)  Hutte de commerce 2, (Île perdue) (S)"},~
	REPLACE_TEXTUALLY ~{"BG2009", "Balduran's Isle (South): Store Hut 1"},~                                     ~{"BG2009", "(ToSC)  Hutte de commerce 1, (Île perdue) (S)"},~
	REPLACE_TEXTUALLY ~{"BG2010", "Balduran's Isle (South): Store Hut 4"},~                                     ~{"BG2010", "(ToSC)  Hutte de commerce 4, (Île perdue) (S)"},~
	REPLACE_TEXTUALLY ~{"BG2011", "Balduran's Isle (South): Store Hut 3"},~                                     ~{"BG2011", "(ToSC)  Hutte de commerce 3, (Île perdue) (S)"},~
	REPLACE_TEXTUALLY ~{"BG2012", "Werewolf Caverns"},~                                                         ~{"BG2012", "(ToSC)  Caverne des loups-garous, (S)"},~
	REPLACE_TEXTUALLY ~{"BG2100", "Cloakwood Falls"},~                                                          ~{"BG2100", "(B-M)  Les Falaises de Bois-Manteau, (2)"},~
	REPLACE_TEXTUALLY ~{"BG2101", "Cloakwood Falls: Spider Nest"},~                                             ~{"BG2101", "(B-M)  Nid d'araignée, Centeol (2)"},~
	REPLACE_TEXTUALLY ~{"BG2200", "Cloakwood Lodge"},~                                                          ~{"BG2200", "(B-M)  Le Pavillon de chasse de Bois-Manteau, Coran (1)"},~
	REPLACE_TEXTUALLY ~{"BG2215", "Cloakwood Lodge: Hunting Lodge"},~                                           ~{"BG2215", "(B-M)  Pavillon de chasse, L1 (1)"},~
	REPLACE_TEXTUALLY ~{"BG2300", "Friendly Arm Inn"},~                                                         ~{"BG2300", "(A-B)  Auberge de BRASAMICAL"},~
	REPLACE_TEXTUALLY ~{"BG2301", "Friendly Arm Inn: L1"},~                                                     ~{"BG2301", "(A-B)  Auberge de Brasamical, L1 (Jaheira, Khalid)"},~
	REPLACE_TEXTUALLY ~{"BG2302", "Friendly Arm Inn: L2"},~                                                     ~{"BG2302", "(A-B)  Auberge de Brasamical, L2"},~
	REPLACE_TEXTUALLY ~{"BG2303", "Friendly Arm Inn: L3"},~                                                     ~{"BG2303", "(A-B)  Auberge de Brasamical, L3"},~
	REPLACE_TEXTUALLY ~{"BG2304", "Friendly Arm Inn: Temple of Wisdom"},~                                       ~{"BG2304", "(A-B)  Temple de la sagesse"},~
	REPLACE_TEXTUALLY ~{"BG2305", "Friendly Arm Inn: House"},~                                                  ~{"BG2305", "(A-B)  Maison"},~
	REPLACE_TEXTUALLY ~{"BG2306", "Friendly Arm Inn: Joia's House"},~                                           ~{"BG2306", "(A-B)  Maison de Joia"},~
	REPLACE_TEXTUALLY ~{"BG2400", "Peldvale"},~                                                                 ~{"BG2400", "(SC)  Valpeld, (Viconia)"},~
	REPLACE_TEXTUALLY ~{"BG2600", "Candlekeep"},~                                                               ~{"BG2600", "(C-S)  Château-Suif, Prologue"},~
	REPLACE_TEXTUALLY ~{"BG2602", "Candlekeep: Priest's Quarters"},~                                            ~{"BG2602", "(C-S)  Quartiers du pretre"},~
	REPLACE_TEXTUALLY ~{"BG2605", "Candlekeep: Infirmary"},~                                                    ~{"BG2605", "(C-S)  Infirmerie"},~
	REPLACE_TEXTUALLY ~{"BG2606", "Candlekeep: Storehouse"},~                                                   ~{"BG2606", "(C-S)  Entrepôt"},~
	REPLACE_TEXTUALLY ~{"BG2607", "Candlekeep: Bunkhouse"},~                                                    ~{"BG2607", "(C-S)  Baraquement"},~
	REPLACE_TEXTUALLY ~{"BG2608", "Candlekeep: Library L1"},~                                                   ~{"BG2608", "(C-S)  Château-Suif, Bibliothèque L1"},~
	REPLACE_TEXTUALLY ~{"BG2609", "Candlekeep: Library L2"},~                                                   ~{"BG2609", "(C-S)  Château-Suif, Bibliothèque L2"},~
	REPLACE_TEXTUALLY ~{"BG2610", "Candlekeep: Library L3"},~                                                   ~{"BG2610", "(C-S)  Château-Suif, Bibliothèque L3"},~
	REPLACE_TEXTUALLY ~{"BG2611", "Candlekeep: Library L4"},~                                                   ~{"BG2611", "(C-S)  Château-Suif, Bibliothèque L4"},~
	REPLACE_TEXTUALLY ~{"BG2612", "Candlekeep: Library L5"},~                                                   ~{"BG2612", "(C-S)  Château-Suif, Bibliothèque L5"},~
	REPLACE_TEXTUALLY ~{"BG2613", "Candlekeep: Catacombs L1 Antechamber"},~                                     ~{"BG2613", "(C-S)  Château-Suif, Entree des Catacombes"},~
	REPLACE_TEXTUALLY ~{"BG2614", "Candlekeep: Library L6"},~                                                   ~{"BG2614", "(C-S)  Château-Suif, Bibliothèque L6"},~
	REPLACE_TEXTUALLY ~{"BG2615", "Candlekeep: Catacombs L1"},~                                                 ~{"BG2615", "(C-S)  Château-Suif, Catacombes L1"},~
	REPLACE_TEXTUALLY ~{"BG2616", "Candlekeep: Inn L1"},~                                                       ~{"BG2616", "(C-S)  Auberge de Château-Suif, L1"},~
	REPLACE_TEXTUALLY ~{"BG2617", "Candlekeep: Inn L2"},~                                                       ~{"BG2617", "(C-S)  Auberge de Château-Suif, L2"},~
	REPLACE_TEXTUALLY ~{"BG2618", "Candlekeep: Barracks"},~                                                     ~{"BG2618", "(C-S)  Caserne"},~
	REPLACE_TEXTUALLY ~{"BG2619", "Candlekeep: Catacombs L2"},~                                                 ~{"BG2619", "(C-S)  Château-Suif, Catacombes L2"},~
	REPLACE_TEXTUALLY ~{"BG2626", "Candlekeep: Ch.6"},~                                                         ~{"BG2626", "(C-S)  Chapitre 6, Château-Suif"},~
	REPLACE_TEXTUALLY ~{"BG2627", "Candlekeep: Ch.6 Priest's Quarters"},~                                       ~{"BG2627", "(C-S)  Chapitre 6, Quartiers du prêtre"},~
	REPLACE_TEXTUALLY ~{"BG2628", "Candlekeep: Infirmary"},~                                                    ~{"BG2628", "(C-S)  Chapitre 6, Infirmerie"},~
	REPLACE_TEXTUALLY ~{"BG2629", "Candlekeep: Ch.6 Inn L1"},~                                                  ~{"BG2629", "(C-S)  Chapitre 6, Auberge L1"},~
	REPLACE_TEXTUALLY ~{"BG2630", "Candlekeep: Ch.6 Inn L2"},~                                                  ~{"BG2630", "(C-S)  Chapitre 6, Auberge L2"},~
	REPLACE_TEXTUALLY ~{"BG2631", "Candlekeep: Ch.6 Barracks"},~                                                ~{"BG2631", "(C-S)  Chapitre 6, Caserne"},~
	REPLACE_TEXTUALLY ~{"BG2632", "Candlekeep: Ch.6 Bunkhouse"},~                                               ~{"BG2632", "(C-S)  Chapitre 6, Baraquement"},~
	REPLACE_TEXTUALLY ~{"BG2633", "Candlekeep: Ch.6 Infirmary"},~                                               ~{"BG2633", "(C-S)  Chapitre 6, Infirmerie"},~
	REPLACE_TEXTUALLY ~{"BG2643", "Candlekeep: Obe's Cellar"},~                                                 ~{"BG2643", "(C-S)  Entraînement au combat de groupe d’Obe"},~
	REPLACE_TEXTUALLY ~{"BG2700", "Lion's Way"},~                                                               ~{"BG2700", "(SC)  Voie du Lion, (Imoen, Xzar, Montaron)"},~
	REPLACE_TEXTUALLY ~{"BG2800", "Coast Way"},~                                                                ~{"BG2800", "(SC)  Croisée des chemins"},~
	REPLACE_TEXTUALLY ~{"BG2900", "Larswood"},~                                                                 ~{"BG2900", "(SC)  Bois de Lars"},~
	REPLACE_TEXTUALLY ~{"BG3000", "Spider Wood"},~                                                              ~{"BG3000", "(SC)  Bois des araignées"},~
	REPLACE_TEXTUALLY ~{"BG3100", "Rocky Coast"},~                                                              ~{"BG3100", "(SC)  Cote des épaves"},~
	REPLACE_TEXTUALLY ~{"BG3200", "High Hedge"},~                                                               ~{"BG3200", "(SC)  Haute Haie, (Kivan)"},~
	REPLACE_TEXTUALLY ~{"BG3201", "High Hedge: House"},~                                                        ~{"BG3201", "(SC)  Maison"},~
	REPLACE_TEXTUALLY ~{"BG3202", "High Hedge: Thalanthyr's Abode"},~                                           ~{"BG3202", "(SC)  Demeure de Thalantyr"},~
	REPLACE_TEXTUALLY ~{"BG3300", "Beregost"},~                                                                 ~{"BG3300", "  BÉRÉGOST, (Neera, Garrick, Kagain)"},~
	REPLACE_TEXTUALLY ~{"BG3301", "Beregost: Thunderhammer Smithy"},~                                           ~{"BG3301", "(B)  Forge de Grondemarteau"},~
	REPLACE_TEXTUALLY ~{"BG3302", "Beregost: House19"},~                                                        ~{"BG3302", "(B)  Maison 19"},~
	REPLACE_TEXTUALLY ~{"BG3303", "Beregost: Red Sheaf L2"},~                                                   ~{"BG3303", "(B)  Auberge de la Gerbe Rouge, L2"},~
	REPLACE_TEXTUALLY ~{"BG3304", "Beregost: Jovial Juggler L1"},~                                              ~{"BG3304", "(B)  Jongleur Jovial, L1"},~
	REPLACE_TEXTUALLY ~{"BG3305", "Beregost: Jovial Juggler L2F"},~                                             ~{"BG3305", "(B)  Jongleur Jovial, L2 principale"},~
	REPLACE_TEXTUALLY ~{"BG3306", "Beregost: Jovial Juggler L2R"},~                                             ~{"BG3306", "(B)  Jongleur Jovial, L2 secondaire"},~
	REPLACE_TEXTUALLY ~{"BG3307", "Beregost: Burning Wizard L1"},~                                              ~{"BG3307", "(B)  Magicien Ardent, L1"},~
	REPLACE_TEXTUALLY ~{"BG3308", "Beregost: Burning Wizard L2"},~                                              ~{"BG3308", "(B)  Magicien Ardent, L2"},~
	REPLACE_TEXTUALLY ~{"BG3309", "Beregost: House13 L1"},~                                                     ~{"BG3309", "(B)  Maison 13, L1"},~
	REPLACE_TEXTUALLY ~{"BG3310", "Beregost: House13 L2"},~                                                     ~{"BG3310", "(B)  Maison 13, L2"},~
	REPLACE_TEXTUALLY ~{"BG3311", "Beregost: House12 L1"},~                                                     ~{"BG3311", "(B)  Maison 12, L1"},~
	REPLACE_TEXTUALLY ~{"BG3312", "Beregost: House12 L2"},~                                                     ~{"BG3312", "(B)  Maison 12, L2"},~
	REPLACE_TEXTUALLY ~{"BG3313", "Beregost: Mirianne's House L1"},~                                            ~{"BG3313", "(B)  Maison de Mirianne, L1"},~
	REPLACE_TEXTUALLY ~{"BG3314", "Beregost: Mirianne's House L2"},~                                            ~{"BG3314", "(B)  Maison de Mirianne, L2"},~
	REPLACE_TEXTUALLY ~{"BG3315", "Beregost: Landrin's House"},~                                                ~{"BG3315", "(B)  Maison de Landrin"},~
	REPLACE_TEXTUALLY ~{"BG3316", "Beregost: House18"},~                                                        ~{"BG3316", "(B)  Maison 18"},~
	REPLACE_TEXTUALLY ~{"BG3317", "Beregost: House17"},~                                                        ~{"BG3317", "(B)  Maison de Borland"},~
	REPLACE_TEXTUALLY ~{"BG3318", "Beregost: House15"},~                                                        ~{"BG3318", "(B)  Maison 15"},~
	REPLACE_TEXTUALLY ~{"BG3319", "Beregost: House16"},~                                                        ~{"BG3319", "(B)  Maison 16"},~
	REPLACE_TEXTUALLY ~{"BG3320", "Beregost: Travenhurst Manor L1"},~                                           ~{"BG3320", "(B)  Manoir Travenhurst, L1"},~
	REPLACE_TEXTUALLY ~{"BG3321", "Beregost: Travenhurst Manor L2"},~                                           ~{"BG3321", "(B)  Manoir Travenhurst, L2"},~
	REPLACE_TEXTUALLY ~{"BG3322", "Beregost: Servant's Quarters"},~                                             ~{"BG3322", "(B)  Quartier des serviteurs du Manoir"},~
	REPLACE_TEXTUALLY ~{"BG3323", "Beregost: House20 L1"},~                                                     ~{"BG3323", "(B)  Maison 20, L1"},~
	REPLACE_TEXTUALLY ~{"BG3324", "Beregost: House20 L2"},~                                                     ~{"BG3324", "(B)  Maison 20, L2"},~
	REPLACE_TEXTUALLY ~{"BG3325", "Beregost: House23 L1"},~                                                     ~{"BG3325", "(B)  Maison 23, L1"},~
	REPLACE_TEXTUALLY ~{"BG3326", "Beregost: House23 L2"},~                                                     ~{"BG3326", "(B)  Maison 23, L2"},~
	REPLACE_TEXTUALLY ~{"BG3327", "Beregost: House14 L1"},~                                                     ~{"BG3327", "(B)  Maison 14, L1"},~
	REPLACE_TEXTUALLY ~{"BG3328", "Beregost: House14 L2"},~                                                     ~{"BG3328", "(B)  Maison 14, L2"},~
	REPLACE_TEXTUALLY ~{"BG3329", "Beregost: House21 L1"},~                                                     ~{"BG3329", "(B)  Maison d'Alain, L1"},~
	REPLACE_TEXTUALLY ~{"BG3330", "Beregost: House21 L2"},~                                                     ~{"BG3330", "(B)  Maison d'Alain, L2"},~
	REPLACE_TEXTUALLY ~{"BG3331", "Beregost: House11 L1"},~                                                     ~{"BG3331", "(B)  Maison de Mr. Colquetle, L1"},~
	REPLACE_TEXTUALLY ~{"BG3332", "Beregost: House11 L2"},~                                                     ~{"BG3332", "(B)  Maison de Mr. Colquetle, L2"},~
	REPLACE_TEXTUALLY ~{"BG3333", "Beregost: Firebead's House L1"},~                                            ~{"BG3333", "(B)  Maison de Perleflamme Cheveux d’elfe, L1"},~
	REPLACE_TEXTUALLY ~{"BG3334", "Beregost: Firebead's House L2"},~                                            ~{"BG3334", "(B)  Maison de Perleflamme Cheveux d’elfe, L2"},~
	REPLACE_TEXTUALLY ~{"BG3335", "Beregost: House10 L1"},~                                                     ~{"BG3335", "(B)  Maison 10, L1"},~
	REPLACE_TEXTUALLY ~{"BG3336", "Beregost: House10 L2"},~                                                     ~{"BG3336", "(B)  Maison 10, L2"},~
	REPLACE_TEXTUALLY ~{"BG3337", "Beregost: House22 L1"},~                                                     ~{"BG3337", "(B)  Maison 22, L1"},~
	REPLACE_TEXTUALLY ~{"BG3338", "Beregost: House22 L2"},~                                                     ~{"BG3338", "(B)  Maison 22, L2"},~
	REPLACE_TEXTUALLY ~{"BG3339", "Beregost: House01 L1"},~                                                     ~{"BG3339", "(B)  Maison 01, L1"},~
	REPLACE_TEXTUALLY ~{"BG3340", "Beregost: House01 L2"},~                                                     ~{"BG3340", "(B)  Maison 01, L2"},~
	REPLACE_TEXTUALLY ~{"BG3341", "Beregost: House02 L1"},~                                                     ~{"BG3341", "(B)  Maison 02, L1"},~
	REPLACE_TEXTUALLY ~{"BG3342", "Beregost: House02 L2"},~                                                     ~{"BG3342", "(B)  Maison 02, L2"},~
	REPLACE_TEXTUALLY ~{"BG3343", "Beregost: House03"},~                                                        ~{"BG3343", "(B)  Maison 03"},~
	REPLACE_TEXTUALLY ~{"BG3344", "Beregost: House07"},~                                                        ~{"BG3344", "(B)  Maison 07"},~
	REPLACE_TEXTUALLY ~{"BG3345", "Beregost: House04 L1"},~                                                     ~{"BG3345", "(B)  Maison 04 L1"},~
	REPLACE_TEXTUALLY ~{"BG3346", "Beregost: House04 L2"},~                                                     ~{"BG3346", "(B)  Maison 04 L2"},~
	REPLACE_TEXTUALLY ~{"BG3347", "Beregost: House05 L1"},~                                                     ~{"BG3347", "(B)  Maison des Greycart, L1"},~
	REPLACE_TEXTUALLY ~{"BG3348", "Beregost: House05 L2"},~                                                     ~{"BG3348", "(B)  Maison des Greycart, L2"},~
	REPLACE_TEXTUALLY ~{"BG3349", "Beregost: House06 L1"},~                                                     ~{"BG3349", "(B)  Maison 06, L1"},~
	REPLACE_TEXTUALLY ~{"BG3350", "Beregost: House06 L2"},~                                                     ~{"BG3350", "(B)  Maison 06, L2"},~
	REPLACE_TEXTUALLY ~{"BG3351", "Beregost: Feldepost's Inn L1"},~                                             ~{"BG3351", "(B)  Auberge de Feldpost, L1"},~
	REPLACE_TEXTUALLY ~{"BG3352", "Beregost: Feldepost's Inn L2"},~                                             ~{"BG3352", "(B)  Auberge de Feldpost, L2"},~
	REPLACE_TEXTUALLY ~{"BG3353", "Beregost: Kagain's Store"},~                                                 ~{"BG3353", "(B)  Boutique de Kagain"},~
	REPLACE_TEXTUALLY ~{"BG3354", "Beregost: House09"},~                                                        ~{"BG3354", "(B)  Maison, 09"},~
	REPLACE_TEXTUALLY ~{"BG3355", "Beregost: House08"},~                                                        ~{"BG3355", "(B)  Maison, 08"},~
	REPLACE_TEXTUALLY ~{"BG3356", "Beregost: House08"},~                                                        ~{"BG3356", "(B)  Maison, 08"},~
	REPLACE_TEXTUALLY ~{"BG3357", "Beregost: Red Sheaf L1"},~                                                   ~{"BG3357", "(B)  Auberge de la Gerbe Rouge, L1"},~
	REPLACE_TEXTUALLY ~{"BG3400", "Temple of Lathander"},~                                                      ~{"BG3400", "(B)  Temple de Lathandre"},~
	REPLACE_TEXTUALLY ~{"BG3401", "Temple of Lathander: Vestibule"},~                                           ~{"BG3401", "(B)  Vestibule du Temple de Lathandre"},~
	REPLACE_TEXTUALLY ~{"BG3402", "Temple of Lathander: Song of the Morning"},~                                 ~{"BG3402", "(B)  Temple de Lathandre, Intérieur"},~
	REPLACE_TEXTUALLY ~{"BG3500", "Sharp Teeth Plain"},~                                                        ~{"BG3500", "(SC)  Jardins de Mutamin"},~
	REPLACE_TEXTUALLY ~{"BG3600", "Lighthouse"},~                                                               ~{"BG3600", "(SC)  Phare, (Safana)"},~
	REPLACE_TEXTUALLY ~{"BG3601", "Lighthouse: Black Alaric's Cave"},~                                          ~{"BG3601", "(SC)  Grotte de Black Alaric"},~
	REPLACE_TEXTUALLY ~{"BG3700", "Red Canyons"},~                                                              ~{"BG3700", "(SC)  Canyons rouges"},~
	REPLACE_TEXTUALLY ~{"BG3800", "Trade Way North"},~                                                          ~{"BG3800", "(SC)  Route de Nashkel"},~
	REPLACE_TEXTUALLY ~{"BG3802", "Trade Way North: Cave"},~                                                    ~{"BG3802", "(SC)  Grotte de la Route de Nashkel"},~
	REPLACE_TEXTUALLY ~{"BG3900", "Ulcaster"},~                                                                 ~{"BG3900", "(SC)  École d’Ulcaster"},~
	REPLACE_TEXTUALLY ~{"BG3901", "Ulcaster Ruins"},~                                                           ~{"BG3901", "(SC)  Ruines de l'école d’Ulcaster"},~
	REPLACE_TEXTUALLY ~{"BG4000", "Gullykin"},~                                                                 ~{"BG4000", "  GULLYKIN"},~
	REPLACE_TEXTUALLY ~{"BG4001", "Gullykin: Jenkal's House L1"},~                                              ~{"BG4001", "(G)  Maison de Jenkal, L1"},~
	REPLACE_TEXTUALLY ~{"BG4002", "Gullykin: Jenkal's House Cellar"},~                                          ~{"BG4002", "(G)  Maison de Jenkal, Cellier"},~
	REPLACE_TEXTUALLY ~{"BG4003", "Gullykin: Winery L1"},~                                                      ~{"BG4003", "(G)  Temple de Yondalla, L1"},~
	REPLACE_TEXTUALLY ~{"BG4004", "Gullykin: Winery Cellar"},~                                                  ~{"BG4004", "(G)  Temple de Yondalla, Cellier"},~
	REPLACE_TEXTUALLY ~{"BG4005", "Gullykin: House1 L1"},~                                                      ~{"BG4005", "(G)  Maison 1, L1"},~
	REPLACE_TEXTUALLY ~{"BG4006", "Gullykin: House1 Cellar"},~                                                  ~{"BG4006", "(G)  Maison 1, Cellier"},~
	REPLACE_TEXTUALLY ~{"BG4007", "Gullykin: House3 L1"},~                                                      ~{"BG4007", "(G)  Maison 3, L1"},~
	REPLACE_TEXTUALLY ~{"BG4008", "Gullykin: House3 Cellar"},~                                                  ~{"BG4008", "(G)  Maison 3, Cellier"},~
	REPLACE_TEXTUALLY ~{"BG4009", "Gullykin: House4 L1"},~                                                      ~{"BG4009", "(G)  Maison 4, L1"},~
	REPLACE_TEXTUALLY ~{"BG4010", "Gullykin: House4 Cellar"},~                                                  ~{"BG4010", "(G)  Maison 4, Cellier"},~
	REPLACE_TEXTUALLY ~{"BG4011", "Gullykin: House5 L1"},~                                                      ~{"BG4011", "(G)  Maison 5, L1"},~
	REPLACE_TEXTUALLY ~{"BG4012", "Gullykin: House5 Cellar"},~                                                  ~{"BG4012", "(G)  Maison 5, Cellier"},~
	REPLACE_TEXTUALLY ~{"BG4013", "Gullykin: House2 L1"},~                                                      ~{"BG4013", "(G)  Maison 2, L1"},~
	REPLACE_TEXTUALLY ~{"BG4014", "Gullykin: House2 Cellar"},~                                                  ~{"BG4014", "(G)  Maison 2, Cellier"},~
	REPLACE_TEXTUALLY ~{"BG4100", "Ancient Ruins"},~                                                            ~{"BG4100", "(SC)  Site archéologique"},~
	REPLACE_TEXTUALLY ~{"BG4101", "Ancient Ruins: Tomb"},~                                                      ~{"BG4101", "(SC)  Tombe"},~
	REPLACE_TEXTUALLY ~{"BG4200", "Wilderness Lake"},~                                                          ~{"BG4200", "(SC)  Lac dans la campagne"},~
	REPLACE_TEXTUALLY ~{"BG4300", "Trade Way South"},~                                                          ~{"BG4300", "(SC)  Passe de Nashkel"},~
	REPLACE_TEXTUALLY ~{"BG4400", "Lonely Peaks"},~                                                             ~{"BG4400", "(SC)  Plaines de Flammevin"},~
	REPLACE_TEXTUALLY ~{"BG4401", "Lonely Peaks: Cave"},~                                                       ~{"BG4401", "(SC)  Grotte des plaines de Flammevin"},~
	REPLACE_TEXTUALLY ~{"BG4500", "Firewine Bridge"},~                                                          ~{"BG4500", "(SC)  Pont de Flammevin"},~
	REPLACE_TEXTUALLY ~{"BG4501", "Cloakwood Crossings: Wyvern Cave"},~                                         ~{"BG4501", "(B-M)  Grotte des Wyvernes de Bois-Manteau, (4)"},~
	REPLACE_TEXTUALLY ~{"BG4600", "Bear River"},~                                                               ~{"BG4600", "(SC)  Rivière de l'Ours"},~
	REPLACE_TEXTUALLY ~{"BG4700", "Xvart Village"},~                                                            ~{"BG4700", "(SC)  Village Xvart"},~
	REPLACE_TEXTUALLY ~{"BG4701", "Xvart Village: Cave"},~                                                      ~{"BG4701", "(SC)  Grotte d'Ursa l'ours"},~
	REPLACE_TEXTUALLY ~{"BG4800", "Nashkel"},~                                                                  ~{"BG4800", "  NASHKEL, (Minsc, Edwin, Rasaad)"},~
	REPLACE_TEXTUALLY ~{"BG4801", "Nashkel: Inn"},~                                                             ~{"BG4801", "(N)  Auberge de Nashkel"},~
	REPLACE_TEXTUALLY ~{"BG4802", "Nashkel: Temple of Helm"},~                                                  ~{"BG4802", "(N)  Temple de Heaum"},~
	REPLACE_TEXTUALLY ~{"BG4803", "Nashkel: Store"},~                                                           ~{"BG4803", "(N)  Magasin de Nashkel"},~
	REPLACE_TEXTUALLY ~{"BG4804", "Nashkel: Manor House L1"},~                                                  ~{"BG4804", "(N)  Manoir de Nashkel, L1"},~
	REPLACE_TEXTUALLY ~{"BG4805", "Nashkel: Manor House L2"},~                                                  ~{"BG4805", "(N)  Manoir de Nashkel, L2"},~
	REPLACE_TEXTUALLY ~{"BG4806", "Nashkel: Joseph's House"},~                                                  ~{"BG4806", "(N)  Maison de Joseph"},~
	REPLACE_TEXTUALLY ~{"BG4807", "Nashkel: House1"},~                                                          ~{"BG4807", "(N)  Maison 1"},~
	REPLACE_TEXTUALLY ~{"BG4808", "Nashkel: House2"},~                                                          ~{"BG4808", "(N)  Maison 2"},~
	REPLACE_TEXTUALLY ~{"BG4809", "Nashkel: Belching Dragon Tavern"},~                                          ~{"BG4809", "(N)  Taverne du Dragon Qui Rote"},~
	REPLACE_TEXTUALLY ~{"BG4810", "Nashkel: Garrison"},~                                                        ~{"BG4810", "(N)  Caserne"},~
	REPLACE_TEXTUALLY ~{"BG4900", "Nashkel Carnival"},~                                                         ~{"BG4900", "(N-f)  Festival de Nashkel, (Branwen)"},~
	REPLACE_TEXTUALLY ~{"BG4901", "Nashkel Carnival: Armor Tent"},~                                             ~{"BG4901", "(N-f)  Marchand d’armures"},~
	REPLACE_TEXTUALLY ~{"BG4902", "Nashkel Carnival: Lotus Tent"},~                                             ~{"BG4902", "(N-f)  Lotus noir"},~
	REPLACE_TEXTUALLY ~{"BG4903", "Nashkel Carnival: Vitiare's Tent"},~                                         ~{"BG4903", "(N-f)  Tente de jeux, Vitiare"},~
	REPLACE_TEXTUALLY ~{"BG4904", "Nashkel Carnival: Gambling Tent"},~                                          ~{"BG4904", "(N-f)  Tente de jeux"},~
	REPLACE_TEXTUALLY ~{"BG4905", "Nashkel Carnival: Potion Tent"},~                                            ~{"BG4905", "(N-f)  Marchand de potions rares"},~
	REPLACE_TEXTUALLY ~{"BG4906", "Nashkel Carnival: Zordral's Tent"},~                                         ~{"BG4906", "(N-f)  Tente de Zordral"},~
	REPLACE_TEXTUALLY ~{"BG4907", "Nashkel Carnival: Magic Items Tent"},~                                       ~{"BG4907", "(N-f)  Marchand d’objets magiques"},~
	REPLACE_TEXTUALLY ~{"BG4908", "Nashkel Carnival: Melee Weapons Tent"},~                                     ~{"BG4908", "(N-f)  Marchand d’armes de mêlée"},~
	REPLACE_TEXTUALLY ~{"BG4909", "Nashkel Carnival: Ranged Weapons Tent"},~                                    ~{"BG4909", "(N-f)  Marchand d’armes de jet"},~
	REPLACE_TEXTUALLY ~{"BG5000", "Valley of the Tombs"},~                                                      ~{"BG5000", "(SC)  Vallée des Tombes"},~
	REPLACE_TEXTUALLY ~{"BG5001", "Valley of the Tombs: Tomb"},~                                                ~{"BG5001", "(SC)  Tombes de la Vallée des Tombes"},~
	REPLACE_TEXTUALLY ~{"BG5100", "Gnoll Stronghold"},~                                                         ~{"BG5100", "(SC)  Forteresse gnoll, (Dynahéir)"},~
	REPLACE_TEXTUALLY ~{"BG5101", "Gnoll Stronghold: Xvart Cave"},~                                             ~{"BG5101", "(SC)  Grotte de la forteresse, (Xvarts)"},~
	REPLACE_TEXTUALLY ~{"BG5102", "Gnoll Stronghold: Tome Cave"},~                                              ~{"BG5102", "(SC)  Grotte de la forteresse, (Traité)"},~
	REPLACE_TEXTUALLY ~{"BG5103", "Gnoll Stronghold: Crawler Cave"},~                                           ~{"BG5103", "(SC)  Grotte de la forteresse, (Vers charognards)"},~
	REPLACE_TEXTUALLY ~{"BG5200", "Dryad Falls"},~                                                              ~{"BG5200", "(SC)  Chutes de la dryade"},~
	REPLACE_TEXTUALLY ~{"BG5201", "Firewine Ruins"},~                                                           ~{"BG5201", "(SC)  Ruines de Flammevin"},~
	REPLACE_TEXTUALLY ~{"BG5202", "Dryad Falls: Cave"},~                                                        ~{"BG5202", "(SC)  Caverne des Chutes de la dryade"},~
	REPLACE_TEXTUALLY ~{"BG5300", "Fire Leaf Forest"},~                                                         ~{"BG5300", "(SC)  Forêt des feuilles écarlates"},~
	REPLACE_TEXTUALLY ~{"BG5400", "Nashkel Mines"},~                                                            ~{"BG5400", "(N-m)  Mines de Nashkel"},~
	REPLACE_TEXTUALLY ~{"BG5401", "Nashkel Mines: L1"},~                                                        ~{"BG5401", "(N-m)  Mines, L1"},~
	REPLACE_TEXTUALLY ~{"BG5402", "Nashkel Mines: L2"},~                                                        ~{"BG5402", "(N-m)  Mines, L2"},~
	REPLACE_TEXTUALLY ~{"BG5403", "Nashkel Mines: L3"},~                                                        ~{"BG5403", "(N-m)  Mines, L3"},~
	REPLACE_TEXTUALLY ~{"BG5404", "Nashkel Mines: L4"},~                                                        ~{"BG5404", "(N-m)  Mines, L4"},~
	REPLACE_TEXTUALLY ~{"BG5405", "Nashkel Mines: Mulahey's Cave"},~                                            ~{"BG5405", "(N-m)  Mines, Repère de Mulahey (Xan)"},~
	REPLACE_TEXTUALLY ~{"BG5406", "Nashkel Mines: Cabin"},~                                                     ~{"BG5406", "(N-m)  Réserve des Mines de Nashkel"},~
	REPLACE_TEXTUALLY ~{"BG5500", "Gibberling Mountains"},~                                                     ~{"BG5500", "(SC)  Montagnes des Grouilleux"},~
	REPLACE_TEXTUALLY ~{"BG5506", "Candlekeep Caves"},~                                                         ~{"BG5506", "(C-S)  Cavernes sous Château-Suif"},~
	REPLACE_TEXTUALLY ~{"BG5600", "Random Encounter: Plains1"},~                                                ~{"BG5600", "  Aléatoire, Plaine 1"},~
	REPLACE_TEXTUALLY ~{"BG5601", "Random Encounter: Plains2"},~                                                ~{"BG5601", "  Aléatoire, Plaine 2"},~
	REPLACE_TEXTUALLY ~{"BG5700", "Random Encounter: Canyon1"},~                                                ~{"BG5700", "  Aléatoire, Canyon 1"},~
	REPLACE_TEXTUALLY ~{"BG5701", "Random Encounter: Canyon2"},~                                                ~{"BG5701", "  Aléatoire, Canyon 2"},~
	REPLACE_TEXTUALLY ~{"BG5800", "Random Encounter: Cliff1"},~                                                 ~{"BG5800", "  Aléatoire, Falaise 1"},~
	REPLACE_TEXTUALLY ~{"BG5801", "Random Encounter: Cliff2"},~                                                 ~{"BG5801", "  Aléatoire, Falaise 2"},~
	REPLACE_TEXTUALLY ~{"BG5900", "Random Encounter: Grassland1"},~                                             ~{"BG5900", "  Aléatoire, Prairie 1"},~
	REPLACE_TEXTUALLY ~{"BG5901", "Random Encounter: Grassland2"},~                                             ~{"BG5901", "  Aléatoire, Prairie 2"},~
	REPLACE_TEXTUALLY ~{"BG6000", "Random Encounter: Forest1"},~                                                ~{"BG6000", "  Aléatoire, Forêt 1"},~
	REPLACE_TEXTUALLY ~{"BG6001", "Random Encounter: Forest2"},~                                                ~{"BG6001", "  Aléatoire, Forêt 2"},~
	REPLACE_TEXTUALLY ~{"BG6100", "Random Encounter: Road"},~                                                   ~{"BG6100", "  Aléatoire, Route"},
	{"OH1000", "  Aléatoire, (Dorn recrutement)"},~
	REPLACE_TEXTUALLY ~{"OH2000", "Adoy's Enclave"},~                                                           ~{"OH2000", "(SC)  Enclave d'Adoy, (Quête de Neera)"},
	{"OH2010", "(SC)  Enclave d'Adoy, intérieur"},~ 
	REPLACE_TEXTUALLY ~{"OH3000", "Cloud Peaks"},~                                                              ~{"OH3000", "(SC)  Pics Brumeux, (Quête de Rasaad)"},
	{"OH3010", "(SC)  Temple de la Lune Noire, Entrée"},
	{"OH3020", "(SC)  Temple de la Lune Noire, Geôles"},
	{"OH3100", "(SC)  Temple de la Lune Noire, Sommet"},~                                                                                       
	
	// CheatsAreas Les Fosses noires~
	
	REPLACE_TEXTUALLY ~{"OH9310", "TBP - Arena 1"},~                                                            ~{"OH9310", "(FN1)  Arène 1"},~
	REPLACE_TEXTUALLY ~{"OH9350", "TBP - Arena 2"},~                                                            ~{"OH9350", "(FN1)  Arène 2"},~
	REPLACE_TEXTUALLY ~{"OH9360", "TBP - Staging Area Map"},~                                                   ~{"OH9360", "(FN1)  Zone de repos"},~
	
	// CheatsAreas Tutoriel~
	
	REPLACE_TEXTUALLY ~{"TU0015", "Baldur's Gate Estate (Tutorial starts here)"},~                                ~{"TU0015", "(Tuto)  Palais Ducal, 1er étage (Commencement)"},~
	REPLACE_TEXTUALLY ~{"TU0016", "Baldur's Gate Estate (Tutorial area)"},~                                       ~{"TU0016", "(Tuto)  Palais Ducal, 2eme étage"},~
	REPLACE_TEXTUALLY ~{"TU0017", "Baldur's Gate Estate (Tutorial area)"},~                                       ~{"TU0017", "(Tuto)  Palais Ducal, 3eme étage"},~
	REPLACE_TEXTUALLY ~{"TU0018", "Baldur's Gate Estate Cellar (Tutorial area)"},~                                ~{"TU0018", "(Tuto)  Palais Ducal, Sous-sol"},~
	
	// CheatsAreas pour SoD~                                                                                            
																														
	REPLACE_TEXTUALLY ~{"BD0010", "Ducal Palace City Exterior"},~                                                       ~{"BD0010", "(SoD)  Palais Ducal"},~
	REPLACE_TEXTUALLY ~{"BD0020", "Sorcerous/Elf Song City Exterior"},~                                                 ~{"BD0020", "(SoD)  Bazar Magique / Taverne du Chant de l'elfe"},~
	REPLACE_TEXTUALLY ~{"BD0030", "Flaming Fist City Exterior"},~                                                       ~{"BD0030", "(SoD)  Siege du Poing Enflamme"},~
	REPLACE_TEXTUALLY ~{"BD0040", "Three Kegs City Exterior"},~                                                         ~{"BD0040", "(SoD)  Auberge des Trois Vieilles Chopes"},~
	REPLACE_TEXTUALLY ~{"BD0050", "Iron Throne City Exterior"},~                                                        ~{"BD0050", "(SoD)  Trône de Fer"},~
	REPLACE_TEXTUALLY ~{"BD0060", "Random Area - Cave Entrance"},~                                                      ~{"BD0060", "  Aléatoire, Entree de la Caverne"},~
	REPLACE_TEXTUALLY ~{"BD0061", "Random Area - Cave Interior from BD0060"},~                                          ~{"BD0061", "  Aléatoire, Intérieur de la Caverne"},~
	REPLACE_TEXTUALLY ~{"BD0062", "Random Area - Cave Pool from BD0061"},~                                              ~{"BD0062", "  Aléatoire, Bassin de la Caverne"},~
	REPLACE_TEXTUALLY ~{"BD0063", "Random Area - Canyon Ambush"},~                                                      ~{"BD0063", "  Aléatoire, Embuscade"},~
	REPLACE_TEXTUALLY ~{"BD0064", "Random Area - Forest Paths"},~                                                       ~{"BD0064", "  Aléatoire, Chemin dans la forêt"},~
	REPLACE_TEXTUALLY ~{"BD0065", "Random Area - Wilderness Open Area"},~                                               ~{"BD0065", "  Aléatoire, Territoire sauvage"},~
	REPLACE_TEXTUALLY ~{"BD0066", "Random Area - Wilderness Hole to BD0067"},~                                          ~{"BD0066", "  Aléatoire, Trou béant"},~
	REPLACE_TEXTUALLY ~{"BD0067", "Random Area - Cave Interior from BD0066"},~                                          ~{"BD0067", "  Aléatoire, Intérieur du trou béant"},~
	REPLACE_TEXTUALLY ~{"BD0070", "The Scrying Pool - The Hooded Man Cutscene"},~                                       ~{"BD0070", "Cinématique du Bassin, L'homme à la capuche"},~
	REPLACE_TEXTUALLY ~{"BD0071", "The Scrying Pool - Caelar Cutscene"},~                                               ~{"BD0071", "Cinématique du Bassin, Caelar"},~
	REPLACE_TEXTUALLY ~{"BD0100", "Ducal Palace  Second Floor"},~                                                       ~{"BD0100", "(SoD)  Palais Ducal, L2"},~
	REPLACE_TEXTUALLY ~{"BD0101", "Ducal Palace  Leaving BG"},~                                                         ~{"BD0101", "(SoD)  Palais Ducal, Le grand depart"},~
	REPLACE_TEXTUALLY ~{"BD0102", "Ducal Palace  First Floor"},~                                                        ~{"BD0102", "(SoD)  Palais Ducal, L1"},~
	REPLACE_TEXTUALLY ~{"BD0103", "Ducal Palace  Third Floor"},~                                                        ~{"BD0103", "(SoD)  Palais Ducal, L3"},~
	REPLACE_TEXTUALLY ~{"BD0104", "Flaming Fist HQ"},~                                                                  ~{"BD0104", "(SoD)  Siege du Poing Enflamme"},~
	REPLACE_TEXTUALLY ~{"BD0105", "Flaming Fist HQ  Basement"},~                                                        ~{"BD0105", "(SoD)  Siege du Poing Enflamme, Sous-sol"},~
	REPLACE_TEXTUALLY ~{"BD0106", "Three Old Kegs  First Floor"},~                                                      ~{"BD0106", "(SoD)  Auberge des Trois Vieilles Chopes, L1"},~
	REPLACE_TEXTUALLY ~{"BD0107", "Three Old Kegs  Second Floor"},~                                                     ~{"BD0107", "(SoD)  Auberge des Trois Vieilles Chopes, L2"},~
	REPLACE_TEXTUALLY ~{"BD0108", "Three Old Kegs  Third Floor"},~                                                      ~{"BD0108", "(SoD)  Auberge des Trois Vieilles Chopes, L3"},~
	REPLACE_TEXTUALLY ~{"BD0109", "Elfsong Tavern  First Floor"},~                                                      ~{"BD0109", "(SoD)  Taverne du Chant de l'elfe, L1"},~
	REPLACE_TEXTUALLY ~{"BD0110", "Elfsong Tavern  Second Floor"},~                                                     ~{"BD0110", "(SoD)  Taverne du Chant de l'elfe, L2"},~
	REPLACE_TEXTUALLY ~{"BD0111", "Iron Throne Floor  First Floor"},~                                                   ~{"BD0111", "(SoD)  Trône de Fer, L1"},~
	REPLACE_TEXTUALLY ~{"BD0112", "Baldur s Gate East"},~                                                               ~{"BD0112", "(SoD)  Porte de Baldur Est, Le grand depart"},~
	REPLACE_TEXTUALLY ~{"BD0113", "Underground Cavern Wyrms"},~                                                         ~{"BD0113", "(SoD)  Caverne des Vers, (Rivière souterraine)"},~
	REPLACE_TEXTUALLY ~{"BD0114", "Spider Cave"},~                                                                      ~{"BD0114", "(SoD)  Trou des araignées, (Forêt des dragons)"},~
	REPLACE_TEXTUALLY ~{"BD0115", "Vampire Cavern"},~                                                                   ~{"BD0115", "(SoD)  Grotte du Vampire, (Forêt de la Voie Côtière)"},~
	REPLACE_TEXTUALLY ~{"BD0116", "Ducal Palace, Basement"},~                                                           ~{"BD0116", "(SoD)  Palais Ducal, Sous-sol"},~
	REPLACE_TEXTUALLY ~{"BD0117", "Iron Throne  Basement"},~                                                            ~{"BD0117", "(SoD)  Palais Ducal, Sous-sol"},~
	REPLACE_TEXTUALLY ~{"BD0118", "The Scrying Pool - Imoen Cutscene"},~                                                ~{"BD0118", "Cinématique du Bassin, Imoen"},~
	REPLACE_TEXTUALLY ~{"BD0120", "Tomb Safehouse  First Floor"},~                                                      ~{"BD0120", "(SoD)  Donjon de Korlasz, L1"},~
	REPLACE_TEXTUALLY ~{"BD0121", "Sorcerous Sundries  First Floor"},~                                                  ~{"BD0121", "(SoD)  Bazar Magique, L1"},~
	REPLACE_TEXTUALLY ~{"BD0122", "Sorcerous Sundries  Second Floor"},~                                                 ~{"BD0122", "(SoD)  Bazar Magique, L2"},~
	REPLACE_TEXTUALLY ~{"BD0130", "Tomb Safehouse  Second Floor"},~                                                     ~{"BD0130", "(SoD)  Donjon de Korlasz, L2"},~
	REPLACE_TEXTUALLY ~{"BD1000", "Coast Way Crossing"},~                                                               ~{"BD1000", "(SoD)  Pont de la Voie Côtière"},~
	REPLACE_TEXTUALLY ~{"BD1010", "Cave (generic)"},~                                                                   ~{"BD1010", "(SoD)  Grotte du Mimique, (Défilé du Trépassé)"},~
	REPLACE_TEXTUALLY ~{"BD1100", "The Dig"},~                                                                          ~{"BD1100", "(SoD)  Site d'excavation nain, (Pont de la Voie Côtière)"},~
	REPLACE_TEXTUALLY ~{"BD1200", "Lich Outpost"},~                                                                     ~{"BD1200", "(SoD)  Repaire de la liche, (Site d'excavation nain)"},~
	REPLACE_TEXTUALLY ~{"BD2000", "Boareskyr Bridge & Bridgefort"},~                                                    ~{"BD2000", "(SoD)  Pont de Boreskyr / Fort-du-Pont"},~
	REPLACE_TEXTUALLY ~{"BD2010", "Cave (generic)"},~                                                                   ~{"BD2010", "(SoD)  Grotte, (Fort-du-Pont)"},~
	REPLACE_TEXTUALLY ~{"BD2100", "Bridgefort Interior"},~                                                              ~{"BD2100", "(SoD)  Fort-du-Pont"},~
	REPLACE_TEXTUALLY ~{"BD3000", "Allied Siege Camp"},~                                                                ~{"BD3000", "(SoD)  Camp de la coalition"},~
	REPLACE_TEXTUALLY ~{"BD4000", "Dragonspear Castle  Exterior"},~                                                     ~{"BD4000", "(SoD)  Château Paldragon"},~
	REPLACE_TEXTUALLY ~{"BD4100", "Dragonspear Castle Keep  First Floor"},~                                             ~{"BD4100", "(SoD)  Château Paldragon, L1"},~
	REPLACE_TEXTUALLY ~{"BD4300", "Dragonspear Castle Basement"},~                                                      ~{"BD4300", "(SoD)  Château Paldragon, Sous-sols"},~
	REPLACE_TEXTUALLY ~{"BD4400", "Avernus"},~                                                                          ~{"BD4400", "(SoD)  Avernus, (Portail)"},~
	REPLACE_TEXTUALLY ~{"BD4500", "Avernus Bridge"},~                                                                   ~{"BD4500", "(SoD)  Le pont d'Avernus"},~
	REPLACE_TEXTUALLY ~{"BD4600", "Avernus Interior"},~                                                                 ~{"BD4600", "(SoD)  Tour de basalte, (Avernus)"},~
	REPLACE_TEXTUALLY ~{"BD4601", "Avernus Elevator"},~                                                                 ~{"BD4601", "(SoD)  Élévateur, (Avernus)"},~
	REPLACE_TEXTUALLY ~{"BD4700", "Avernus Roof"},~                                                                     ~{"BD4700", "(SoD)  Sommet de l'Avernus, (Belhifet)"},~
	REPLACE_TEXTUALLY ~{"BD5000", "Underground River Entrance"},~                                                       ~{"BD5000", "(SoD)  Entree de la Rivière souterraine"},~
	REPLACE_TEXTUALLY ~{"BD5100", "Underground River"},~                                                                ~{"BD5100", "(SoD)  Rivière souterraine"},~
	REPLACE_TEXTUALLY ~{"BD5110", "Ettin Ghost Cave"},~                                                                 ~{"BD5110", "(SoD)  Grotte de l'Ettin, (Rivière souterraine)"},~
	REPLACE_TEXTUALLY ~{"BD5200", "The Warrens"},~                                                                      ~{"BD5200", "(SoD)  Les terriers sous le Château Paldragon"},~
	REPLACE_TEXTUALLY ~{"BD5300", "Kanaglym"},~                                                                         ~{"BD5300", "(SoD)  Kanaglym"},~
	REPLACE_TEXTUALLY ~{"BD6000", "Abandoned Sewers & Caverns"},~                                                       ~{"BD6000", "(SoD)  Égouts / Caverne"},~
	REPLACE_TEXTUALLY ~{"BD6200", "Sewers Exit"},~                                                                      ~{"BD6200", "(SoD)  Sortie des égouts / Groupe pour BG2"},~
	REPLACE_TEXTUALLY ~{"BD6100", "The Ambush"},~                                                                       ~{"BD6100", "(SoD)  Transition / Fin de SoD"},~
	REPLACE_TEXTUALLY ~{"BD7000", "Coast Way Forest"},~                                                                 ~{"BD7000", "(SoD)  Forêt de la Voie Côtière"},~
	REPLACE_TEXTUALLY ~{"BD7100", "Troll Forest"},~                                                                     ~{"BD7100", "(SoD)  Bois des Griffes de Troll"},~
	REPLACE_TEXTUALLY ~{"BD7110", "Troll Cave"},~                                                                       ~{"BD7110", "(SoD)  Grotte des Trolls"},~
	REPLACE_TEXTUALLY ~{"BD7200", "Forest of Wyrms"},~                                                                  ~{"BD7200", "(SoD)  Forêt des dragons"},~
	REPLACE_TEXTUALLY ~{"BD7210", "Wyrm Cave"},~                                                                        ~{"BD7210", "(SoD)  Caverne aux Dragons, (Forêt des dragons)"},~
	REPLACE_TEXTUALLY ~{"BD7220", "Bugbear Stronghold"},~                                                               ~{"BD7220", "(SoD)  Grotte des Gobelours, (Caverne aux Dragons)"},~
	REPLACE_TEXTUALLY ~{"BD7230", "Temple of Cyric"},~                                                                  ~{"BD7230", "(SoD)  Temple de Cyric, (Grotte des Gobelours)"},~
	REPLACE_TEXTUALLY ~{"BD7300", "Dead Man s Pass"},~                                                                  ~{"BD7300", "(SoD)  Défilé du Trépassé"},~
	REPLACE_TEXTUALLY ~{"BD7310", "Hidden Cellar/Treasure Stash"},~                                                     ~{"BD7310", "(SoD)  Cave dissimulée, (Défilé du Trépassé)"},~
	REPLACE_TEXTUALLY ~{"BD7400", "Bloodbark Grove"},~                                                                  ~{"BD7400", "(SoD)  Bosquet d'Ecorsang"},~
	REPLACE_TEXTUALLY ~{"BD7410", "Vampire Hideout"},~                                                                  ~{"BD7410", "(SoD)  Cave du vampire, (Bosquet d'Ecorsang)"},~

	// CheatsAreas SoA                                                                                                  
																														
	REPLACE_TEXTUALLY ~{"AR0011", "Candlekeep Dream 1 (Do you remember Candlekeep?)"},~                                 ~{"AR0011", "(Rêve)  Souvenirs de Château-Suif"},~
	REPLACE_TEXTUALLY ~{"AR0012", "Candlekeep Library (Main Door Trigger)"},~                                           ~{"AR0012", "(Rêve)  Attire la bête ici... c'est ta seule chance"},~
	REPLACE_TEXTUALLY ~{"AR0013", "Candlekeep Library (Stairway Triggers Up and Down)"},~                               ~{"AR0013", "(Rêve)  Ce que vous pouvez être"},~
	REPLACE_TEXTUALLY ~{"AR0014", "Candlekeep Library (Stairway Trigger Down)"},~                                       ~{"AR0014", "(Rêve)  Un, deux, trois, quatre... CINQ"},~
	REPLACE_TEXTUALLY ~{"AR0020", "City Gates"},~                                                                       ~{"AR0020", "  LES PORTES DE LA VILLE"},~
	REPLACE_TEXTUALLY ~{"AR0021", "Crooked Crane 1st Floor"},~                                                          ~{"AR0021", "(P)  Auberge du Crâne Tordu, L1"},~
	REPLACE_TEXTUALLY ~{"AR0022", "Crooked Crane 2nd Floor"},~                                                          ~{"AR0022", "(P)  Auberge du Crâne Tordu, L2"},~
	REPLACE_TEXTUALLY ~{"AR0028", "Candlekeep Dream (After PC Soultheft)"},~                                            ~{"AR0028", "(Rêve)  Abandonnez une partie de vous même"},~
	REPLACE_TEXTUALLY ~{"AR0041", "Random Encounter City"},~                                                            ~{"AR0041", "  Aléatoire, Ville 1"},~
	REPLACE_TEXTUALLY ~{"AR0042", "Random Encounter Outdoor"},~                                                         ~{"AR0042", "  Aléatoire, Forêt 1"},~
	REPLACE_TEXTUALLY ~{"AR0043", "Random Encounter Outdoor (With rocks)"},~                                            ~{"AR0043", "  Aléatoire, Forêt 2 (Roche)"},~
	REPLACE_TEXTUALLY ~{"AR0044", "Random Encounter Outdoor (sand)"},~                                                  ~{"AR0044", "  Aléatoire, Forêt 3 (sable)"},~
	REPLACE_TEXTUALLY ~{"AR0045", "Random Encounter City"},~                                                            ~{"AR0045", "  Aléatoire, Ville 2"},~
	REPLACE_TEXTUALLY ~{"AR0046", "Random Encounter City (bridge)"},~                                                   ~{"AR0046", "  Aléatoire, Ville 3 (pont)"},~
	REPLACE_TEXTUALLY ~{"AR0060", "Empty (Triggers, Doors... are there but no area)"},~                                 ~{"AR0060", "Néant"},~
	REPLACE_TEXTUALLY ~{"AR0061", "Empty (Triggers, Doors... are there but no area)"},~                                 ~{"AR0061", "Néant"},~
	REPLACE_TEXTUALLY ~{"AR0062", "Empty (Triggers, Doors... are there but no area)"},~                                 ~{"AR0062", "Néant"},~
	REPLACE_TEXTUALLY ~{"AR0063", "Empty (Triggers, Doors... are there but no area)"},~                                 ~{"AR0063", "Néant"},~
	REPLACE_TEXTUALLY ~{"AR0064", "Empty (Triggers, Doors... are there but no area)"},~                                 ~{"AR0064", "Néant"},~
	REPLACE_TEXTUALLY ~{"AR0065", "Empty (Triggers, Doors... are there but no area)"},~                                 ~{"AR0065", "Néant"},~
	REPLACE_TEXTUALLY ~{"AR0069", "Government Building (Cowled Cutscene -- 'Why is this man not gagged?')"},~           ~{"AR0069", "(Ciné)  Qu'ils pourrissent à Spellhold !"},~
	REPLACE_TEXTUALLY ~{"AR0070", "Spellhold (Irenicus Cutscene -- 'I cannot be caged...')"},~                          ~{"AR0070", "(Ciné)  Irenicus prend le contrôle de Spellhold"},~
	REPLACE_TEXTUALLY ~{"AR0071", "Spellhold (Imoen Soultheft Cutscene -- 'Silence do, you have no purpose...')"},~     ~{"AR0071", "(Ciné)  Imoen perd son Âme à Spellhold (Chapitre )')"},~
	REPLACE_TEXTUALLY ~{"AR0072", "Ust Natha Temple (Irenicus/Bodhi, Ardula/Phaere Cutscene)"},~                        ~{"AR0072", "(Ciné)  Irenicus et Bodhi à Ust Natha (Chapitre )"},~
	REPLACE_TEXTUALLY ~{"AR0082", "Lich Grave in Bridge District Inn"},~                                                ~{"AR0082", "(P)  Auberge du Crâne Tordu, Liche"},~
	REPLACE_TEXTUALLY ~{"AR0083", "Candlekeep Library (Dream: PC learns to control the Slayer)"},~                      ~{"AR0083", "(Rêve)  Apprendre à contrôler l'Echorcheur"},~
	REPLACE_TEXTUALLY ~{"AR0084", "Candlekeep Library (Stairway trigger down)"},~                                       ~{"AR0084", "(Rêve) Tout est question de puissance"},~
	REPLACE_TEXTUALLY ~{"AR0085", "Tree of Life"},~                                                                     ~{"AR0085", "(Rêve)  Ellésime et L'Arbre de Vie"},~
	REPLACE_TEXTUALLY ~{"AR0086", "Wooded Area"},~                                                                      ~{"AR0086", "(CLUA)  Zone Boisée / Têtes de pierre"},~
	REPLACE_TEXTUALLY ~{"AR0087", "Elven Dining Room"},~                                                                ~{"AR0087", "(Ciné)  Diner avec les elfes"},~
	REPLACE_TEXTUALLY ~{"AR0201", "Leading to ghoul village and beholder lair (Temple District)"},~                     ~{"AR0201", "(D-t)  Vers le village des goules et l'antre, (Œil Aveugle)"},~
	REPLACE_TEXTUALLY ~{"AR0202", "The Unseeing Eye Cult Hideout"},~                                                    ~{"AR0202", "(D-t)  Culte de l'Œil Aveugle"},~
	REPLACE_TEXTUALLY ~{"AR0203", "Temple of the Forgotten God -- Amaunator (Unseeing Eye Plot)"},~                     ~{"AR0203", "(D-t)  Temple du dieu oublié, (Œil Aveugle)"},~
	REPLACE_TEXTUALLY ~{"AR0204", "The Forgotten Believers -- Temple City (Unseeing Eye Plot)"},~                       ~{"AR0204", "(D-t)  Les adeptes oubliés, (Œil Aveugle)"},~
	REPLACE_TEXTUALLY ~{"AR0205", "The Beholder Hideout (Unseeing Eye Plot)"},~                                         ~{"AR0205", "(D-t)  L'antre de l'Œil Aveugle"},~
	REPLACE_TEXTUALLY ~{"AR0206", "Ghoul village (Temple District)"},~                                                  ~{"AR0206", "(D-t)  Le village des goules, (Œil Aveugle)"},~
	REPLACE_TEXTUALLY ~{"AR0300", "The Docks"},~                                                                        ~{"AR0300", "  LES QUAIS"},~
	REPLACE_TEXTUALLY ~{"AR0301", "Mae'Var's Hide Out"},~                                                               ~{"AR0301", "(Q)  Guilde de Mae’Var, Planque"},~
	REPLACE_TEXTUALLY ~{"AR0302", "Mae'Var's Inn 1st Floor -- Entrance"},~                                              ~{"AR0302", "(Q)  Guilde de Mae’Var, L1"},~
	REPLACE_TEXTUALLY ~{"AR0303", "Mae'Var's Inn 2nd Floor -- Training Area"},~                                         ~{"AR0303", "(Q)  Guilde de Mae’Var, L2"},~
	REPLACE_TEXTUALLY ~{"AR0304", "Mae'Var's Inn 3rd Floor -- Edwin"},~                                                 ~{"AR0304", "(Q)  Guilde de Mae’Var, L3 (Edwin)"},~
	REPLACE_TEXTUALLY ~{"AR0305", "Shadow Thieves Guild Entrance"},~                                                    ~{"AR0305", "(Q)  Guilde des Voleurs de l’Ombre, L1"},~
	REPLACE_TEXTUALLY ~{"AR0306", "Renal Bloodscalp's Hideout"},~                                                       ~{"AR0306", "(Q)  Guilde des Voleurs de l’Ombre, L2 (Renal Bloodscalp)"},~
	REPLACE_TEXTUALLY ~{"AR0307", "Aran Linvail's Hideout"},~                                                           ~{"AR0307", "(Q)  Guilde des Voleurs de l’Ombre, L3 (Aran Linvail)"},~
	REPLACE_TEXTUALLY ~{"AR0308", "Harper's 1st Floor"},~                                                               ~{"AR0308", "(Q)  Domaine des Ménestrels, L1"},~
	REPLACE_TEXTUALLY ~{"AR0309", "Harper's 2nd Floor"},~                                                               ~{"AR0309", "(Q)  Domaine des Ménestrels, L2"},~
	REPLACE_TEXTUALLY ~{"AR0310", "Pirates' Hideout in Sea Bounty Tavern"},~                                            ~{"AR0310", "(Q)  Taverne de la Bonté Marine, Pirates"},~
	REPLACE_TEXTUALLY ~{"AR0311", "Living Room (Entry points outside and up) -- Gaelan?"},~                             ~{"AR0311", "(B-q)  Maison de Gaelan Bayle, L1, (Chapitre 2)"},~
	REPLACE_TEXTUALLY ~{"AR0312", "Sleeping Room (Entry point down) -- Arledrian"},~                                    ~{"AR0312", "(B-q)  Maison de Gaelan Bayle, L2"},~
	REPLACE_TEXTUALLY ~{"AR0313", "Sea Bounty Tavern 1st Floor"},~                                                      ~{"AR0313", "(Q)  Taverne de la Bonté Marine, L1"},~
	REPLACE_TEXTUALLY ~{"AR0314", "Sea Bounty Tavern 2nd Floor"},~                                                      ~{"AR0314", "(Q)  Taverne de la Bonté Marine, L2"},~
	REPLACE_TEXTUALLY ~{"AR0315", "Living Room (Favour for Edwin -- Mae'Var Plot)"},~                                   ~{"AR0315", "(Q)  Maison de Rayic Gethras, L1"},~
	REPLACE_TEXTUALLY ~{"AR0316", "Sleeping Room (Favour for Edwin -- Mae'Var Plot)"},~                                 ~{"AR0316", "(Q)  Maison de Rayic Gethras, L2"},~
	REPLACE_TEXTUALLY ~{"AR0317", "Sleeping Room (Favour for Edwin -- Mae'Var Plot)"},~                                 ~{"AR0317", "(Q)  Maison de Rayic Gethras, L3"},~
	REPLACE_TEXTUALLY ~{"AR0318", "Storage Room"},~                                                                     ~{"AR0318", "(Q)  Entrepôt"},~
	REPLACE_TEXTUALLY ~{"AR0319", "Temple of Oghma"},~                                                                  ~{"AR0319", "(Q)  Temple d’Oghma"},~
	REPLACE_TEXTUALLY ~{"AR0321", "Thief Stronghold (Hideout)"},~                                                       ~{"AR0321", "(Q)  Guilde de Charname, Planque"},~
	REPLACE_TEXTUALLY ~{"AR0322", "Thief Stronghold (1st Floor)"},~                                                     ~{"AR0322", "(Q)  Guilde de Charname, L1"},~
	REPLACE_TEXTUALLY ~{"AR0323", "Thief Stronghold (2nd Floor)"},~                                                     ~{"AR0323", "(Q)  Guilde de Charname, L2"},~
	REPLACE_TEXTUALLY ~{"AR0324", "Thief Stronghold (3rd Floor)"},~                                                     ~{"AR0324", "(Q)  Guilde de Charname, L3"},~
	REPLACE_TEXTUALLY ~{"AR0325", "Corthala House 1st Floor"},~                                                         ~{"AR0325", "(Q)  Maison de Valygar Corthala, L1"},~
	REPLACE_TEXTUALLY ~{"AR0326", "Corthala House 2nd Floor"},~                                                         ~{"AR0326", "(Q)  Maison de Valygar Corthala, L1"},~
	REPLACE_TEXTUALLY ~{"AR0327", "Shadow Thief Entrance (sided with Bodhi)"},~                                         ~{"AR0327", "(Q)  Détruire la Guilde pour Bodhi, L1"},~
	REPLACE_TEXTUALLY ~{"AR0328", "Shadow Thief 1st Floor (sided with Bodhi)"},~                                        ~{"AR0328", "(Q)  Détruire la Guilde pour Bodhi, L2"},~
	REPLACE_TEXTUALLY ~{"AR0329", "Aran's Hideout (sided with Bodhi)"},~                                                ~{"AR0329", "(Q)  Détruire la Guilde pour Bodhi, L3 (Aran Linvail)"},~
	REPLACE_TEXTUALLY ~{"AR0330", "House 1st Floor (Kangaxx)"},~                                                        ~{"AR0330", "(Q)  Maison abandonnée, L1 (Kangaxx)"},~
	REPLACE_TEXTUALLY ~{"AR0331", "House Cellar (Kangaxx)"},~                                                           ~{"AR0331", "(Q)  Maison abandonnée, Cellier (Kangaxx)"},~
	REPLACE_TEXTUALLY ~{"AR0332", "Barracks in the Docks"},~                                                            ~{"AR0332", "(Q)  Caserne, L1"},~
	REPLACE_TEXTUALLY ~{"AR0333", "Barracks in the Docks"},~                                                            ~{"AR0333", "(Q)  Caserne, L2"},~
	REPLACE_TEXTUALLY ~{"AR0334", "Cromwell's Shop"},~                                                                  ~{"AR0334", "(Q)  Forge de Cromwell"},~
	REPLACE_TEXTUALLY ~{"AR0335", "Sleeping Room"},~                                                                    ~{"AR0335", "(Q)  Maison, (Au dessus de la forge)"},~
	REPLACE_TEXTUALLY ~{"AR0400", "Slums"},~                                                                            ~{"AR0400", "  LES BAS QUARTIERS"},~
	REPLACE_TEXTUALLY ~{"AR0401", "Jansen Cellar"},~                                                                    ~{"AR0401", "(B-q)  Maison de la famille Jansen, Cellier"},~
	REPLACE_TEXTUALLY ~{"AR0402", "Jansen 1st Floor"},~                                                                 ~{"AR0402", "(B-q)  Maison de la famille Jansen, L1"},~
	REPLACE_TEXTUALLY ~{"AR0403", "Jansen 2nd Floor"},~                                                                 ~{"AR0403", "(B-q)  Maison de la famille Jansen, L2"},~
	REPLACE_TEXTUALLY ~{"AR0404", "Sewers beneath Coronet -- Lilarcor"},~                                               ~{"AR0404", "(B-q)  Les égouts"},~
	REPLACE_TEXTUALLY ~{"AR0405", "Slaver's Ship Building"},~                                                           ~{"AR0405", "(B-q)  Repaire des esclavagistes"},~
	REPLACE_TEXTUALLY ~{"AR0406", "Copper Coronet"},~                                                                   ~{"AR0406", "(B-q)  La Couronne de Cuivre, (Nalia, Anomen, Clara, Korgan)"},~
	REPLACE_TEXTUALLY ~{"AR0407", "Prebek's House"},~                                                                   ~{"AR0407", "(Q)  Maison de Prebek et Sanasha"},~
	REPLACE_TEXTUALLY ~{"AR0408", "Temple of Ilmater"},~                                                                ~{"AR0408", "(B-q)  Temple d’Ilmater"},~
	REPLACE_TEXTUALLY ~{"AR0409", "Living Room (Ployer's home)"},~                                                      ~{"AR0409", "(B-q)  Maison abandonnée, Baron Ployer"},~
	REPLACE_TEXTUALLY ~{"AR0410", "Sphere: Navigator's room -- Lavok's Hideout"},~                                      ~{"AR0410", "(B-q)  Salle de navigation, (Sphere planaire)"},~
	REPLACE_TEXTUALLY ~{"AR0411", "Sphere: Entrance floor"},~                                                           ~{"AR0411", "(B-q)  Sphere planaire"},~
	REPLACE_TEXTUALLY ~{"AR0412", "Sphere: Ice and Fire Room"},~                                                        ~{"AR0412", "(B-q)  Salle de la Fournaise, (Sphere planaire)"},~
	REPLACE_TEXTUALLY ~{"AR0413", "Sphere: Enginge Room"},~                                                             ~{"AR0413", "(B-q)  Noyau de puissance, (Sphere planaire)"},~
	REPLACE_TEXTUALLY ~{"AR0414", "Sphere: Demon Plane"},~                                                              ~{"AR0414", "(B-q)  Enfer, (Sphere planaire)"},~
	REPLACE_TEXTUALLY ~{"AR0415", "Living Room 1st Floor"},~                                                            ~{"AR0415", "(Q)  Maison, L1 (à gauche de la caserne)"},~
	REPLACE_TEXTUALLY ~{"AR0416", "Living Room 2nd Floor"},~                                                            ~{"AR0416", "(Q)  Maison, L2 (à gauche de la caserne)"},~
	REPLACE_TEXTUALLY ~{"AR0417", "Living Room"},~                                                                      ~{"AR0417", "(B-q)  Maison de Borinall"},~
	REPLACE_TEXTUALLY ~{"AR0418", "Myconids"},~                                                                         ~{"AR0418", "(B-q)  Myconides, (Les égouts)"},~
	REPLACE_TEXTUALLY ~{"AR0419", "Myconid"},~                                                                          ~{"AR0419", "(B-q)  Myconides, (Sphere planaire)"},~
	REPLACE_TEXTUALLY ~{"AR0420", "Sphere: Lizardmen Hideout"},~                                                        ~{"AR0420", "(B-q)  Hommes-Lézard, (Sphere planaire)"},~
	REPLACE_TEXTUALLY ~{"AR0500", "Bridge District"},~                                                                  ~{"AR0500", "  DISTRICT DU PONT"},~
	REPLACE_TEXTUALLY ~{"AR0501", "Tanner's Hideout 1st Floor"},~                                                       ~{"AR0501", "(Pont)  Échoppe du tanneur, L1"},~
	REPLACE_TEXTUALLY ~{"AR0502", "Tanner's Hideout Cellar"},~                                                          ~{"AR0502", "(Pont)  Échoppe du tanneur, Cellier"},~
	REPLACE_TEXTUALLY ~{"AR0503", "Tanner's Hideout Dock"},~                                                            ~{"AR0503", "(Pont)  Échoppe du tanneur, Quais"},~
	REPLACE_TEXTUALLY ~{"AR0504", "Saerk's House 1st Floor"},~                                                          ~{"AR0504", "(Pont)  Domaine Saerk Farrahd, L1"},~
	REPLACE_TEXTUALLY ~{"AR0505", "Saerk's House 2nd Floor"},~                                                          ~{"AR0505", "(Pont)  Domaine Saerk Farrahd, L2"},~
	REPLACE_TEXTUALLY ~{"AR0506", "Noble House 1st Floor"},~                                                            ~{"AR0506", "(Pont)  Domaine Balthis"},~
	REPLACE_TEXTUALLY ~{"AR0507", "Kidnappers' Hideout 1st Floor"},~                                                    ~{"AR0507", "(Pont)  Maison barricadée, L1"},~
	REPLACE_TEXTUALLY ~{"AR0508", "Kidnappers' Hideout 2nd Floor"},~                                                    ~{"AR0508", "(Pont)  Maison barricadée, L2"},~
	REPLACE_TEXTUALLY ~{"AR0509", "Five Flagons Inn 1st Floor"},~                                                       ~{"AR0509", "(Pont)  Auberge des Cinq Chopes, L1"},~
	REPLACE_TEXTUALLY ~{"AR0510", "Five Flagons Inn Theater"},~                                                         ~{"AR0510", "(Pont)  Auberge des Cinq Chopes, Théâtre"},~
	REPLACE_TEXTUALLY ~{"AR0511", "Five Flagons Inn 2nd Floor"},~                                                       ~{"AR0511", "(Pont)  Auberge des Cinq Chopes, L2"},~
	REPLACE_TEXTUALLY ~{"AR0512", "Temple of Helm"},~                                                                   ~{"AR0512", "(Pont)  Temple de Heaum"},~
	REPLACE_TEXTUALLY ~{"AR0513", "Calbor's Inn at Bridge District 1st Floor"},~                                        ~{"AR0513", "(Pont)  Auberge de Delosar, L1"},~
	REPLACE_TEXTUALLY ~{"AR0514", "Inn at Bridge District 2nd Floor"},~                                                 ~{"AR0514", "(Pont)  Auberge de Delosar, L2"},~
	REPLACE_TEXTUALLY ~{"AR0515", "Inn at Bridge District 3rd Floor"},~                                                 ~{"AR0515", "(Pont)  Auberge de Delosar, L3"},~
	REPLACE_TEXTUALLY ~{"AR0516", "Planar Prison"},~                                                                    ~{"AR0516", "(Pont)  Prison Planaire"},~
	REPLACE_TEXTUALLY ~{"AR0517", "Planar Prison Cell"},~                                                               ~{"AR0517", "(Pont)  Cellule des Githyankis, (Prison Planaire)"},~
	REPLACE_TEXTUALLY ~{"AR0518", "Planar Prison Cell"},~                                                               ~{"AR0518", "(Pont)  Cellule des Muloups, (Prison Planaire)"},~
	REPLACE_TEXTUALLY ~{"AR0519", "Planar Prison Cell"},~                                                               ~{"AR0519", "(Pont)  Cellule des Éfrits, (Prison Planaire)"},~
	REPLACE_TEXTUALLY ~{"AR0520", "Planar Prison Cell"},~                                                               ~{"AR0520", "(Pont)  Cellule des Minotaures, (Prison Planaire)"},~
	REPLACE_TEXTUALLY ~{"AR0521", "Planar Prison Cell"},~                                                               ~{"AR0521", "(Pont)  Cellule des Golems, (Prison Planaire)"},~
	REPLACE_TEXTUALLY ~{"AR0522", "Five Flagons Inn (Stronghold)"},~                                                    ~{"AR0522", "(Pont)  Auberge des Cinq Chopes, (Forteresse)"},~
	REPLACE_TEXTUALLY ~{"AR0523", "Five Flagons Theater (Stronghold)"},~                                                ~{"AR0523", "(Pont)  Théâtre, (Forteresse du Barde)"},~
	REPLACE_TEXTUALLY ~{"AR0525", "House 1st Floor"},~                                                                  ~{"AR0525", "(Pont)  Maison, L1 (Liche élémentaire)"},~
	REPLACE_TEXTUALLY ~{"AR0526", "Sarcophagus Cellar"},~                                                               ~{"AR0526", "(Pont)  Sarcophage de la Liche élémentaire"},~
	REPLACE_TEXTUALLY ~{"AR0527", "House 1st Floor"},~                                                                  ~{"AR0527", "(Pont)  Maison du poissonnier, L1"},~
	REPLACE_TEXTUALLY ~{"AR0528", "House 2nd Floor"},~                                                                  ~{"AR0528", "(Pont)  Maison du poissonnier, L2"},~
	REPLACE_TEXTUALLY ~{"AR0529", "Neb's Hideout"},~                                                                    ~{"AR0529", "(Pont)  Planque de Neb"},~
	REPLACE_TEXTUALLY ~{"AR0530", "Storehouse"},~                                                                       ~{"AR0530", "(Pont)  Entrepôt, (Groupe maléfique)"},~
	REPLACE_TEXTUALLY ~{"AR0531", "Commoner House"},~                                                                   ~{"AR0531", "(Pont)  Maison de roturiers"},~
	REPLACE_TEXTUALLY ~{"AR0600", "Circus Tent (phased)"},~                                                             ~{"AR0600", "(W)  Chapiteau, Illusion"},~
	REPLACE_TEXTUALLY ~{"AR0601", "Air Plane in Irenicus's Dungeon"},~                                                  ~{"AR0601", "(W)  Donjon d'Irenicus, Plan de l'air"},~
	REPLACE_TEXTUALLY ~{"AR0602", "Irenicus's Dungeon 1st Floor"},~                                                     ~{"AR0602", "(W)  Donjon d'Irenicus, L1 (Imoen, Jaheira, Minsc)"},~
	REPLACE_TEXTUALLY ~{"AR0603", "Irenicus's Dungeon 2nd Floor"},~                                                     ~{"AR0603", "(W)  Donjon d'Irenicus, L2 (Yoshimo)"},~
	REPLACE_TEXTUALLY ~{"AR0604", "Circus Tent 1st Floor"},~                                                            ~{"AR0604", "(W)  Chapiteau, Illusion L1, (Aerie)"},~
	REPLACE_TEXTUALLY ~{"AR0605", "Circus Tent 2nd Floor"},~                                                            ~{"AR0605", "(W)  Chapiteau, Illusion L2"},~
	REPLACE_TEXTUALLY ~{"AR0606", "Circus Tent 3rd Floor"},~                                                            ~{"AR0606", "(W)  Chapiteau, Illusion L3, (Kalah)"},~
	REPLACE_TEXTUALLY ~{"AR0607", "Circus Tent restored"},~                                                             ~{"AR0607", "(W)  Le Chapiteau, (Quayle)"},~
	REPLACE_TEXTUALLY ~{"AR0700", "Waukeen's Promenade"},~                                                              ~{"AR0700", "  LA PROMENADE DE WAUKYNE"},~
	REPLACE_TEXTUALLY ~{"AR0701", "The Sewers"},~                                                                       ~{"AR0701", "(D-t)  Les égouts"},~
	REPLACE_TEXTUALLY ~{"AR0702", "Adventurer's Mart"},~                                                                ~{"AR0702", "(W)  Le Marché de l'Aventurier"},~
	REPLACE_TEXTUALLY ~{"AR0703", "Temple of Ilmater"},~                                                                ~{"AR0703", "(W)  Temple d'Ilmater"},~
	REPLACE_TEXTUALLY ~{"AR0704", "Mithrest Inn"},~                                                                     ~{"AR0704", "(W)  Auberge du Bonrepos (Mithrest)"},~
	REPLACE_TEXTUALLY ~{"AR0705", "Mekrath's Hideout in the Sewers (Haer'Dalis Plot)"},~                                ~{"AR0705", "(D-t)  Planque de Mekrath, égouts, (Haer'Dalis)"},~
	REPLACE_TEXTUALLY ~{"AR0706", "Armourer/Fletcher"},~                                                                ~{"AR0706", "(W)  Armurier / Fabricant de flèches"},~
	REPLACE_TEXTUALLY ~{"AR0707", "Enge's Shop"},~                                                                      ~{"AR0707", "(W)  Échoppe d'Enge"},~
	REPLACE_TEXTUALLY ~{"AR0708", "Cernd's former home"},~                                                              ~{"AR0708", "(W)  Maison de Cernd"},~
	REPLACE_TEXTUALLY ~{"AR0709", "Den of the Seven Vales 1st Floor"},~                                                 ~{"AR0709", "(W)  Antre des Sept Vaux, L1"},~
	REPLACE_TEXTUALLY ~{"AR0710", "Fennecia's Home"},~                                                                  ~{"AR0710", "(W)  Maison de Fennecia"},~
	REPLACE_TEXTUALLY ~{"AR0711", "Illithid Hideout in the Sewers (The Hidden Plot)"},~                                 ~{"AR0711", "(D-t)  Planque des Illithids, (égouts)"},~
	REPLACE_TEXTUALLY ~{"AR0712", "Den of the Seven Vales 2nd Floor"},~                                                 ~{"AR0712", "(W)  Antre des Sept Vaux, L2"},~
	REPLACE_TEXTUALLY ~{"AR0713", "Store or Inn at Promenade"},~                                                        ~{"AR0713", "(W)  Restaurant, (Au dessus de la maison de Cernd)"},~
	REPLACE_TEXTUALLY ~{"AR0714", "Debris at Waukeen's Promenade (Irenicus Cutscene in the beginning)"},~               ~{"AR0714", "(Ciné)  Irenicus à la promenade de Waukyne"},~
	REPLACE_TEXTUALLY ~{"AR0800", "Graveyard"},~                                                                        ~{"AR0800", "  DISTRICT DU CIMETIÈRE"},~
	REPLACE_TEXTUALLY ~{"AR0801", "Bodhi's Hideout (sided with Aran)"},~                                                ~{"AR0801", "(C)  Catacombes,(Détruire la Guilde pour Aran)"},~
	REPLACE_TEXTUALLY ~{"AR0802", "Netherscroll, Korgan's Book, Edwin"},~                                               ~{"AR0802", "(C)  Catacombes, (Parchemin Néthère, Livre de Kaza)"},~
	REPLACE_TEXTUALLY ~{"AR0803", "Bodhi's Lair (sided with Aran)"},~                                                   ~{"AR0803", "(C)  Antre de Bodhi, (Détruire la Guilde pour Aran)"},~
	REPLACE_TEXTUALLY ~{"AR0804", "Pai'Na's Hideout"},~                                                                 ~{"AR0804", "(C)  Bosquet de Pai'Na"},~
	REPLACE_TEXTUALLY ~{"AR0805", "Crypt"},~                                                                            ~{"AR0805", "(C)  Crypte, Nord"},~
	REPLACE_TEXTUALLY ~{"AR0806", "Crypt"},~                                                                            ~{"AR0806", "(C)  Crypte, (Roi de la crypte)"},~
	REPLACE_TEXTUALLY ~{"AR0807", "Crypt"},~                                                                            ~{"AR0807", "(C)  Crypte, Est"},~
	REPLACE_TEXTUALLY ~{"AR0808", "Bodhi's Hideout (Abduction Plot, getting Imoen's soul)"},~                           ~{"AR0808", "(C)  Catacombes, (L'Âme d'Imoen, Romance)"},~
	REPLACE_TEXTUALLY ~{"AR0809", "Bodhi's Lair (Abduction Plot, getting Imoen's soul)"},~                              ~{"AR0809", "(C)  Antre de Bodhi, (L'Âme d'Imoen, Romance)"},~
	REPLACE_TEXTUALLY ~{"AR0810", "Crypt"},~                                                                            ~{"AR0810", "(C)  Crypte, Sud"},~
	REPLACE_TEXTUALLY ~{"AR0811", "Crypt"},~                                                                            ~{"AR0811", "(C)  Crypte, Sud-Est"},~
	REPLACE_TEXTUALLY ~{"AR0812", "Crypt"},~                                                                            ~{"AR0812", "(C)  Crypte 1 centrale"},~
	REPLACE_TEXTUALLY ~{"AR0813", "Crypt"},~                                                                            ~{"AR0813", "(C)  Crypte 2 centrale"},~
	REPLACE_TEXTUALLY ~{"AR0900", "Temple District"},~                                                                  ~{"AR0900", "  DISTRICT DU TEMPLE"},~
	REPLACE_TEXTUALLY ~{"AR0901", "Temple of Helm"},~                                                                   ~{"AR0901", "(D-t)  Temple de Heaum"},~
	REPLACE_TEXTUALLY ~{"AR0902", "Temple of Lathander"},~                                                              ~{"AR0902", "(D-t)  Temple de Lathandre"},~
	REPLACE_TEXTUALLY ~{"AR0903", "Order of the Radiant Heart"},~                                                       ~{"AR0903", "(D-t)  Ordre du Cœur Radieux"},~
	REPLACE_TEXTUALLY ~{"AR0904", "Temple of Talos"},~                                                                  ~{"AR0904", "(D-t)  Temple de Talos"},~
	REPLACE_TEXTUALLY ~{"AR0905", "Pimlico's Estate"},~                                                                 ~{"AR0905", "(D-t)  Domaine Pimlico"},~
	REPLACE_TEXTUALLY ~{"AR0906", "Guarded Compound 1st Floor"},~                                                       ~{"AR0906", "(D-t)  Cour gardée, L1"},~
	REPLACE_TEXTUALLY ~{"AR0907", "Guarded Compound 2nd Floor"},~                                                       ~{"AR0907", "(D-t)  Cour gardée, L2"},~
	REPLACE_TEXTUALLY ~{"AR1000", "Government District"},~                                                              ~{"AR1000", "  DISTRICT DU GOUVERNEMENT"},~
	REPLACE_TEXTUALLY ~{"AR1001", "Delryn's Estate"},~                                                                  ~{"AR1001", "(G)  Domaine Delryn"},~
	REPLACE_TEXTUALLY ~{"AR1002", "Councel Building"},~                                                                 ~{"AR1002", "(G)  Bâtiment du Conseil des Six"},~
	REPLACE_TEXTUALLY ~{"AR1003", "Firecam's Estate"},~                                                                 ~{"AR1003", "(G)  Domaine Firecam"},~
	REPLACE_TEXTUALLY ~{"AR1004", "Deril's Estate (Cernd Plot)"},~                                                      ~{"AR1004", "(G)  Domaine Deril, (Quête de Cernd)"},~
	REPLACE_TEXTUALLY ~{"AR1005", "Prison"},~                                                                           ~{"AR1005", "(G)  Prison"},~
	REPLACE_TEXTUALLY ~{"AR1006", "Jysstev's Estate (Oisig Plot)"},~                                                    ~{"AR1006", "(G)  Domaine Jysstev, (Quête du prêtre)"},~
	REPLACE_TEXTUALLY ~{"AR1007", "Noble House"},~                                                                      ~{"AR1007", "(G)  Maison, Nord"},~
	REPLACE_TEXTUALLY ~{"AR1008", "Twisted Rune"},~                                                                     ~{"AR1008", "(Pont)  Rune Tordue"},~
	REPLACE_TEXTUALLY ~{"AR1009", "Noble House (Isaea Roenall's)"},~                                                    ~{"AR1009", "(G)  Maison d'Isaea Roenall"},~
	REPLACE_TEXTUALLY ~{"AR1010", "Temple of Waukeen"},~                                                                ~{"AR1010", "(G)  Temple de Waukyne"},~
	REPLACE_TEXTUALLY ~{"AR1100", "Umar Hills"},~                                                                       ~{"AR1100", "(Imn)  Collines d'Umar"},~
	REPLACE_TEXTUALLY ~{"AR1101", "Valygar's Cabin"},~                                                                  ~{"AR1101", "(Imn)  Cabane de Valygar"},~
	REPLACE_TEXTUALLY ~{"AR1102", "Merella's Cabin"},~                                                                  ~{"AR1102", "(Imn)  Cabane de Merella"},~
	REPLACE_TEXTUALLY ~{"AR1103", "Jermien's Cabin"},~                                                                  ~{"AR1103", "(Imn)  Maison de Jermien"},~
	REPLACE_TEXTUALLY ~{"AR1104", "Mayor Lloyd's Cabin"},~                                                              ~{"AR1104", "(Imn)  Maison du maire Lloyd"},~
	REPLACE_TEXTUALLY ~{"AR1105", "Imnesvale Inn"},~                                                                    ~{"AR1105", "(Imn)  Auberge d'Imnesvale"},~
	REPLACE_TEXTUALLY ~{"AR1106", "Umar's Cave"},~                                                                      ~{"AR1106", "(Imn)  Grotte d'Umar"},~
	REPLACE_TEXTUALLY ~{"AR1107", "Ranger-Protector's Cabin (Stronghold)"},~                                            ~{"AR1107", "(Imn)  Forteresse du rôdeur"},~
	REPLACE_TEXTUALLY ~{"AR1200", "Windspear Hills"},~                                                                  ~{"AR1200", "(C-L)  Collines de Lancevent"},~
	REPLACE_TEXTUALLY ~{"AR1201", "Firkraag's Entrance"},~                                                              ~{"AR1201", "(C-L)  Donjon de Firkraag, Entrée"},~
	REPLACE_TEXTUALLY ~{"AR1202", "Firkraag's Maze"},~                                                                  ~{"AR1202", "(C-L)  Donjon de Firkraag, , Labyrinthe"},~
	REPLACE_TEXTUALLY ~{"AR1203", "Firkraag's Hideout"},~                                                               ~{"AR1203", "(C-L)  Tanière de Firkraag"},~
	REPLACE_TEXTUALLY ~{"AR1204", "Garren Windspear's Cabin"},~                                                         ~{"AR1204", "(C-L)  Cabane de Garren Lancevent"},~
	REPLACE_TEXTUALLY ~{"AR1300", "De'Arnise Keep Destroyed"},~                                                         ~{"AR1300", "(Arn)  Forteresse De'Arnise, (Assiégée)"},~
	REPLACE_TEXTUALLY ~{"AR1301", "De'Arnise Cellar"},~                                                                 ~{"AR1301", "(Arn)  Sous-sols De'Arnise, (Torgal)"},~
	REPLACE_TEXTUALLY ~{"AR1302", "De'Arnise Keep 1st Floor"},~                                                         ~{"AR1302", "(Arn)  Forteresse De'Arnise, L1"},~
	REPLACE_TEXTUALLY ~{"AR1303", "De'Arnise Keep 2nd Floor (Destroyed)"},~                                             ~{"AR1303", "(Arn)  Forteresse De'Arnise, L2"},~
	REPLACE_TEXTUALLY ~{"AR1304", "De'Arnise Keep (Restored, Stronghold)"},~                                            ~{"AR1304", "(Arn)  Forteresse De'Arnise, (Libérée)"},~
	REPLACE_TEXTUALLY ~{"AR1305", "De'Arnise Keep (Stronghold)"},~                                                      ~{"AR1305", "(Arn)  Forteresse du guerrier, Sous-sols"},~
	REPLACE_TEXTUALLY ~{"AR1306", "De'Arnise Keep (Stronghold)"},~                                                      ~{"AR1306", "(Arn)  Forteresse du guerrier, L1"},~
	REPLACE_TEXTUALLY ~{"AR1307", "De'Arnise Keep (Stronghold)"},~                                                      ~{"AR1307", "(Arn)  Forteresse du guerrier, L2"},~
	REPLACE_TEXTUALLY ~{"AR1400", "Shadow Temple Land (restored, Ranger)"},~                                            ~{"AR1400", "(Um)  Ruines du temple (Illuminé)"},~
	REPLACE_TEXTUALLY ~{"AR1401", "Shadow Temple"},~                                                                    ~{"AR1401", "(Um)  Donjon du Temple"},~
	REPLACE_TEXTUALLY ~{"AR1402", "Shadow Dragon Hideout"},~                                                            ~{"AR1402", "(Um)  Tanière de Thaxll'ssillyia"},~
	REPLACE_TEXTUALLY ~{"AR1403", "Wolfwere Hideout"},~                                                                 ~{"AR1403", "(Um)  Grotte du loup, (Anath)"},~
	REPLACE_TEXTUALLY ~{"AR1404", "Shadow Temple Land shadowed"},~                                                      ~{"AR1404", "(Um)  Ruines du temple, (Ténèbre)"},~
	REPLACE_TEXTUALLY ~{"AR1500", "Spellhold"},~                                                                        ~{"AR1500", "(SP)  Asile de Spellhold"},~
	REPLACE_TEXTUALLY ~{"AR1501", "Cave (Spellhold Test)"},~                                                            ~{"AR1501", "(SP)  Salle de la terre (Jugement)"},~
	REPLACE_TEXTUALLY ~{"AR1502", "Fire Room (Spellhold Test)"},~                                                       ~{"AR1502", "(SP)  Salle du feu, (Jugement)"},~
	REPLACE_TEXTUALLY ~{"AR1503", "Spore Room (Spellhold Test)"},~                                                      ~{"AR1503", "(SP)  Salle des spores, (Jugement)"},~
	REPLACE_TEXTUALLY ~{"AR1504", "Crushing Trap Room (Spellhold Test)"},~                                              ~{"AR1504", "(SP)  Salle piégée (Jugement)"},~
	REPLACE_TEXTUALLY ~{"AR1505", "Lever Room (Spellhold Test)"},~                                                      ~{"AR1505", "(SP)  Salle des leviers (Jugement)"},~
	REPLACE_TEXTUALLY ~{"AR1506", "Troll Cave (Spellhold Test)"},~                                                      ~{"AR1506", "(SP)  Salle des Trolls, (Jugement)"},~
	REPLACE_TEXTUALLY ~{"AR1507", "Kobold Room (Spellhold Test)"},~                                                     ~{"AR1507", "(SP)  Salle des Kobolds, (Jugement)"},~
	REPLACE_TEXTUALLY ~{"AR1508", "Final Judgement Spellhold Test"},~                                                   ~{"AR1508", "(SP)  Jugement Final"},~
	REPLACE_TEXTUALLY ~{"AR1509", "Myconid Room (Spellhold Test)"},~                                                    ~{"AR1509", "(SP)  Salle des Myconides, (Jugement)"},~
	REPLACE_TEXTUALLY ~{"AR1510", "Sahuagin Room (Spellhold Test)"},~                                                   ~{"AR1510", "(SP)  Salle des Sahuagins, (Jugement)"},~
	REPLACE_TEXTUALLY ~{"AR1511", "Elven Table while Spellhold Test"},~                                                 ~{"AR1511", "(SP)  Dîner (Jugement)"},~
	REPLACE_TEXTUALLY ~{"AR1512", "Bodhi's Hunt Level 1"},~                                                             ~{"AR1512", "(SP)  Le Vampire et l'Enfant, L1 (Imoen)"},~
	REPLACE_TEXTUALLY ~{"AR1513", "Bodhi's Hunt Level 2"},~                                                             ~{"AR1513", "(SP)  Le Vampire et l'Enfant, L2"},~
	REPLACE_TEXTUALLY ~{"AR1514", "Bodhi's Hunt Level 3 (1st Slayer Change Happens here)"},~                            ~{"AR1514", "(SP)  Le Vampire et l'Enfant, L3 (L'Écorcheur)"},~
	REPLACE_TEXTUALLY ~{"AR1515", "Spellhold (Irenicus's Living Room)"},~                                               ~{"AR1515", "(SP)  Asile de Spellhold, L1 (Coordinateur) "},~
	REPLACE_TEXTUALLY ~{"AR1516", "Spellhold (Soultheft Level)"},~                                                      ~{"AR1516", "(SP)  Asile de Spellhold, L2 (Rituel)"},~
	REPLACE_TEXTUALLY ~{"AR1600", "Brynnlaw"},~                                                                         ~{"AR1600", "  BRYNNLAW"},~
	REPLACE_TEXTUALLY ~{"AR1601", "Desharik's Estate"},~                                                                ~{"AR1601", "(Bry)  Demeure de Desharik"},~
	REPLACE_TEXTUALLY ~{"AR1602", "Brynnlaw's Inn"},~                                                                   ~{"AR1602", "(Bry)  Auberge du Singe vulgaire"},~
	REPLACE_TEXTUALLY ~{"AR1603", "Brynnlaw's Shop"},~                                                                  ~{"AR1603", "(Bry)  Magasin"},~
	REPLACE_TEXTUALLY ~{"AR1604", "Temple of Umberlee"},~                                                               ~{"AR1604", "(Bry)  Temple d'Umberlee"},~
	REPLACE_TEXTUALLY ~{"AR1605", "CW's House"},~                                                                       ~{"AR1605", "(Bry)  Maison de Perth l'adepte"},~
	REPLACE_TEXTUALLY ~{"AR1606", "House of Desharik's Lover"},~                                                        ~{"AR1606", "(Bry)  Maison de Cayia"},~
	REPLACE_TEXTUALLY ~{"AR1607", "Githyanki Assault"},~                                                                ~{"AR1607", "(MER)  L'assaut des Githyanki"},~
	REPLACE_TEXTUALLY ~{"AR1608", "Cellar of Brothel"},~                                                                ~{"AR1608", "(Bry)  Passage de la Maison Close"},~
	REPLACE_TEXTUALLY ~{"AR1609", "Courtesan Room"},~                                                                   ~{"AR1609", "(Bry)  Chambre à Coucher"},~
	REPLACE_TEXTUALLY ~{"AR1610", "Brothel Prison"},~                                                                   ~{"AR1610", "(Bry)  Prison de la Maison Close"},~
	REPLACE_TEXTUALLY ~{"AR1611", "Brothel"},~                                                                          ~{"AR1611", "(Bry)  Entrée de la Maison Close"},~
	REPLACE_TEXTUALLY ~{"AR1612", "Brothel Kitchen"},~                                                                  ~{"AR1612", "(Bry)  Cuisine de la Maison Close"},~
	REPLACE_TEXTUALLY ~{"AR1613", "Brothel HQ"},~                                                                       ~{"AR1613", "(Bry)  Chambre à Coucher, (Capitaine Rerdes)"},~
	REPLACE_TEXTUALLY ~{"AR1700", "Small Teeth Pass"},~                                                                 ~{"AR1700", "(Amn)  Passe du Petit Croc"},~
	REPLACE_TEXTUALLY ~{"AR1800", "North Forest"},~                                                                     ~{"AR1800", "(Amn)  Forêt de nord"},~
	REPLACE_TEXTUALLY ~{"AR1900", "Druid Grove Area"},~                                                                 ~{"AR1900", "(B-d)  Bosquet des druides"},~
	REPLACE_TEXTUALLY ~{"AR1901", "Druid Grove"},~                                                                      ~{"AR1901", "(B-d)  Bosquet, (Faldorn)"},~
	REPLACE_TEXTUALLY ~{"AR1902", "Storehouse (Ihtafeer's Storehouse)"},~                                               ~{"AR1902", "(B-d)  Marchande de potions, (Ihtafeer)"},~
	REPLACE_TEXTUALLY ~{"AR1904", "Troll Hill"},~                                                                       ~{"AR1904", "(B-d)  Tertre aux trolls"},~
	REPLACE_TEXTUALLY ~{"AR1905", "Store Tower"},~                                                                      ~{"AR1905", "(B-d)  Tour de l'ogre"},~
	REPLACE_TEXTUALLY ~{"AR2000", "Trademeet"},~                                                                        ~{"AR2000", "  FRANC-MARCHÉ"},~
	REPLACE_TEXTUALLY ~{"AR2001", "The Smithy"},~                                                                       ~{"AR2001", "(F-M)  Forgeron"},~
	REPLACE_TEXTUALLY ~{"AR2002", "Fentan's House"},~                                                                   ~{"AR2002", "(F-M)  Maison Fentan"},~
	REPLACE_TEXTUALLY ~{"AR2006", "Tiri's Home"},~                                                                      ~{"AR2006", "(F-M)  Maison de Tiri"},~
	REPLACE_TEXTUALLY ~{"AR2007", "High Merchant's Estate"},~                                                           ~{"AR2007", "(F-M)  Domaine du Haut Marchand, (Logan Coprith)"},~
	REPLACE_TEXTUALLY ~{"AR2008", "Temple of Waukeen"},~                                                                ~{"AR2008", "(F-M)  Temple de Waukyne"},~
	REPLACE_TEXTUALLY ~{"AR2009", "High Merchant Prison"},~                                                             ~{"AR2009", "(F-M)  Prison de Franc-Marché"},~
	REPLACE_TEXTUALLY ~{"AR2010", "Trademeet's Inn"},~                                                                  ~{"AR2010", "(F-M)  Taverne de Vyatri"},~
	REPLACE_TEXTUALLY ~{"AR2011", "Alibakkar's Estate"},~                                                               ~{"AR2011", "(F-M)  Domaine Alibakkar"},~
	REPLACE_TEXTUALLY ~{"AR2012", "Lurraxol's Estate"},~                                                                ~{"AR2012", "(F-M)  Domaine Lurraxol"},~
	REPLACE_TEXTUALLY ~{"AR2013", "Trademeet Crypt"},~                                                                  ~{"AR2013", "(F-M)  Crypte de Franc-Marché"},~
	REPLACE_TEXTUALLY ~{"AR2014", "Djinni's Tent"},~                                                                    ~{"AR2014", "(F-M)  Tente des djinns"},~
	REPLACE_TEXTUALLY ~{"AR2015", "Merchant Tent"},~                                                                    ~{"AR2015", "(F-M)  Tente du marchand"},~
	REPLACE_TEXTUALLY ~{"AR2016", "Raffee's Tent"},~                                                                    ~{"AR2016", "(F-M)  Tente de Raffee"},~
	REPLACE_TEXTUALLY ~{"AR2017", "Courtesan Tent"},~                                                                   ~{"AR2017", "(F-M)  Tente de Madame Jeanne"},~
	REPLACE_TEXTUALLY ~{"AR2018", "Tent (no exit)"},~                                                                   ~{"AR2018", "(CLUA)  Tente"},~
	REPLACE_TEXTUALLY ~{"AR2100", "Underdark"},~                                                                        ~{"AR2100", "(O-T)  Ombre-Terre, (Chapitre 5)"},~
	REPLACE_TEXTUALLY ~{"AR2101", "Beholder Cave in Underdark"},~                                                       ~{"AR2101", "(O-T)  Tunnels du sud, (Orbe ancien)"},~
	REPLACE_TEXTUALLY ~{"AR2102", "Adalon's Cave"},~                                                                    ~{"AR2102", "(O-T)  Tanière d'Adalon"},~
	REPLACE_TEXTUALLY ~{"AR2200", "Ust Natha"},~                                                                        ~{"AR2200", "  UST NATHA"},~
	REPLACE_TEXTUALLY ~{"AR2201", "Temple in Ust Natha"},~                                                              ~{"AR2201", "(O-T)  Temple de Lolth"},~
	REPLACE_TEXTUALLY ~{"AR2202", "Inn in Ust Natha 1st Floor"},~                                                       ~{"AR2202", "(O-T)  Taverne d'Ust Natha, L1"},~
	REPLACE_TEXTUALLY ~{"AR2203", "Inn in Ust Natha; 2nd Floor"},~                                                      ~{"AR2203", "(O-T)  Taverne d'Ust Natha, L1"},~
	REPLACE_TEXTUALLY ~{"AR2204", "House in Ust Natha"},~                                                               ~{"AR2204", "(O-T)  Société des Combattantes"},~
	REPLACE_TEXTUALLY ~{"AR2205", "House in Ust Natha"},~                                                               ~{"AR2205", "(O-T)  Société des Combattants"},~
	REPLACE_TEXTUALLY ~{"AR2206", "Qilue's House in Ust Natha"},~                                                       ~{"AR2206", "(O-T)  Demeure de Qilue"},~
	REPLACE_TEXTUALLY ~{"AR2207", "Deirex's Tower in Ust Natha"},~                                                      ~{"AR2207", "(O-T)  Tour de Deirex"},~
	REPLACE_TEXTUALLY ~{"AR2208", "Jarlaxle's House wherever"},~                                                        ~{"AR2208", "(O-T)  Planque de Jarlaxle"},~
	REPLACE_TEXTUALLY ~{"AR2209", "Jae'llat's House"},~                                                                 ~{"AR2209", "(O-T)  Demeure Jae'llat"},~
	REPLACE_TEXTUALLY ~{"AR2210", "Deirex's Cave"},~                                                                    ~{"AR2210", "(O-T)  Tour de Deirex, Sous-sol"},~
	REPLACE_TEXTUALLY ~{"AR2300", "Sahuagin City"},~                                                                    ~{"AR2300", "(MER)  La cité des Sahuagins"},~
	REPLACE_TEXTUALLY ~{"AR2400", "Mind Flayers in Underdark"},~                                                        ~{"AR2400", "(O-T)  Tunnels de l'est, Maître-Cerveau"},~
	REPLACE_TEXTUALLY ~{"AR2401", "Cave Between Underdark and Exit from Underdark"},~                                   ~{"AR2401", "(O-T)  Vers la surface"},~
	REPLACE_TEXTUALLY ~{"AR2402", "Kuo Toa in Underdark"},~                                                             ~{"AR2402", "(O-T)  Tunnels de l'ouest, Prince Kuo-Toa"},~
	REPLACE_TEXTUALLY ~{"AR2500", "Elven Temple at Underdark Exit"},~                                                   ~{"AR2500", "(Amn)  Sortie de l'ombre-terre, (Elhan, Chapitre 6)"},~
	REPLACE_TEXTUALLY ~{"AR2600", "Thetyr Wood"},~                                                                      ~{"AR2600", "(Amn)  Forêt de Téthyr, (Safana, Coran)"},~
	REPLACE_TEXTUALLY ~{"AR2601", "Meet Drizzt Do'Urden"},~                                                             ~{"AR2601", "  Aléatoire, Drizzt Do'Urden"},~
	REPLACE_TEXTUALLY ~{"AR2602", "Cave in Woods to Suldanessellar"},~                                                  ~{"AR2602", "(Amn)  Cave dans la Forêt de Téthyr"},~
	REPLACE_TEXTUALLY ~{"AR2603", "Coran's Cabin"},~                                                                    ~{"AR2603", "(Amn)  Cabane de Coran"},~
	REPLACE_TEXTUALLY ~{"AR2700", "Ancient Spirits?"},~                                                                 ~{"AR2700", "(CLUA)  Zone Boisée / Têtes de pierre"},~
	REPLACE_TEXTUALLY ~{"AR2800", "Suldanessellar"},~                                                                   ~{"AR2800", "  SULDANESSELLAR, (Chapitre 7)"},~
	REPLACE_TEXTUALLY ~{"AR2801", "House of High Priestess of Suldanessellar"},~                                        ~{"AR2801", "(Sun)  Maison de la grande prêtresse Demin"},~
	REPLACE_TEXTUALLY ~{"AR2802", "House in Suldanessellar"},~                                                          ~{"AR2802", "(Sun)  Maison de la Corne"},~
	REPLACE_TEXTUALLY ~{"AR2803", "Rillifane Temple"},~                                                                 ~{"AR2803", "(Sun)  Temple de Rillifane, (Suneer)"},~
	REPLACE_TEXTUALLY ~{"AR2804", "To the Tree of Life (Entrance Hidden)"},~                                            ~{"AR2804", "(Sun)  Vers L'Arbre de Vie (Entrée cachée)"},~
	REPLACE_TEXTUALLY ~{"AR2805", "To the Tree of Life (Entrance Revealed)"},~                                          ~{"AR2805", "(Sun)  Vers L'Arbre de Vie (Entrée révélée)"},~
	REPLACE_TEXTUALLY ~{"AR2806", "Tree of Life"},~                                                                     ~{"AR2806", "(Sun)  L'Arbre de Vie"},~
	REPLACE_TEXTUALLY ~{"AR2807", "Black Dragon's Hideout"},~                                                           ~{"AR2807", "(Sun)  Tanière de Nizidramanii'yt"},~
	REPLACE_TEXTUALLY ~{"AR2808", "House in Suldanessellar"},~                                                          ~{"AR2808", "(Sun)  Maison de la Lune"},~
	REPLACE_TEXTUALLY ~{"AR2809", "House in Suldanessellar - Puzzle Box"},~                                             ~{"AR2809", "(Sun)  Maison du talisman, Énigme"},~
	REPLACE_TEXTUALLY ~{"AR2810", "House in Suldanessellar"},~                                                          ~{"AR2810", "(Sun)  Maison du prêtre"},~
	REPLACE_TEXTUALLY ~{"AR2811", "House in Suldanessellar"},~                                                          ~{"AR2811", "(Sun)  Maison du harpiste"},~
	REPLACE_TEXTUALLY ~{"AR2812", "Temple of Rillifane after the Battle"},~                                             ~{"AR2812", "(Sun)  Temple de Rillifane / Fin de SoA"},~
	REPLACE_TEXTUALLY ~{"AR2900", "The Abyss"},~                                                                        ~{"AR2900", "(SoA)  Les Abysses / Fin de SoA"},~
	REPLACE_TEXTUALLY ~{"AR2901", "Fear (Abyss)"},~                                                                     ~{"AR2901", "(SoA)  Peur, Larme de Bhaal"},~
	REPLACE_TEXTUALLY ~{"AR2902", "Pride (Abyss)"},~                                                                    ~{"AR2902", "(SoA)  Fierté, Larme de Bhaal"},~
	REPLACE_TEXTUALLY ~{"AR2903", "Greed (Abyss)"},~                                                                    ~{"AR2903", "(SoA)  Cupidité, Larme de Bhaal"},~
	REPLACE_TEXTUALLY ~{"AR2904", "Selfish (Abyss)"},~                                                                  ~{"AR2904", "(SoA)  Égoïste, Larme de Bhaal"},~
	REPLACE_TEXTUALLY ~{"AR2905", "Sarevok (Abyss)"},~                                                                  ~{"AR2905", "(SoA)  Colère, Larme de Bhaal"},~
	REPLACE_TEXTUALLY ~{"AR2906", "Jon Battle ?"},~                                                                     ~{"AR2906", "Néant"},~
	REPLACE_TEXTUALLY ~{"OH4000", "Rasaad - The Amphitheater"},~                                                        ~{"OH4000", "(SoA)  Amphithéâtre abandonné, Quête de Rasaad"},~
	REPLACE_TEXTUALLY ~{"OH4010", "Rasaad - Tears of Selune battle encounter"},~                                        ~{"OH4010", "(SoA)  Les Larmes de Séluné, Quête de Rasaad"},~
	REPLACE_TEXTUALLY ~{"OH4100", "Rasaad - Dark Moon Heretic Temple"},~                                                ~{"OH4100", "(SoA)  Temple des hérétiques, Quête de Rasaad"},~
	REPLACE_TEXTUALLY ~{"OH4101", "Rasaad - Dark Moon Heretic Temple Interior"},~                                       ~{"OH4101", "(SoA)  Intérieur du temple, Quête de Rasaad"},~
	REPLACE_TEXTUALLY ~{"OH5000", "Dorn - Radiant Heart (Wedding)"},~                                                   ~{"OH5000", "(SoA)  Le mariage au Cœur Radieux, Quête de Dorn"},~
	REPLACE_TEXTUALLY ~{"OH5100", "Dorn - Resurrection Gorge"},~                                                        ~{"OH5100", "(SoA)  Gorge de la Résurrection, Quête de Dorn"},~
	REPLACE_TEXTUALLY ~{"OH5110", "Dorn - Resurrection Gorge Cave"},~                                                   ~{"OH5110", "(SoA)  Caverne de la Résurrection, Quête de Dorn"},~
	REPLACE_TEXTUALLY ~{"OH5120", "Dorn - Resurrection Gorge Tree Interior"},~                                          ~{"OH5120", "(SoA)  Arbre de la Résurrection, Quête de Dorn"},~
	REPLACE_TEXTUALLY ~{"OH5200", "Dorn - Resurrection Gorge Interior"},~                                               ~{"OH5200", "(SoA)  Rivière de la Résurrection, Quête de Dorn"},~
	REPLACE_TEXTUALLY ~{"OH5300", "Dorn - Helmite Camp"},~                                                              ~{"OH5300", "(SoA)  Camp heaumite, Quête de Dorn"},~
	REPLACE_TEXTUALLY ~{"OH6000", "Neera - The Wild Forest"},~                                                          ~{"OH6000", "(SoA)  Forêt Sauvage, Quête de Neera"},~
	REPLACE_TEXTUALLY ~{"OH6010", "Neera - Random Encounter in Athkatla"},~                                             ~{"OH6010", "(SoA)  Rencontre aléatoire avec Neera"},~
	REPLACE_TEXTUALLY ~{"OH6100", "Neera - The Hidden Refuge"},~                                                        ~{"OH6100", "(SoA)  Le Refuge Caché, Quête de Neera"},~
	REPLACE_TEXTUALLY ~{"OH6200", "Neera - The Hidden Refuge (Destroyed)"},~                                            ~{"OH6200", "(SoA)  Le Refuge détruit, Quête de Neera"},~
	REPLACE_TEXTUALLY ~{"OH6300", "Neera - Red Wizard Enclave"},~                                                       ~{"OH6300", "(SoA)  Enclave des Sorciers Rouges, Quête de Neera"},~
	REPLACE_TEXTUALLY ~{"OH7000", "Hexxat - Top Left Quarter (Dragomir)"},~                                             ~{"OH7000", "(SoA)  Tombe de Dragomir, Quête de Hexxat"},~
	REPLACE_TEXTUALLY ~{"OH7100", "Hexxat - Bottom Left Quarter (Shou Lung)"},~                                         ~{"OH7100", "(SoA)  Tombe inférieur Ouest, Quête de Hexxat"},~
	REPLACE_TEXTUALLY ~{"OH7200", "Hexxat - Bottom Right Quarter (Zakhara)"},~                                          ~{"OH7200", "(SoA)  Tombe inférieur Est, Quête de Hexxat"},~
	
	// CheatsAreas pour Les Gladiateurs de Thay                                                                         
																														
	REPLACE_TEXTUALLY ~{"OH8000", "TBP2 - Suzail Tavern"},~                                                             ~{"OH8000", "(FN2)  Comptoir de Suzail"},~
	REPLACE_TEXTUALLY ~{"OH8100", "TBP2 - Staging Area Map"},~                                                          ~{"OH8100", "(FN2)  Zone de repos"},~
	REPLACE_TEXTUALLY ~{"OH8200", "TBP2 - Arena 1"},~                                                                   ~{"OH8200", "(FN2)  Arène 1"},~
	REPLACE_TEXTUALLY ~{"OH8300", "TBP2 - Arena 2"},~                                                                   ~{"OH8300", "(FN2)  Arène 2"},~
	REPLACE_TEXTUALLY ~{"OH8400", "TBP2 - Arena 3"},~                                                                   ~{"OH8400", "(FN2)  Arène 3"},~
	
	// CheatsAreas pour ToB : La Tour de Garde                                                                          
																														
	REPLACE_TEXTUALLY ~{"AR3000", "Watcher's Keep"},~                                                                   ~{"AR3000", "(ToB)  La Tour de Garde"},~
	REPLACE_TEXTUALLY ~{"AR3001", "Watcher's Keep -- Altar level"},~                                                    ~{"AR3001", "(Tour de Garde)  L'Autel, (1)"},~
	REPLACE_TEXTUALLY ~{"AR3003", "Watcher's Keep -- Compass level"},~                                                  ~{"AR3003", "(Tour de Garde)  La boussole, (3)"},~
	REPLACE_TEXTUALLY ~{"AR3004", "Watcher's Keep"},~                                                                   ~{"AR3004", "(Tour de Garde)  Diantrefosse, (3)"},~
	REPLACE_TEXTUALLY ~{"AR3005", "Watcher's Keep -- tieflings"},~                                                      ~{"AR3005", "(Tour de Garde)  Tieffelins"},~
	REPLACE_TEXTUALLY ~{"AR3006", "Watcher's Keep -- Succubus"},~                                                       ~{"AR3006", "(Tour de Garde)  Succube, (3)"},~
	REPLACE_TEXTUALLY ~{"AR3007", "Watcher's Keep --Cambion"},~                                                         ~{"AR3007", "(Tour de Garde)  Arbre, Cambion, (3)"},~
	REPLACE_TEXTUALLY ~{"AR3008", "Watcher's Keep -- Baalor (Paladin Sword)"},~                                         ~{"AR3008", "(Tour de Garde)  Menhir, (3)"},~
	REPLACE_TEXTUALLY ~{"AR3009", "Watcher's Keep -- Wild Magic ?"},~                                                   ~{"AR3009", "(Tour de Garde)  Salle de l'entropie, (3)"},~
	REPLACE_TEXTUALLY ~{"AR3010", "Watcher's Keep -- Tanar'ri -- Obelisk"},~                                            ~{"AR3010", "(Tour de Garde)  Obelisk, (3)"},~
	REPLACE_TEXTUALLY ~{"AR3011", "Watcher's Keep -- Bard's Gloves, Manman's Journal"},~                                ~{"AR3011", "(Tour de Garde)  Elfe Fou, Journal, (3)"},~
	REPLACE_TEXTUALLY ~{"AR3012", "Watcher's Keep -- Tahazzar"},~                                                       ~{"AR3012", "(Tour de Garde)  Tahazzar, (3)"},~
	REPLACE_TEXTUALLY ~{"AR3013", "Watcher's Keep -- Ka'rashur"},~                                                      ~{"AR3013", "(Tour de Garde)  Ka'rashur, (3)"},~
	REPLACE_TEXTUALLY ~{"AR3014", "Watcher's Keep -- White Dragon Scales"},~                                            ~{"AR3014", "(Tour de Garde)  Spectre démoniaque, (3)"},~
	REPLACE_TEXTUALLY ~{"AR3015", "Watcher's Keep -- Aesgareth"},~                                                      ~{"AR3015", "(Tour de Garde)  Aesgareth, (3)"},~
	REPLACE_TEXTUALLY ~{"AR3016", "Watcher's Keep -- Chromatic Demon; Elementalist Level"},~                            ~{"AR3016", "(Tour de Garde)  Démon Chromatique, (2)"},~
	REPLACE_TEXTUALLY ~{"AR3017", "Watcher's Keep -- Carston and the machine"},~                                        ~{"AR3017", "(Tour de Garde)  Machine de Lum le Fou, (4)"},~
	REPLACE_TEXTUALLY ~{"AR3018", "Watcher's Keep -- Saladrex (Dragon)"},~                                              ~{"AR3018", "(Tour de Garde)  Saladrex le dragon, (4)"},~
	REPLACE_TEXTUALLY ~{"AR3019", "Watcher's Keep -- Helmite Level -- Last Seals"},~                                    ~{"AR3019", "(Tour de Garde)  Le fantôme d'Helmite, (5)"},~
	REPLACE_TEXTUALLY ~{"AR3020", "Watcher's Keep -- Imprisoned One"},~                                                 ~{"AR3020", "(Tour de Garde)  L'Emprisonné, (6)"},~
	REPLACE_TEXTUALLY ~{"AR3021", "Watcher's Keep -- Illithids"},~                                                      ~{"AR3021", "(Tour de Garde)  Domaine des Illithids, (4)"},~
	REPLACE_TEXTUALLY ~{"AR3022", "Watcher's Keep -- Anti-Paladins"},~                                                  ~{"AR3022", "(Tour de Garde)  Githyankis Anti-Paladins, (4)"},~
	REPLACE_TEXTUALLY ~{"AR3023", "Watcher's Keep -- 'Adventure Level' (Mini Map!!!)"},~                                ~{"AR3023", "(Tour de Garde)  Jeu de rôle, (5)"},~
	REPLACE_TEXTUALLY ~{"AR3024", "Watcher's Keep -- Dragon -- Fear Challenge"},~                                       ~{"AR3024", "(Tour de Garde)  Dragon, Épreuve d'Helmite (5)"},~
	REPLACE_TEXTUALLY ~{"AR3025", "Watcher's Keep -- Orcs -- Ixil's Nail"},~                                            ~{"AR3025", "(Tour de Garde)  Horde, Épreuve d'Helmite (5)"},~
	REPLACE_TEXTUALLY ~{"AR3026", "Watcher's Keep -- Imp -- Game"},~                                                    ~{"AR3026", "(Tour de Garde)  Diablotin, Épreuve d'Helmite (5)"},~
	REPLACE_TEXTUALLY ~{"AR3027", "Watcher's Keep -- Crypt -- Demi-Lich"},~                                             ~{"AR3027", "(Tour de Garde)  Crypte de la Demi-Liche, (4)"},~
	
	// CheatsAreas pour ToB	                                                                                            
																														
	REPLACE_TEXTUALLY ~{"AR4000", "Spirit Heads"},~                                                                     ~{"AR4000", "(ToB)  Forêt des Esprit, ILLASERA (Chapitre 8)"},~
	REPLACE_TEXTUALLY ~{"AR4500", "Pocket Plane"},~                                                                     ~{"AR4500", "(ToB)  Antichambre, (Sarevok)"},~
	REPLACE_TEXTUALLY ~{"AR5000", "Saradush"},~                                                                         ~{"AR5000", "  SARADUSH"},~
	REPLACE_TEXTUALLY ~{"AR5001", "Gromnir 1st Level"},~                                                                ~{"AR5001", "(Gromnir)  Château de Saradush"},~
	REPLACE_TEXTUALLY ~{"AR5002", "Gromnir's Hideout"},~                                                                ~{"AR5002", "(Gromnir)  Planque de GROMNIR"},~
	REPLACE_TEXTUALLY ~{"AR5003", "Saradush Tavern (Tankard Tree)"},~                                                   ~{"AR5003", "(S)  Taverne de l'Arbre à Chopines"},~
	REPLACE_TEXTUALLY ~{"AR5004", "Temple of Waukeen"},~                                                                ~{"AR5004", "(S)  Temple de Waukyne"},~
	REPLACE_TEXTUALLY ~{"AR5005", "Gromnir's Barracks"},~                                                               ~{"AR5005", "(S)  Caserne de Gromnir"},~
	REPLACE_TEXTUALLY ~{"AR5006", "Saradush Prison"},~                                                                  ~{"AR5006", "(S)  Prison de Saradush"},~
	REPLACE_TEXTUALLY ~{"AR5007", "Basement Entrance to Gromnir's Hideout"},~                                           ~{"AR5007", "(Gromnir)  Sous-sols du Château"},~
	REPLACE_TEXTUALLY ~{"AR5008", "Kiser's Home"},~                                                                     ~{"AR5008", "(S)  Demeure de Kiser, L1"},~
	REPLACE_TEXTUALLY ~{"AR5009", "House (no exit?)"},~                                                                 ~{"AR5009", "(CLUA)  Demeure de Kiser, L2"},~
	REPLACE_TEXTUALLY ~{"AR5010", "Countess Santele's Home"},~                                                          ~{"AR5010", "(S)  Demeure de la comtesse Santele"},~
	REPLACE_TEXTUALLY ~{"AR5011", "Arcana Archives"},~                                                                  ~{"AR5011", "(S)  Archives des Arcanes, Lazarus Librarus"},~
	REPLACE_TEXTUALLY ~{"AR5012", "House"},~                                                                            ~{"AR5012", "(S)  Maison de paysans"},~
	REPLACE_TEXTUALLY ~{"AR5013", "Sewers beneath Saradush"},~                                                          ~{"AR5013", "(S)  Égouts de Saradush"},~
	REPLACE_TEXTUALLY ~{"AR5014", "Kiser's Home -- Cellar"},~                                                           ~{"AR5014", "(S)  Demeure de Kiser, Cellier"},~
	REPLACE_TEXTUALLY ~{"AR5015", "Saradush Militia Entrance"},~                                                        ~{"AR5015", "(S)  Quartier général de la milice"},~
	REPLACE_TEXTUALLY ~{"AR5016", "Saradush Castle Jail (Kiser Plot)"},~                                                ~{"AR5016", "(S)  Cellules de la milice"},~
	REPLACE_TEXTUALLY ~{"AR5200", "Fire Giant Entrance Area"},~                                                         ~{"AR5200", "(Yaga-Shura)  Les Monts de la Marche"},~
	REPLACE_TEXTUALLY ~{"AR5201", "Fire Giant Keep"},~                                                                  ~{"AR5201", "(Yaga-Shura)  Montagne des géants du feu"},~
	REPLACE_TEXTUALLY ~{"AR5202", "Nyalee's Hideout; Gorion Wraith"},~                                                  ~{"AR5202", "(Yaga-Shura)  Forêt de Mir, (Nyalee)"},~
	REPLACE_TEXTUALLY ~{"AR5203", "Yaga-Shura's Camp"},~                                                                ~{"AR5203", "(Yaga-Shura)  Camp de YAGA-SHURA"},~
	REPLACE_TEXTUALLY ~{"AR5204", "Yaga-Shura's Keep"},~                                                                ~{"AR5204", "(Yaga-Shura)  Cœur de Yaga-Shura"},~
	REPLACE_TEXTUALLY ~{"AR5500", "Amkethran"},~                                                                        ~{"AR5500", "  AMKETHRAN, (Chapitre 9)"},~
	REPLACE_TEXTUALLY ~{"AR5501", "Amkethran Inn"},~                                                                    ~{"AR5501", "(Balthazar)  Taverne d'Amkethran"},~
	REPLACE_TEXTUALLY ~{"AR5502", "Kerrick the Smith's House"},~                                                        ~{"AR5502", "(Balthazar)  Kerrick le forgeron, Lazarus Librarus"},~
	REPLACE_TEXTUALLY ~{"AR5503", "Chyil's House"},~                                                                    ~{"AR5503", "(Balthazar)  Temple de Waukyne, (Chyil)"},~
	REPLACE_TEXTUALLY ~{"AR5504", "Smuggler Cave"},~                                                                    ~{"AR5504", "(Balthazar)  Caverne des contrebandiers"},~
	REPLACE_TEXTUALLY ~{"AR5505", "Balthazar's Home"},~                                                                 ~{"AR5505", "(Balthazar)  Demeure de BALTHAZAR"},~
	REPLACE_TEXTUALLY ~{"AR5506", "Commoner's Home"},~                                                                  ~{"AR5506", "(Balthazar)  Maison de roturiers"},~
	REPLACE_TEXTUALLY ~{"AR5507", "Empty Home"},~                                                                       ~{"AR5507", "(Balthazar)  Maison vide"},~
	REPLACE_TEXTUALLY ~{"AR5508", "Faheed's Home"},~                                                                    ~{"AR5508", "(Balthazar)  Maison de Majira et Faheed"},~
	REPLACE_TEXTUALLY ~{"AR5509", "Amkethran Crypt"},~                                                                  ~{"AR5509", "(Balthazar)  Grotte des Morts, (Vongoethe la liche)"},~
	REPLACE_TEXTUALLY ~{"AR6000", "Abazigal's Entrance"},~                                                              ~{"AR6000", "(Abazigal)  Enclave d'Abazigal, (Draconis)"},~
	REPLACE_TEXTUALLY ~{"AR6001", "Abazigal's Lair Entrance Hall"},~                                                    ~{"AR6001", "(Abazigal)  Entrée de l'Enclave"},~
	REPLACE_TEXTUALLY ~{"AR6002", "Abazigal's Lair -- Cells"},~                                                         ~{"AR6002", "(Abazigal)  Kuo-toa, Cellule, Corde, (Puits Est 2)"},~
	REPLACE_TEXTUALLY ~{"AR6003", "Abazigal's Lair -- Iycanth the Mad, Bondari"},~                                      ~{"AR6003", "(Abazigal)  Iycanth le fou, Statues, (Puits Central 3)"},~
	REPLACE_TEXTUALLY ~{"AR6004", "Abazigal's Lair -- Fll'Yissetat"},~                                                  ~{"AR6004", "(Abazigal)  Vers l'antre, Fll'Yissetat, (Puits Sud 4)"},~
	REPLACE_TEXTUALLY ~{"AR6005", "Abazigal's Hideout"},~                                                               ~{"AR6005", "(Abazigal)  Tanière d'ABAZIGAL"},~
	REPLACE_TEXTUALLY ~{"AR6008", "Frost Salamander Cave"},~                                                            ~{"AR6008", "(Abazigal)  Salamandres de glace, (Puits Ouest 1)"},~
	REPLACE_TEXTUALLY ~{"AR6011", "Orbs and Gauth"},~                                                                   ~{"AR6011", "(Abazigal)  Orbes Anciens, (Pédoncule)"},~
	REPLACE_TEXTUALLY ~{"AR6012", "Pool Home -- breath under water"},~                                                  ~{"AR6012", "(Abazigal)  Maison de la respiration"},~
	REPLACE_TEXTUALLY ~{"AR6100", "Area outside Sendai's Hideout"},~                                                    ~{"AR6100", "(Sendai)  Enclave de Sendai"},~
	REPLACE_TEXTUALLY ~{"AR6101", "Main Entrance Sendai's Lair"},~                                                      ~{"AR6101", "(Sendai)  Entrée de l'Enclave"},~
	REPLACE_TEXTUALLY ~{"AR6102", "Sendai's Lair -- Slavemaster"},~                                                     ~{"AR6102", "(Sendai)  Tunnel du Nord, (Duergars)"},~
	REPLACE_TEXTUALLY ~{"AR6103", "Sendai's Lair -- Spiders"},~                                                         ~{"AR6103", "(Sendai)  Tunnel du Sud, (Araignées)"},~
	REPLACE_TEXTUALLY ~{"AR6104", "Sendai's Lair -- Crossway"},~                                                        ~{"AR6104", "(Sendai)  Vers la maison d'Odamaron"},~
	REPLACE_TEXTUALLY ~{"AR6105", "Sendai's Lair -- Diaytha, Abishai"},~                                                ~{"AR6105", "(Sendai)  Prêtresse Diaytha, L2"},~
	REPLACE_TEXTUALLY ~{"AR6106", "Sendai's Lair -- Captain Egeissag"},~                                                ~{"AR6106", "(Sendai)  Capitaine Egeissag, L3"},~
	REPLACE_TEXTUALLY ~{"AR6107", "Sendai's Lair -- Mithykyl"},~                                                        ~{"AR6107", "(Sendai)  Mithykyll Le flagelleur mental, L3"},~
	REPLACE_TEXTUALLY ~{"AR6108", "Sendai's Lair -- Sendai"},~                                                          ~{"AR6108", "(Sendai)  Repaire de SENDAI"},~
	REPLACE_TEXTUALLY ~{"AR6109", "Sendai's Lair -- Drow"},~                                                            ~{"AR6109", "(Sendai)  Caserne de elfes noirs"},~
	REPLACE_TEXTUALLY ~{"AR6110", "Sendai's Lair -- Odamaron"},~                                                        ~{"AR6110", "(Sendai)  Maison d'Odamaron la liche, L1"},~
	REPLACE_TEXTUALLY ~{"AR6111", "Woodcutter's House -- Sendai's Area"},~                                              ~{"AR6111", "(Sendai)  Maison du Bûcheron"},~
	REPLACE_TEXTUALLY ~{"AR6200", "The Throne of Bhaal"},~                                                              ~{"AR6200", "(ToB)  Le Trône de Bhaal / Fin du Jeu"},~
	REPLACE_TEXTUALLY ~{"AR6300", "Oasis in Tethyr"},~                                                                  ~{"AR6300", "(ToB)  Oasis du Téthyr"},~
	REPLACE_TEXTUALLY ~{"AR6400", "River Area"},~                                                                       ~{"AR6400", "(ToB)  Forêt du Nord, (Téthyr, Rivière)"},~
	REPLACE_TEXTUALLY ~{"OH4200", "Rasaad - Dwarven Clanhold Exterior"},~                                               ~{"OH4200", "(ToB)  Rocheprofonde, Quête de Rasaad"},~
	REPLACE_TEXTUALLY ~{"OH4210", "Rasaad - Dwarven Clanhold Interior"},~                                               ~{"OH4210", "(ToB)  Clan de Rocheprofonde, Quête de Rasaad"},~
	REPLACE_TEXTUALLY ~{"OH4220", "Rasaad - Dwarven Mines"},~                                                           ~{"OH4220", "(ToB)  Mines de Rocheprofonde, Quête de Rasaad"},~
	REPLACE_TEXTUALLY ~{"OH4230", "Rasaad - Plane of Shadow"},~                                                         ~{"OH4230", "(ToB)  Plan de l'ombre, Quête de Rasaad"},~
	REPLACE_TEXTUALLY ~{"OH4290", "Rasaad - Sharran Ambush"},~                                                          ~{"OH4290", "(ToB)  l'embuscade des Sharrans, Quête de Rasaad"},~
	REPLACE_TEXTUALLY ~{"OH5400", "Dorn - Forest Clearing"},~                                                           ~{"OH5400", "(ToB)  Clairière de la forêt, Quête de Dorn"},~
	REPLACE_TEXTUALLY ~{"OH5500", "Dorn - Lunia"},~                                                                     ~{"OH5500", "(ToB)  Lunia, Quête de Dorn"},~
	REPLACE_TEXTUALLY ~{"OH6400", "Neera - Wilderness Clearing"},~                                                      ~{"OH6400", "(ToB)  Clairière, Quête de Neera"},~
	REPLACE_TEXTUALLY ~{"OH6450", "Neera - The Black Pits: Arena"},~                                                    ~{"OH6450", "(ToB)  Arène des Fosses noires, Quête de Neera"},~
	REPLACE_TEXTUALLY ~{"OH6460", "Neera - The Black Pits: Staging Area"},~                                             ~{"OH6460", "(ToB)  Salle de repos des Fosses noires, Quête de Neera"},~
	REPLACE_TEXTUALLY ~{"OH6500", "Neera - Thayan Estate"},~                                                            ~{"OH6500", "(ToB)  Domaine Thayen, Quête de Neera"},~
	REPLACE_TEXTUALLY ~{"OH7300", "Hexxat - Completed Maze (Korkorran)"},~                                              ~{"OH7300", "(ToB)  Labyrinthe de Korkorran, Quête de Hexxat"},~
	REPLACE_TEXTUALLY ~{"OH7310", "Hexxat - Scene with L"},~                                                            ~{"OH7310", "(ToB)  Scene with L, Quête de Hexxat"},~
	
END
