ACTION_IF FILE_EXISTS_IN_GAME ~bgee.lua~ BEGIN
	COPY_EXISTING ~bgee.lua~ ~override/bgee.lua~

	// CheatsAreas pour BGEE
	
	REPLACE_TEXTUALLY ~{"BG0002", "N Baldur's Gate: Temple of Helm"},~                                          @1  
	REPLACE_TEXTUALLY ~{"BG0004", "N Baldur's Gate: Bheren's House L1"},~                                       @2  
	REPLACE_TEXTUALLY ~{"BG0005", "N Baldur's Gate: Bheren's House L2"},~                                       @3  
	REPLACE_TEXTUALLY ~{"BG0006", "N Baldur's Gate: Rinnie's House L1"},~                                       @4  
	REPLACE_TEXTUALLY ~{"BG0007", "N Baldur's Gate: Rinnie's House L2"},~                                       @5  
	REPLACE_TEXTUALLY ~{"BG0008", "N Baldur's Gate: House1 L1"},~                                               @6  
	REPLACE_TEXTUALLY ~{"BG0009", "N Baldur's Gate: House1 L2"},~                                               @7  
	REPLACE_TEXTUALLY ~{"BG0010", "N Baldur's Gate: Jardak's House L1"},~                                       @8  
	REPLACE_TEXTUALLY ~{"BG0011", "N Baldur's Gate: Jardak's House L2"},~                                       @9  
	REPLACE_TEXTUALLY ~{"BG0012", "N Baldur's Gate: House2 L1"},~                                               @10 
	REPLACE_TEXTUALLY ~{"BG0013", "N Baldur's Gate: House2 L2"},~                                               @11 
	REPLACE_TEXTUALLY ~{"BG0014", "N Baldur's Gate: House3 L1"},~                                               @12 
	REPLACE_TEXTUALLY ~{"BG0015", "N Baldur's Gate: House3 L2"},~                                               @13 
	REPLACE_TEXTUALLY ~{"BG0016", "N Baldur's Gate: House4 L1"},~                                               @14 
	REPLACE_TEXTUALLY ~{"BG0017", "N Baldur's Gate: House4 L2"},~                                               @15 
	REPLACE_TEXTUALLY ~{"BG0018", "N Baldur's Gate: House5 L1"},~                                               @16 
	REPLACE_TEXTUALLY ~{"BG0019", "N Baldur's Gate: House5 L2"},~                                               @17 
	REPLACE_TEXTUALLY ~{"BG0020", "N Baldur's Gate: House6 L1"},~                                               @18 
	REPLACE_TEXTUALLY ~{"BG0021", "N Baldur's Gate: House6 L2"},~                                               @19 
	REPLACE_TEXTUALLY ~{"BG0100", "NW Baldur's Gate"},~                                                         @20 
	REPLACE_TEXTUALLY ~{"BG0101", "NW Baldur's Gate: Silvershield Estate L1"},~                                 @21 
	REPLACE_TEXTUALLY ~{"BG0102", "NW Baldur's Gate: Silvershield Estate L2"},~                                 @22 
	REPLACE_TEXTUALLY ~{"BG0103", "NE Baldur's Gate: Splurging Sturgeon L1"},~                                  @23 
	REPLACE_TEXTUALLY ~{"BG0104", "NE Baldur's Gate: Splurging Sturgeon L2"},~                                  @24 
	REPLACE_TEXTUALLY ~{"BG0105", "SE Baldur's Gate: Blade & Stars L1"},~                                       @25 
	REPLACE_TEXTUALLY ~{"BG0106", "SE Baldur's Gate: Blade & Stars L2"},~                                       @26 
	REPLACE_TEXTUALLY ~{"BG0107", "SE Baldur's Gate: Blade & Stars L3"},~                                       @27 
	REPLACE_TEXTUALLY ~{"BG0108", "N Baldur's Gate: Ducal Palace L1"},~                                         @28 
	REPLACE_TEXTUALLY ~{"BG0109", "N Baldur's Gate: Ducal Palace L2"},~                                         @29 
	REPLACE_TEXTUALLY ~{"BG0110", "N Baldur's Gate: Ducal Palace L3"},~                                         @30 
	REPLACE_TEXTUALLY ~{"BG0111", "N Baldur's Gate: Ducal Palace Cellar"},~                                     @31 
	REPLACE_TEXTUALLY ~{"BG0112", "Baldur's Gate Undercellars"},~                                               @32 
	REPLACE_TEXTUALLY ~{"BG0114", "NE Baldur's Gate: Blushing Mermaid L1"},~                                    @33 
	REPLACE_TEXTUALLY ~{"BG0115", "NE Baldur's Gate: Blushing Mermaid L2"},~                                    @34 
	REPLACE_TEXTUALLY ~{"BG0116", "NW Baldur's Gate: Helm & Cloak L1"},~                                        @35 
	REPLACE_TEXTUALLY ~{"BG0117", "NW Baldur's Gate: Helm & Cloak L2"},~                                        @36 
	REPLACE_TEXTUALLY ~{"BG0118", "NW Baldur's Gate: Helm & Cloak L3"},~                                        @37 
	REPLACE_TEXTUALLY ~{"BG0119", "N Baldur's Gate: Three Old Kegs L1"},~                                       @38 
	REPLACE_TEXTUALLY ~{"BG0120", "N Baldur's Gate: Three Old Kegs L2"},~                                       @39 
	REPLACE_TEXTUALLY ~{"BG0121", "N Baldur's Gate: Three Old Kegs L3"},~                                       @40 
	REPLACE_TEXTUALLY ~{"BG0123", "Undercity"},~                                                                @41 
	REPLACE_TEXTUALLY ~{"BG0125", "Undercity: Temple of Bhaal"},~                                               @42 
	REPLACE_TEXTUALLY ~{"BG0126", "W Baldur's Gate: Ragefast's House"},~                                        @43 
	REPLACE_TEXTUALLY ~{"BG0127", "SW Baldur's Gate: Merchant League L1"},~                                     @44 
	REPLACE_TEXTUALLY ~{"BG0128", "SW Baldur's Gate: Merchant League L2"},~                                     @45 
	REPLACE_TEXTUALLY ~{"BG0129", "SW Baldur's Gate: Merchant League L3"},~                                     @46 
	REPLACE_TEXTUALLY ~{"BG0130", "W Baldur's Gate: Hall of Wonders"},~                                         @47 
	REPLACE_TEXTUALLY ~{"BG0131", "W Baldur's Gate: High House of Wonders"},~                                   @48 
	REPLACE_TEXTUALLY ~{"BG0132", "W Baldur's Gate: Lady's House"},~                                            @49 
	REPLACE_TEXTUALLY ~{"BG0133", "Baldur's Gate Docks: Low Lantern D1"},~                                      @50 
	REPLACE_TEXTUALLY ~{"BG0134", "Baldur's Gate Docks: Low Lantern D2"},~                                      @51 
	REPLACE_TEXTUALLY ~{"BG0135", "Baldur's Gate Docks: Low Lantern D3"},~                                      @52 
	REPLACE_TEXTUALLY ~{"BG0136", "Baldur's Gate Docks: Low Lantern D4"},~                                      @53 
	REPLACE_TEXTUALLY ~{"BG0137", "N Baldur's Gate: Ramazith's Tower L1"},~                                     @54 
	REPLACE_TEXTUALLY ~{"BG0138", "N Baldur's Gate: Ramazith's Tower L6"},~                                     @55 
	REPLACE_TEXTUALLY ~{"BG0139", "N Baldur's Gate: Ramazith's Tower L2"},~                                     @56 
	REPLACE_TEXTUALLY ~{"BG0140", "N Baldur's Gate: Ramazith's Tower L3"},~                                     @57 
	REPLACE_TEXTUALLY ~{"BG0141", "N Baldur's Gate: Ramazith's Tower L4"},~                                     @58 
	REPLACE_TEXTUALLY ~{"BG0142", "N Baldur's Gate: Ramazith's Tower L5"},~                                     @59 
	REPLACE_TEXTUALLY ~{"BG0143", "Central Baldur's Gate: Oberon's Estate L1"},~                                @60 
	REPLACE_TEXTUALLY ~{"BG0144", "Central Baldur's Gate: Oberon's Estate L2"},~                                @61 
	REPLACE_TEXTUALLY ~{"BG0145", "Central Baldur's Gate: Oberon's Estate L3"},~                                @62 
	REPLACE_TEXTUALLY ~{"BG0146", "Thieves' Maze"},~                                                            @63 
	REPLACE_TEXTUALLY ~{"BG0148", "E Baldur's Gate: House5"},~                                                  @64 
	REPLACE_TEXTUALLY ~{"BG0149", "NE Baldur's Gate: Ilmater's Shrine"},~                                       @65 
	REPLACE_TEXTUALLY ~{"BG0150", "E Baldur's Gate: House2"},~                                                  @66 
	REPLACE_TEXTUALLY ~{"BG0151", "E Baldur's Gate: House3"},~                                                  @67 
	REPLACE_TEXTUALLY ~{"BG0152", "E Baldur's Gate: House4"},~                                                  @68 
	REPLACE_TEXTUALLY ~{"BG0153", "E Baldur's Gate: Thieves' Guild"},~                                          @69 
	REPLACE_TEXTUALLY ~{"BG0154", "E Baldur's Gate: Keexie Tavern L1"},~                                        @70 
	REPLACE_TEXTUALLY ~{"BG0155", "NW Baldur's Gate: House3 L1"},~                                              @71 
	REPLACE_TEXTUALLY ~{"BG0156", "NW Baldur's Gate: House3 L2"},~                                              @72 
	REPLACE_TEXTUALLY ~{"BG0157", "NW Baldur's Gate: Quinn's House L1"},~                                       @73 
	REPLACE_TEXTUALLY ~{"BG0158", "NW Baldur's Gate: Quinn's House L2"},~                                       @74 
	REPLACE_TEXTUALLY ~{"BG0159", "NW Baldur's Gate: House1 L1"},~                                              @75 
	REPLACE_TEXTUALLY ~{"BG0160", "NW Baldur's Gate: House1 L2"},~                                              @76 
	REPLACE_TEXTUALLY ~{"BG0161", "NW Baldur's Gate: Degrodel's House"},~                                       @77 
	REPLACE_TEXTUALLY ~{"BG0162", "NW Baldur's Gate: Laerta's House L1"},~                                      @78 
	REPLACE_TEXTUALLY ~{"BG0163", "NW Baldur's Gate: House2 L1"},~                                              @79 
	REPLACE_TEXTUALLY ~{"BG0164", "NW Baldur's Gate: House2 L2"},~                                              @80 
	REPLACE_TEXTUALLY ~{"BG0165", "NW Baldur's Gate: Tavern L1"},~                                              @81 
	REPLACE_TEXTUALLY ~{"BG0166", "NW Baldur's Gate: Tavern L2"},~                                              @82 
	REPLACE_TEXTUALLY ~{"BG0167", "NW Baldur's Gate: Pheirkas' House L1"},~                                     @83 
	REPLACE_TEXTUALLY ~{"BG0168", "NW Baldur's Gate: Pheirkas' House L2"},~                                     @84 
	REPLACE_TEXTUALLY ~{"BG0169", "NW Baldur's Gate: House4 L1"},~                                              @85 
	REPLACE_TEXTUALLY ~{"BG0170", "NW Baldur's Gate: House4 L2"},~                                              @86 
	REPLACE_TEXTUALLY ~{"BG0171", "E Baldur's Gate: Keexie Tavern L2"},~                                        @87 
	REPLACE_TEXTUALLY ~{"BG0200", "N Baldur's Gate"},~                                                          @88 
	REPLACE_TEXTUALLY ~{"BG0224", "W Sewers"},~                                                                 @89 
	REPLACE_TEXTUALLY ~{"BG0225", "Central Sewers"},~                                                           @90 
	REPLACE_TEXTUALLY ~{"BG0226", "E Sewers"},~                                                                 @91 
	REPLACE_TEXTUALLY ~{"BG0300", "NE Baldur's Gate"},~                                                         @92 
	REPLACE_TEXTUALLY ~{"BG0302", "NE Baldur's Gate: House2 L1"},~                                              @93 
	REPLACE_TEXTUALLY ~{"BG0303", "NE Baldur's Gate: House2 L2"},~                                              @94 
	REPLACE_TEXTUALLY ~{"BG0304", "NE Baldur's Gate: Store"},~                                                  @95 
	REPLACE_TEXTUALLY ~{"BG0305", "NE Baldur's Gate: House1 L1"},~                                              @96 
	REPLACE_TEXTUALLY ~{"BG0306", "NE Baldur's Gate: House1 L2"},~                                              @97 
	REPLACE_TEXTUALLY ~{"BG0307", "NE Baldur's Gate: Counting House L1"},~                                      @98 
	REPLACE_TEXTUALLY ~{"BG0308", "NE Baldur's Gate: Counting House L2"},~                                      @99 
	REPLACE_TEXTUALLY ~{"BG0400", "Upper Chionthar"},~                                                          @100
	REPLACE_TEXTUALLY ~{"BG0401", "Upper Chionthar: Farmhouse"},~                                               @101
	REPLACE_TEXTUALLY ~{"BG0500", "Durlag's Tower"},~                                                           @102
	REPLACE_TEXTUALLY ~{"BG0501", "Durlag's Tower: Cellar"},~                                                   @103
	REPLACE_TEXTUALLY ~{"BG0502", "Durlag's Tower: L1"},~                                                       @104
	REPLACE_TEXTUALLY ~{"BG0503", "Durlag's Tower: L2"},~                                                       @105
	REPLACE_TEXTUALLY ~{"BG0504", "Durlag's Tower: L3"},~                                                       @106
	REPLACE_TEXTUALLY ~{"BG0505", "Durlag's Tower: L4"},~                                                       @107
	REPLACE_TEXTUALLY ~{"BG0506", "Durlag's Tower: Chessboard"},~                                               @108
	REPLACE_TEXTUALLY ~{"BG0507", "Durlag's Tower: Ice Chamber"},~                                              @109
	REPLACE_TEXTUALLY ~{"BG0508", "Durlag's Tower: Fire Chamber"},~                                             @110
	REPLACE_TEXTUALLY ~{"BG0509", "Durlag's Tower: Air Chamber"},~                                              @111
	REPLACE_TEXTUALLY ~{"BG0510", "Durlag's Tower: Earth Chamber"},~                                            @112
	REPLACE_TEXTUALLY ~{"BG0511", "Durlag's Tower: D1"},~                                                       @113
	REPLACE_TEXTUALLY ~{"BG0512", "Durlag's Tower: D2"},~                                                       @114
	REPLACE_TEXTUALLY ~{"BG0513", "Durlag's Tower: D3"},~                                                       @115
	REPLACE_TEXTUALLY ~{"BG0514", "Durlag's Tower: D4"},~                                                       @116
	REPLACE_TEXTUALLY ~{"BG0515", "Durlag's Tower: Compass Room"},~                                             @117
	REPLACE_TEXTUALLY ~{"BG0516", "Durlag's Tower: Demonknight's Chamber"},~                                    @118
	REPLACE_TEXTUALLY ~{"BG0600", "W Baldur's Gate"},~                                                          @119
	REPLACE_TEXTUALLY ~{"BG0601", "SW Baldur's Gate: Seven Suns L1"},~                                          @120
	REPLACE_TEXTUALLY ~{"BG0602", "SW Baldur's Gate: Seven Suns L2"},~                                          @121
	REPLACE_TEXTUALLY ~{"BG0603", "SW Baldur's Gate: Seven Suns Cellar"},~                                      @122
	REPLACE_TEXTUALLY ~{"BG0606", "SW Baldur's Gate: Flaming Fist HQ Cellar"},~                                 @123
	REPLACE_TEXTUALLY ~{"BG0607", "SW Baldur's Gate: Flaming Fist HQ L1"},~                                     @124
	REPLACE_TEXTUALLY ~{"BG0608", "SW Baldur's Gate: Flaming Fist HQ L2"},~                                     @125
	REPLACE_TEXTUALLY ~{"BG0609", "Baldur's Gate Docks: Water-Queen's House"},~                                 @126
	REPLACE_TEXTUALLY ~{"BG0611", "Baldur's Gate Docks: Iron Throne Cellar"},~                                  @127
	REPLACE_TEXTUALLY ~{"BG0612", "Baldur's Gate Docks: Iron Throne L2"},~                                      @128
	REPLACE_TEXTUALLY ~{"BG0613", "Baldur's Gate Docks: Iron Throne L3"},~                                      @129
	REPLACE_TEXTUALLY ~{"BG0614", "Baldur's Gate Docks: Iron Throne L4"},~                                      @130
	REPLACE_TEXTUALLY ~{"BG0615", "Baldur's Gate Docks: Iron Throne L5"},~                                      @131
	REPLACE_TEXTUALLY ~{"BG0616", "Baldur's Gate Docks: Iron Throne L1"},~                                      @132
	REPLACE_TEXTUALLY ~{"BG0617", "W Baldur's Gate: Tremain's House L1"},~                                      @133
	REPLACE_TEXTUALLY ~{"BG0618", "W Baldur's Gate: Tremain's House L2"},~                                      @134
	REPLACE_TEXTUALLY ~{"BG0619", "W Baldur's Gate: Fenten's House L1"},~                                       @135
	REPLACE_TEXTUALLY ~{"BG0620", "W Baldur's Gate: Fenten's House L2"},~                                       @136
	REPLACE_TEXTUALLY ~{"BG0621", "Baldur's Gate Docks: Iron Throne Roof"},~                                    @137
	REPLACE_TEXTUALLY ~{"BG0700", "Central Baldur's Gate"},~                                                    @138
	REPLACE_TEXTUALLY ~{"BG0702", "Baldur's Gate Docks: Harbormaster"},~                                        @139
	REPLACE_TEXTUALLY ~{"BG0703", "E Baldur's Gate: Sorcerous Sundries L1"},~                                   @140
	REPLACE_TEXTUALLY ~{"BG0704", "E Baldur's Gate: Sorcerous Sundries L2"},~                                   @141
	REPLACE_TEXTUALLY ~{"BG0705", "E Baldur's Gate: Elfsong Tavern L1"},~                                       @142
	REPLACE_TEXTUALLY ~{"BG0706", "E Baldur's Gate: Elfsong Tavern L2"},~                                       @143
	REPLACE_TEXTUALLY ~{"BG0707", "Central Baldur's Gate: House3 L1"},~                                         @144
	REPLACE_TEXTUALLY ~{"BG0708", "Central Baldur's Gate: House3 L2"},~                                         @145
	REPLACE_TEXTUALLY ~{"BG0709", "Central Baldur's Gate: House2 L1"},~                                         @146
	REPLACE_TEXTUALLY ~{"BG0710", "Central Baldur's Gate: House2 L2"},~                                         @147
	REPLACE_TEXTUALLY ~{"BG0711", "Central Baldur's Gate: House1 L1"},~                                         @148
	REPLACE_TEXTUALLY ~{"BG0712", "Central Baldur's Gate: House1 L2"},~                                         @149
	REPLACE_TEXTUALLY ~{"BG0713", "Central Baldur's Gate: House5 L1"},~                                         @150
	REPLACE_TEXTUALLY ~{"BG0714", "Central Baldur's Gate: House5 L2"},~                                         @151
	REPLACE_TEXTUALLY ~{"BG0715", "Central Baldur's Gate: Nadine's House L1"},~                                 @152
	REPLACE_TEXTUALLY ~{"BG0716", "Central Baldur's Gate: Nadine's House L2"},~                                 @153
	REPLACE_TEXTUALLY ~{"BG0717", "Central Baldur's Gate: House6 L1"},~                                         @154
	REPLACE_TEXTUALLY ~{"BG0718", "Central Baldur's Gate: House6 L2"},~                                         @155
	REPLACE_TEXTUALLY ~{"BG0719", "Central Baldur's Gate: Felonius' Manor"},~                                   @156
	REPLACE_TEXTUALLY ~{"BG0720", "Central Baldur's Gate: Drakon Tavern"},~                                     @157
	REPLACE_TEXTUALLY ~{"BG0721", "Central Baldur's Gate: Poultry Store"},~                                     @158
	REPLACE_TEXTUALLY ~{"BG0722", "Central Baldur's Gate: House4 L1"},~                                         @159
	REPLACE_TEXTUALLY ~{"BG0723", "Central Baldur's Gate: House4 L2"},~                                         @160
	REPLACE_TEXTUALLY ~{"BG0724", "Central Baldur's Gate: Gambling Tent 1"},~                                   @161
	REPLACE_TEXTUALLY ~{"BG0725", "Central Baldur's Gate: Gambling Tent 2"},~                                   @162
	REPLACE_TEXTUALLY ~{"BG0726", "Central Baldur's Gate: Diviner's Tent"},~                                    @163
	REPLACE_TEXTUALLY ~{"BG0800", "E Baldur's Gate"},~                                                          @164
	REPLACE_TEXTUALLY ~{"BG0801", "E Baldur's Gate: House6 L1"},~                                               @165
	REPLACE_TEXTUALLY ~{"BG0802", "E Baldur's Gate: House6 L2"},~                                               @166
	REPLACE_TEXTUALLY ~{"BG0803", "E Baldur's Gate: Maltz' Weapon Shop L1"},~                                   @167
	REPLACE_TEXTUALLY ~{"BG0804", "E Baldur's Gate: Maltz' Weapon Shop L2"},~                                   @168
	REPLACE_TEXTUALLY ~{"BG0805", "E Baldur's Gate: Arkion's House L1"},~                                       @169
	REPLACE_TEXTUALLY ~{"BG0806", "E Baldur's Gate: Arkion's House L2"},~                                       @170
	REPLACE_TEXTUALLY ~{"BG0807", "E Baldur's Gate: Inn L1"},~                                                  @171
	REPLACE_TEXTUALLY ~{"BG0808", "E Baldur's Gate: Inn L2"},~                                                  @172
	REPLACE_TEXTUALLY ~{"BG0809", "E Baldur's Gate: Silence's Shop"},~                                          @173
	REPLACE_TEXTUALLY ~{"BG0810", "E Baldur's Gate: Lucky Aello's"},~                                           @174
	REPLACE_TEXTUALLY ~{"BG0811", "E Baldur's Gate: House1 L1"},~                                               @175
	REPLACE_TEXTUALLY ~{"BG0812", "E Baldur's Gate: House1 L2"},~                                               @176
	REPLACE_TEXTUALLY ~{"BG0813", "SE Baldur's Gate: Nemphre's House L1"},~                                     @177
	REPLACE_TEXTUALLY ~{"BG0814", "SE Baldur's Gate: Nemphre's House L2"},~                                     @178
	REPLACE_TEXTUALLY ~{"BG0900", "Wyrm's Crossing"},~                                                          @179
	REPLACE_TEXTUALLY ~{"BG0901", "Wyrm's Crossing: Tenya's House"},~                                           @180
	REPLACE_TEXTUALLY ~{"BG1000", "Ulgoth's Beard"},~                                                           @181
	REPLACE_TEXTUALLY ~{"BG1001", "Ulgoth's Beard: Inn"},~                                                      @182
	REPLACE_TEXTUALLY ~{"BG1002", "Ulgoth's Beard: Demon's Chamber"},~                                          @183
	REPLACE_TEXTUALLY ~{"BG1003", "Ulgoth's Beard: Storehouse"},~                                               @184
	REPLACE_TEXTUALLY ~{"BG1004", "Ulgoth's Beard: Mendas' House"},~                                            @185
	REPLACE_TEXTUALLY ~{"BG1005", "Ulgoth's Beard: Therella's House"},~                                         @186
	REPLACE_TEXTUALLY ~{"BG1006", "Ulgoth's Beard: House2"},~                                                   @187
	REPLACE_TEXTUALLY ~{"BG1007", "Ulgoth's Beard: House1"},~                                                   @188
	REPLACE_TEXTUALLY ~{"BG1008", "Ice Island"},~                                                               @189
	REPLACE_TEXTUALLY ~{"BG1009", "Ice Island: Maze L1"},~                                                      @190
	REPLACE_TEXTUALLY ~{"BG1010", "Ice Island: Maze L2"},~                                                      @191
	REPLACE_TEXTUALLY ~{"BG1100", "SW Baldur's Gate"},~                                                         @192
	REPLACE_TEXTUALLY ~{"BG1101", "SW Baldur's Gate: Wiven's House L1"},~                                       @193
	REPLACE_TEXTUALLY ~{"BG1102", "SW Baldur's Gate: Wiven's House L2"},~                                       @194
	REPLACE_TEXTUALLY ~{"BG1103", "SW Baldur's Gate: House3 L1"},~                                              @195
	REPLACE_TEXTUALLY ~{"BG1104", "SW Baldur's Gate: House3 L2"},~                                              @196
	REPLACE_TEXTUALLY ~{"BG1105", "SW Baldur's Gate: House1 L1"},~                                              @197
	REPLACE_TEXTUALLY ~{"BG1106", "SW Baldur's Gate: House1 L2"},~                                              @198
	REPLACE_TEXTUALLY ~{"BG1107", "SW Baldur's Gate: House2 L1"},~                                              @199
	REPLACE_TEXTUALLY ~{"BG1108", "SW Baldur's Gate: House2 L2"},~                                              @200
	REPLACE_TEXTUALLY ~{"BG1109", "SW Baldur's Gate: Tavern L1"},~                                              @201
	REPLACE_TEXTUALLY ~{"BG1110", "SW Baldur's Gate: Tavern L2"},~                                              @202
	REPLACE_TEXTUALLY ~{"BG1111", "SW Baldur's Gate: Sunin's House"},~                                          @203
	REPLACE_TEXTUALLY ~{"BG1112", "SW Baldur's Gate: Weapons Store 1"},~                                        @204
	REPLACE_TEXTUALLY ~{"BG1113", "SW Baldur's Gate: Ye Olde Inn L1"},~                                         @205
	REPLACE_TEXTUALLY ~{"BG1114", "SW Baldur's Gate: Ye Olde Inn L2"},~                                         @206
	REPLACE_TEXTUALLY ~{"BG1115", "SW Baldur's Gate: Potions Store 2"},~                                        @207
	REPLACE_TEXTUALLY ~{"BG1116", "SW Baldur's Gate: Weapons Store 2"},~                                        @208
	REPLACE_TEXTUALLY ~{"BG1117", "SW Baldur's Gate: Potions Store 1"},~                                        @209
	REPLACE_TEXTUALLY ~{"BG1200", "Baldur's Gate Docks"},~                                                      @210
	REPLACE_TEXTUALLY ~{"BG1201", "Baldur's Gate Docks: Ogre Magi House L1"},~                                  @211
	REPLACE_TEXTUALLY ~{"BG1202", "Baldur's Gate Docks: Ogre Magi House L2"},~                                  @212
	REPLACE_TEXTUALLY ~{"BG1203", "Baldur's Gate Docks: House2 L1"},~                                           @213
	REPLACE_TEXTUALLY ~{"BG1204", "Baldur's Gate Docks: House2 L2"},~                                           @214
	REPLACE_TEXTUALLY ~{"BG1205", "Baldur's Gate Docks: House1 L1"},~                                           @215
	REPLACE_TEXTUALLY ~{"BG1206", "Baldur's Gate Docks: House1 L2"},~                                           @216
	REPLACE_TEXTUALLY ~{"BG1207", "Baldur's Gate Docks: Basilisk Warehouse"},~                                  @217
	REPLACE_TEXTUALLY ~{"BG1208", "Baldur's Gate Docks: Noralee's Warehouse"},~                                 @218
	REPLACE_TEXTUALLY ~{"BG1209", "Baldur's Gate Docks: Larriaz' House L1"},~                                   @219
	REPLACE_TEXTUALLY ~{"BG1210", "Baldur's Gate Docks: Larriaz' House L2"},~                                   @220
	REPLACE_TEXTUALLY ~{"BG1211", "Baldur's Gate Docks: Ghorak's House L1"},~                                   @221
	REPLACE_TEXTUALLY ~{"BG1212", "Baldur's Gate Docks: Ghorak's House L2"},~                                   @222
	REPLACE_TEXTUALLY ~{"BG1213", "Baldur's Gate Docks: Cordyr's House L1"},~                                   @223
	REPLACE_TEXTUALLY ~{"BG1214", "Baldur's Gate Docks: Cordyr's House L2"},~                                   @224
	REPLACE_TEXTUALLY ~{"BG1215", "Baldur's Gate Docks: Jopalin's Tavern"},~                                    @225
	REPLACE_TEXTUALLY ~{"BG1300", "SE Baldur's Gate"},~                                                         @226
	REPLACE_TEXTUALLY ~{"BG1301", "SE Baldur's Gate: Warehouse"},~                                              @227
	REPLACE_TEXTUALLY ~{"BG1302", "SE Baldur's Gate: General Store 2"},~                                        @228
	REPLACE_TEXTUALLY ~{"BG1303", "SE Baldur's Gate: Nadarin's Warehouse"},~                                    @229
	REPLACE_TEXTUALLY ~{"BG1304", "SE Baldur's Gate: House3 L1"},~                                              @230
	REPLACE_TEXTUALLY ~{"BG1305", "SE Baldur's Gate: House3 L2"},~                                              @231
	REPLACE_TEXTUALLY ~{"BG1306", "SE Baldur's Gate: Inn L1"},~                                                 @232
	REPLACE_TEXTUALLY ~{"BG1307", "SE Baldur's Gate: Inn L2"},~                                                 @233
	REPLACE_TEXTUALLY ~{"BG1308", "SE Baldur's Gate: House4 L1"},~                                              @234
	REPLACE_TEXTUALLY ~{"BG1309", "SE Baldur's Gate: House4 L2"},~                                              @235
	REPLACE_TEXTUALLY ~{"BG1310", "SE Baldur's Gate: House2 L1"},~                                              @236
	REPLACE_TEXTUALLY ~{"BG1311", "SE Baldur's Gate: House2 L2"},~                                              @237
	REPLACE_TEXTUALLY ~{"BG1312", "SE Baldur's Gate: Gantolandan's House L1"},~                                 @238
	REPLACE_TEXTUALLY ~{"BG1313", "SE Baldur's Gate: Gantolandan's House L2"},~                                 @239
	REPLACE_TEXTUALLY ~{"BG1314", "SE Baldur's Gate: House1 L1"},~                                              @240
	REPLACE_TEXTUALLY ~{"BG1315", "SE Baldur's Gate: House1 L2"},~                                              @241
	REPLACE_TEXTUALLY ~{"BG1316", "SE Baldur's Gate: Taxek's House L1"},~                                       @242
	REPLACE_TEXTUALLY ~{"BG1317", "SE Baldur's Gate: Taxek's House L2"},~                                       @243
	REPLACE_TEXTUALLY ~{"BG1320", "SE Baldur's Gate: General Store 1"},~                                        @244
	REPLACE_TEXTUALLY ~{"BG1400", "Lower Chionthar"},~                                                          @245
	REPLACE_TEXTUALLY ~{"BG1401", "Lower Chionthar: Ankheg Pit"},~                                              @246
	REPLACE_TEXTUALLY ~{"BG1402", "Lower Chionthar: House1"},~                                                  @247
	REPLACE_TEXTUALLY ~{"BG1403", "Lower Chionthar: House2"},~                                                  @248
	REPLACE_TEXTUALLY ~{"BG1404", "Lower Chionthar: Farmer Brun's House"},~                                     @249
	REPLACE_TEXTUALLY ~{"BG1500", "Balduran's Isle (North)"},~                                                  @250
	REPLACE_TEXTUALLY ~{"BG1501", "Balduran's Isle (North): Ship D1"},~                                         @251
	REPLACE_TEXTUALLY ~{"BG1502", "Balduran's Isle (North): Ship D2"},~                                         @252
	REPLACE_TEXTUALLY ~{"BG1503", "Balduran's Isle (North): Ship D3"},~                                         @253
	REPLACE_TEXTUALLY ~{"BG1504", "Balduran's Isle (North): Ship D4"},~                                         @254
	REPLACE_TEXTUALLY ~{"BG1505", "Balduran's Isle (North): Dradeel's House"},~                                 @255
	REPLACE_TEXTUALLY ~{"BG1600", "Cloakwood Grove"},~                                                          @256
	REPLACE_TEXTUALLY ~{"BG1601", "Cloakwood Grove: Treehouse L1"},~                                            @257
	REPLACE_TEXTUALLY ~{"BG1602", "Cloakwood Grove: Treehouse L2"},~                                            @258
	REPLACE_TEXTUALLY ~{"BG1603", "Cloakwood Grove: Peter's Cave"},~                                            @259
	REPLACE_TEXTUALLY ~{"BG1700", "Cloakwood Crossings"},~                                                      @260
	REPLACE_TEXTUALLY ~{"BG1800", "Cloakwood Mines"},~                                                          @261
	REPLACE_TEXTUALLY ~{"BG1801", "Cloakwood Mines: L1"},~                                                      @262
	REPLACE_TEXTUALLY ~{"BG1802", "Cloakwood Mines: L3"},~                                                      @263
	REPLACE_TEXTUALLY ~{"BG1803", "Cloakwood Mines: L4"},~                                                      @264
	REPLACE_TEXTUALLY ~{"BG1804", "Cloakwood Mines: L2"},~                                                      @265
	REPLACE_TEXTUALLY ~{"BG1805", "Cloakwood Mines: Barracks L1"},~                                             @266
	REPLACE_TEXTUALLY ~{"BG1806", "Cloakwood Mines: Barracks L2"},~                                             @267
	REPLACE_TEXTUALLY ~{"BG1807", "Cloakwood Mines: Mine Lift"},~                                               @268
	REPLACE_TEXTUALLY ~{"BG1808", "Cloakwood Mines: Storehouse"},~                                              @269
	REPLACE_TEXTUALLY ~{"BG1809", "Cloakwood Mines: Mine Shed"},~                                               @270
	REPLACE_TEXTUALLY ~{"BG1900", "Bandit Camp"},~                                                              @271
	REPLACE_TEXTUALLY ~{"BG1901", "Bandit Camp: Raemon's Tent"},~                                               @272
	REPLACE_TEXTUALLY ~{"BG1902", "Bandit Camp: Tent2"},~                                                       @273
	REPLACE_TEXTUALLY ~{"BG1903", "Bandit Camp: Gnoll Cave"},~                                                  @274
	REPLACE_TEXTUALLY ~{"BG1904", "Bandit Camp: Tersus' Tent"},~                                                @275
	REPLACE_TEXTUALLY ~{"BG1905", "Bandit Camp: Tent1"},~                                                       @276
	REPLACE_TEXTUALLY ~{"BG1906", "Bandit Camp: Tent3"},~                                                       @277
	REPLACE_TEXTUALLY ~{"BG1907", "Bandit Camp: Tent4"},~                                                       @278
	REPLACE_TEXTUALLY ~{"BG2000", "Balduran's Isle (South)"},~                                                  @279
	REPLACE_TEXTUALLY ~{"BG2001", "Balduran's Isle (South): Great Hut"},~                                       @280
	REPLACE_TEXTUALLY ~{"BG2002", "Balduran's Isle (South): Kaishas' Hut"},~                                    @281
	REPLACE_TEXTUALLY ~{"BG2003", "Balduran's Isle (South): Large Hut 3"},~                                     @282
	REPLACE_TEXTUALLY ~{"BG2004", "Balduran's Isle (South): Large Hut 2"},~                                     @283
	REPLACE_TEXTUALLY ~{"BG2005", "Balduran's Isle (South): Large Hut 4"},~                                     @284
	REPLACE_TEXTUALLY ~{"BG2006", "Balduran's Isle (South): Large Hut 1"},~                                     @285
	REPLACE_TEXTUALLY ~{"BG2007", "Balduran's Isle (South): Harbor Hut"},~                                      @286
	REPLACE_TEXTUALLY ~{"BG2008", "Balduran's Isle (South): Store Hut 2"},~                                     @287
	REPLACE_TEXTUALLY ~{"BG2009", "Balduran's Isle (South): Store Hut 1"},~                                     @288
	REPLACE_TEXTUALLY ~{"BG2010", "Balduran's Isle (South): Store Hut 4"},~                                     @289
	REPLACE_TEXTUALLY ~{"BG2011", "Balduran's Isle (South): Store Hut 3"},~                                     @290
	REPLACE_TEXTUALLY ~{"BG2012", "Werewolf Caverns"},~                                                         @291
	REPLACE_TEXTUALLY ~{"BG2100", "Cloakwood Falls"},~                                                          @292
	REPLACE_TEXTUALLY ~{"BG2101", "Cloakwood Falls: Spider Nest"},~                                             @293
	REPLACE_TEXTUALLY ~{"BG2200", "Cloakwood Lodge"},~                                                          @294
	REPLACE_TEXTUALLY ~{"BG2215", "Cloakwood Lodge: Hunting Lodge"},~                                           @295
	REPLACE_TEXTUALLY ~{"BG2300", "Friendly Arm Inn"},~                                                         @296
	REPLACE_TEXTUALLY ~{"BG2301", "Friendly Arm Inn: L1"},~                                                     @297
	REPLACE_TEXTUALLY ~{"BG2302", "Friendly Arm Inn: L2"},~                                                     @298
	REPLACE_TEXTUALLY ~{"BG2303", "Friendly Arm Inn: L3"},~                                                     @299
	REPLACE_TEXTUALLY ~{"BG2304", "Friendly Arm Inn: Temple of Wisdom"},~                                       @300
	REPLACE_TEXTUALLY ~{"BG2305", "Friendly Arm Inn: House"},~                                                  @301
	REPLACE_TEXTUALLY ~{"BG2306", "Friendly Arm Inn: Joia's House"},~                                           @302
	REPLACE_TEXTUALLY ~{"BG2400", "Peldvale"},~                                                                 @303
	REPLACE_TEXTUALLY ~{"BG2600", "Candlekeep"},~                                                               @304
	REPLACE_TEXTUALLY ~{"BG2602", "Candlekeep: Priest's Quarters"},~                                            @305
	REPLACE_TEXTUALLY ~{"BG2605", "Candlekeep: Infirmary"},~                                                    @306
	REPLACE_TEXTUALLY ~{"BG2606", "Candlekeep: Storehouse"},~                                                   @307
	REPLACE_TEXTUALLY ~{"BG2607", "Candlekeep: Bunkhouse"},~                                                    @308
	REPLACE_TEXTUALLY ~{"BG2608", "Candlekeep: Library L1"},~                                                   @309
	REPLACE_TEXTUALLY ~{"BG2609", "Candlekeep: Library L2"},~                                                   @310
	REPLACE_TEXTUALLY ~{"BG2610", "Candlekeep: Library L3"},~                                                   @311
	REPLACE_TEXTUALLY ~{"BG2611", "Candlekeep: Library L4"},~                                                   @312
	REPLACE_TEXTUALLY ~{"BG2612", "Candlekeep: Library L5"},~                                                   @313
	REPLACE_TEXTUALLY ~{"BG2613", "Candlekeep: Catacombs L1 Antechamber"},~                                     @314
	REPLACE_TEXTUALLY ~{"BG2614", "Candlekeep: Library L6"},~                                                   @315
	REPLACE_TEXTUALLY ~{"BG2615", "Candlekeep: Catacombs L1"},~                                                 @316
	REPLACE_TEXTUALLY ~{"BG2616", "Candlekeep: Inn L1"},~                                                       @317
	REPLACE_TEXTUALLY ~{"BG2617", "Candlekeep: Inn L2"},~                                                       @318
	REPLACE_TEXTUALLY ~{"BG2618", "Candlekeep: Barracks"},~                                                     @319
	REPLACE_TEXTUALLY ~{"BG2619", "Candlekeep: Catacombs L2"},~                                                 @320
	REPLACE_TEXTUALLY ~{"BG2626", "Candlekeep: Ch.6"},~                                                         @321
	REPLACE_TEXTUALLY ~{"BG2627", "Candlekeep: Ch.6 Priest's Quarters"},~                                       @322
	REPLACE_TEXTUALLY ~{"BG2628", "Candlekeep: Infirmary"},~                                                    @323
	REPLACE_TEXTUALLY ~{"BG2629", "Candlekeep: Ch.6 Inn L1"},~                                                  @324
	REPLACE_TEXTUALLY ~{"BG2630", "Candlekeep: Ch.6 Inn L2"},~                                                  @325
	REPLACE_TEXTUALLY ~{"BG2631", "Candlekeep: Ch.6 Barracks"},~                                                @326
	REPLACE_TEXTUALLY ~{"BG2632", "Candlekeep: Ch.6 Bunkhouse"},~                                               @327
	REPLACE_TEXTUALLY ~{"BG2633", "Candlekeep: Ch.6 Infirmary"},~                                               @328
	REPLACE_TEXTUALLY ~{"BG2643", "Candlekeep: Obe's Cellar"},~                                                 @329
	REPLACE_TEXTUALLY ~{"BG2700", "Lion's Way"},~                                                               @330
	REPLACE_TEXTUALLY ~{"BG2800", "Coast Way"},~                                                                @331
	REPLACE_TEXTUALLY ~{"BG2900", "Larswood"},~                                                                 @332
	REPLACE_TEXTUALLY ~{"BG3000", "Spider Wood"},~                                                              @333
	REPLACE_TEXTUALLY ~{"BG3100", "Rocky Coast"},~                                                              @334
	REPLACE_TEXTUALLY ~{"BG3200", "High Hedge"},~                                                               @335
	REPLACE_TEXTUALLY ~{"BG3201", "High Hedge: House"},~                                                        @336
	REPLACE_TEXTUALLY ~{"BG3202", "High Hedge: Thalanthyr's Abode"},~                                           @337
	REPLACE_TEXTUALLY ~{"BG3300", "Beregost"},~                                                                 @338
	REPLACE_TEXTUALLY ~{"BG3301", "Beregost: Thunderhammer Smithy"},~                                           @339
	REPLACE_TEXTUALLY ~{"BG3302", "Beregost: House19"},~                                                        @340
	REPLACE_TEXTUALLY ~{"BG3303", "Beregost: Red Sheaf L2"},~                                                   @341
	REPLACE_TEXTUALLY ~{"BG3304", "Beregost: Jovial Juggler L1"},~                                              @342
	REPLACE_TEXTUALLY ~{"BG3305", "Beregost: Jovial Juggler L2F"},~                                             @343
	REPLACE_TEXTUALLY ~{"BG3306", "Beregost: Jovial Juggler L2R"},~                                             @344
	REPLACE_TEXTUALLY ~{"BG3307", "Beregost: Burning Wizard L1"},~                                              @345
	REPLACE_TEXTUALLY ~{"BG3308", "Beregost: Burning Wizard L2"},~                                              @346
	REPLACE_TEXTUALLY ~{"BG3309", "Beregost: House13 L1"},~                                                     @347
	REPLACE_TEXTUALLY ~{"BG3310", "Beregost: House13 L2"},~                                                     @348
	REPLACE_TEXTUALLY ~{"BG3311", "Beregost: House12 L1"},~                                                     @349
	REPLACE_TEXTUALLY ~{"BG3312", "Beregost: House12 L2"},~                                                     @350
	REPLACE_TEXTUALLY ~{"BG3313", "Beregost: Mirianne's House L1"},~                                            @351
	REPLACE_TEXTUALLY ~{"BG3314", "Beregost: Mirianne's House L2"},~                                            @352
	REPLACE_TEXTUALLY ~{"BG3315", "Beregost: Landrin's House"},~                                                @353
	REPLACE_TEXTUALLY ~{"BG3316", "Beregost: House18"},~                                                        @354
	REPLACE_TEXTUALLY ~{"BG3317", "Beregost: House17"},~                                                        @355
	REPLACE_TEXTUALLY ~{"BG3318", "Beregost: House15"},~                                                        @356
	REPLACE_TEXTUALLY ~{"BG3319", "Beregost: House16"},~                                                        @357
	REPLACE_TEXTUALLY ~{"BG3320", "Beregost: Travenhurst Manor L1"},~                                           @358
	REPLACE_TEXTUALLY ~{"BG3321", "Beregost: Travenhurst Manor L2"},~                                           @359
	REPLACE_TEXTUALLY ~{"BG3322", "Beregost: Servant's Quarters"},~                                             @360
	REPLACE_TEXTUALLY ~{"BG3323", "Beregost: House20 L1"},~                                                     @361
	REPLACE_TEXTUALLY ~{"BG3324", "Beregost: House20 L2"},~                                                     @362
	REPLACE_TEXTUALLY ~{"BG3325", "Beregost: House23 L1"},~                                                     @363
	REPLACE_TEXTUALLY ~{"BG3326", "Beregost: House23 L2"},~                                                     @364
	REPLACE_TEXTUALLY ~{"BG3327", "Beregost: House14 L1"},~                                                     @365
	REPLACE_TEXTUALLY ~{"BG3328", "Beregost: House14 L2"},~                                                     @366
	REPLACE_TEXTUALLY ~{"BG3329", "Beregost: House21 L1"},~                                                     @367
	REPLACE_TEXTUALLY ~{"BG3330", "Beregost: House21 L2"},~                                                     @368
	REPLACE_TEXTUALLY ~{"BG3331", "Beregost: House11 L1"},~                                                     @369
	REPLACE_TEXTUALLY ~{"BG3332", "Beregost: House11 L2"},~                                                     @370
	REPLACE_TEXTUALLY ~{"BG3333", "Beregost: Firebead's House L1"},~                                            @371
	REPLACE_TEXTUALLY ~{"BG3334", "Beregost: Firebead's House L2"},~                                            @372
	REPLACE_TEXTUALLY ~{"BG3335", "Beregost: House10 L1"},~                                                     @373
	REPLACE_TEXTUALLY ~{"BG3336", "Beregost: House10 L2"},~                                                     @374
	REPLACE_TEXTUALLY ~{"BG3337", "Beregost: House22 L1"},~                                                     @375
	REPLACE_TEXTUALLY ~{"BG3338", "Beregost: House22 L2"},~                                                     @376
	REPLACE_TEXTUALLY ~{"BG3339", "Beregost: House01 L1"},~                                                     @377
	REPLACE_TEXTUALLY ~{"BG3340", "Beregost: House01 L2"},~                                                     @378
	REPLACE_TEXTUALLY ~{"BG3341", "Beregost: House02 L1"},~                                                     @379
	REPLACE_TEXTUALLY ~{"BG3342", "Beregost: House02 L2"},~                                                     @380
	REPLACE_TEXTUALLY ~{"BG3343", "Beregost: House03"},~                                                        @381
	REPLACE_TEXTUALLY ~{"BG3344", "Beregost: House07"},~                                                        @382
	REPLACE_TEXTUALLY ~{"BG3345", "Beregost: House04 L1"},~                                                     @383
	REPLACE_TEXTUALLY ~{"BG3346", "Beregost: House04 L2"},~                                                     @384
	REPLACE_TEXTUALLY ~{"BG3347", "Beregost: House05 L1"},~                                                     @385
	REPLACE_TEXTUALLY ~{"BG3348", "Beregost: House05 L2"},~                                                     @386
	REPLACE_TEXTUALLY ~{"BG3349", "Beregost: House06 L1"},~                                                     @387
	REPLACE_TEXTUALLY ~{"BG3350", "Beregost: House06 L2"},~                                                     @388
	REPLACE_TEXTUALLY ~{"BG3351", "Beregost: Feldepost's Inn L1"},~                                             @389
	REPLACE_TEXTUALLY ~{"BG3352", "Beregost: Feldepost's Inn L2"},~                                             @390
	REPLACE_TEXTUALLY ~{"BG3353", "Beregost: Kagain's Store"},~                                                 @391
	REPLACE_TEXTUALLY ~{"BG3354", "Beregost: House09"},~                                                        @392
	REPLACE_TEXTUALLY ~{"BG3355", "Beregost: House08"},~                                                        @393
	REPLACE_TEXTUALLY ~{"BG3356", "Beregost: House08"},~                                                        @394
	REPLACE_TEXTUALLY ~{"BG3357", "Beregost: Red Sheaf L1"},~                                                   @395
	REPLACE_TEXTUALLY ~{"BG3400", "Temple of Lathander"},~                                                      @396
	REPLACE_TEXTUALLY ~{"BG3401", "Temple of Lathander: Vestibule"},~                                           @397
	REPLACE_TEXTUALLY ~{"BG3402", "Temple of Lathander: Song of the Morning"},~                                 @398
	REPLACE_TEXTUALLY ~{"BG3500", "Sharp Teeth Plain"},~                                                        @399
	REPLACE_TEXTUALLY ~{"BG3600", "Lighthouse"},~                                                               @400
	REPLACE_TEXTUALLY ~{"BG3601", "Lighthouse: Black Alaric's Cave"},~                                          @401
	REPLACE_TEXTUALLY ~{"BG3700", "Red Canyons"},~                                                              @402
	REPLACE_TEXTUALLY ~{"BG3800", "Trade Way North"},~                                                          @403
	REPLACE_TEXTUALLY ~{"BG3802", "Trade Way North: Cave"},~                                                    @404
	REPLACE_TEXTUALLY ~{"BG3900", "Ulcaster"},~                                                                 @405
	REPLACE_TEXTUALLY ~{"BG3901", "Ulcaster Ruins"},~                                                           @406
	REPLACE_TEXTUALLY ~{"BG4000", "Gullykin"},~                                                                 @407
	REPLACE_TEXTUALLY ~{"BG4001", "Gullykin: Jenkal's House L1"},~                                              @408
	REPLACE_TEXTUALLY ~{"BG4002", "Gullykin: Jenkal's House Cellar"},~                                          @409
	REPLACE_TEXTUALLY ~{"BG4003", "Gullykin: Winery L1"},~                                                      @410
	REPLACE_TEXTUALLY ~{"BG4004", "Gullykin: Winery Cellar"},~                                                  @411
	REPLACE_TEXTUALLY ~{"BG4005", "Gullykin: House1 L1"},~                                                      @412
	REPLACE_TEXTUALLY ~{"BG4006", "Gullykin: House1 Cellar"},~                                                  @413
	REPLACE_TEXTUALLY ~{"BG4007", "Gullykin: House3 L1"},~                                                      @414
	REPLACE_TEXTUALLY ~{"BG4008", "Gullykin: House3 Cellar"},~                                                  @415
	REPLACE_TEXTUALLY ~{"BG4009", "Gullykin: House4 L1"},~                                                      @416
	REPLACE_TEXTUALLY ~{"BG4010", "Gullykin: House4 Cellar"},~                                                  @417
	REPLACE_TEXTUALLY ~{"BG4011", "Gullykin: House5 L1"},~                                                      @418
	REPLACE_TEXTUALLY ~{"BG4012", "Gullykin: House5 Cellar"},~                                                  @419
	REPLACE_TEXTUALLY ~{"BG4013", "Gullykin: House2 L1"},~                                                      @420
	REPLACE_TEXTUALLY ~{"BG4014", "Gullykin: House2 Cellar"},~                                                  @421
	REPLACE_TEXTUALLY ~{"BG4100", "Ancient Ruins"},~                                                            @422
	REPLACE_TEXTUALLY ~{"BG4101", "Ancient Ruins: Tomb"},~                                                      @423
	REPLACE_TEXTUALLY ~{"BG4200", "Wilderness Lake"},~                                                          @424
	REPLACE_TEXTUALLY ~{"BG4300", "Trade Way South"},~                                                          @425
	REPLACE_TEXTUALLY ~{"BG4400", "Lonely Peaks"},~                                                             @426
	REPLACE_TEXTUALLY ~{"BG4401", "Lonely Peaks: Cave"},~                                                       @427
	REPLACE_TEXTUALLY ~{"BG4500", "Firewine Bridge"},~                                                          @428
	REPLACE_TEXTUALLY ~{"BG4501", "Cloakwood Crossings: Wyvern Cave"},~                                         @429
	REPLACE_TEXTUALLY ~{"BG4600", "Bear River"},~                                                               @430
	REPLACE_TEXTUALLY ~{"BG4700", "Xvart Village"},~                                                            @431
	REPLACE_TEXTUALLY ~{"BG4701", "Xvart Village: Cave"},~                                                      @432
	REPLACE_TEXTUALLY ~{"BG4800", "Nashkel"},~                                                                  @433
	REPLACE_TEXTUALLY ~{"BG4801", "Nashkel: Inn"},~                                                             @434
	REPLACE_TEXTUALLY ~{"BG4802", "Nashkel: Temple of Helm"},~                                                  @435
	REPLACE_TEXTUALLY ~{"BG4803", "Nashkel: Store"},~                                                           @436
	REPLACE_TEXTUALLY ~{"BG4804", "Nashkel: Manor House L1"},~                                                  @437
	REPLACE_TEXTUALLY ~{"BG4805", "Nashkel: Manor House L2"},~                                                  @438
	REPLACE_TEXTUALLY ~{"BG4806", "Nashkel: Joseph's House"},~                                                  @439
	REPLACE_TEXTUALLY ~{"BG4807", "Nashkel: House1"},~                                                          @440
	REPLACE_TEXTUALLY ~{"BG4808", "Nashkel: House2"},~                                                          @441
	REPLACE_TEXTUALLY ~{"BG4809", "Nashkel: Belching Dragon Tavern"},~                                          @442
	REPLACE_TEXTUALLY ~{"BG4810", "Nashkel: Garrison"},~                                                        @443
	REPLACE_TEXTUALLY ~{"BG4900", "Nashkel Carnival"},~                                                         @444
	REPLACE_TEXTUALLY ~{"BG4901", "Nashkel Carnival: Armor Tent"},~                                             @445
	REPLACE_TEXTUALLY ~{"BG4902", "Nashkel Carnival: Lotus Tent"},~                                             @446
	REPLACE_TEXTUALLY ~{"BG4903", "Nashkel Carnival: Vitiare's Tent"},~                                         @447
	REPLACE_TEXTUALLY ~{"BG4904", "Nashkel Carnival: Gambling Tent"},~                                          @448
	REPLACE_TEXTUALLY ~{"BG4905", "Nashkel Carnival: Potion Tent"},~                                            @449
	REPLACE_TEXTUALLY ~{"BG4906", "Nashkel Carnival: Zordral's Tent"},~                                         @450
	REPLACE_TEXTUALLY ~{"BG4907", "Nashkel Carnival: Magic Items Tent"},~                                       @451
	REPLACE_TEXTUALLY ~{"BG4908", "Nashkel Carnival: Melee Weapons Tent"},~                                     @452
	REPLACE_TEXTUALLY ~{"BG4909", "Nashkel Carnival: Ranged Weapons Tent"},~                                    @453
	REPLACE_TEXTUALLY ~{"BG5000", "Valley of the Tombs"},~                                                      @454
	REPLACE_TEXTUALLY ~{"BG5001", "Valley of the Tombs: Tomb"},~                                                @455
	REPLACE_TEXTUALLY ~{"BG5100", "Gnoll Stronghold"},~                                                         @456
	REPLACE_TEXTUALLY ~{"BG5101", "Gnoll Stronghold: Xvart Cave"},~                                             @457
	REPLACE_TEXTUALLY ~{"BG5102", "Gnoll Stronghold: Tome Cave"},~                                              @458
	REPLACE_TEXTUALLY ~{"BG5103", "Gnoll Stronghold: Crawler Cave"},~                                           @459
	REPLACE_TEXTUALLY ~{"BG5200", "Dryad Falls"},~                                                              @460
	REPLACE_TEXTUALLY ~{"BG5201", "Firewine Ruins"},~                                                           @461
	REPLACE_TEXTUALLY ~{"BG5202", "Dryad Falls: Cave"},~                                                        @462
	REPLACE_TEXTUALLY ~{"BG5300", "Fire Leaf Forest"},~                                                         @463
	REPLACE_TEXTUALLY ~{"BG5400", "Nashkel Mines"},~                                                            @464
	REPLACE_TEXTUALLY ~{"BG5401", "Nashkel Mines: L1"},~                                                        @465
	REPLACE_TEXTUALLY ~{"BG5402", "Nashkel Mines: L2"},~                                                        @466
	REPLACE_TEXTUALLY ~{"BG5403", "Nashkel Mines: L3"},~                                                        @467
	REPLACE_TEXTUALLY ~{"BG5404", "Nashkel Mines: L4"},~                                                        @468
	REPLACE_TEXTUALLY ~{"BG5405", "Nashkel Mines: Mulahey's Cave"},~                                            @469
	REPLACE_TEXTUALLY ~{"BG5406", "Nashkel Mines: Cabin"},~                                                     @470
	REPLACE_TEXTUALLY ~{"BG5500", "Gibberling Mountains"},~                                                     @471
	REPLACE_TEXTUALLY ~{"BG5506", "Candlekeep Caves"},~                                                         @472
	REPLACE_TEXTUALLY ~{"BG5600", "Random Encounter: Plains1"},~                                                @473
	REPLACE_TEXTUALLY ~{"BG5601", "Random Encounter: Plains2"},~                                                @474
	REPLACE_TEXTUALLY ~{"BG5700", "Random Encounter: Canyon1"},~                                                @475
	REPLACE_TEXTUALLY ~{"BG5701", "Random Encounter: Canyon2"},~                                                @476
	REPLACE_TEXTUALLY ~{"BG5800", "Random Encounter: Cliff1"},~                                                 @477
	REPLACE_TEXTUALLY ~{"BG5801", "Random Encounter: Cliff2"},~                                                 @478
	REPLACE_TEXTUALLY ~{"BG5900", "Random Encounter: Grassland1"},~                                             @479
	REPLACE_TEXTUALLY ~{"BG5901", "Random Encounter: Grassland2"},~                                             @480
	REPLACE_TEXTUALLY ~{"BG6000", "Random Encounter: Forest1"},~                                                @481
	REPLACE_TEXTUALLY ~{"BG6001", "Random Encounter: Forest2"},~                                                @482
	REPLACE_TEXTUALLY ~{"BG6100", "Random Encounter: Road"},~                                                   @483
	REPLACE_TEXTUALLY ~{"OH2000", "Adoy's Enclave"},~                                                           @484                                                           	
	REPLACE_TEXTUALLY ~{"OH3000", "Cloud Peaks"},~                                                              @485                                                                                       
	
	// CheatsAreas Les Fosses noires~
	
	REPLACE_TEXTUALLY ~{"OH9310", "TBP - Arena 1"},~                                                            @486
	REPLACE_TEXTUALLY ~{"OH9350", "TBP - Arena 2"},~                                                            @487
	REPLACE_TEXTUALLY ~{"OH9360", "TBP - Staging Area Map"},~                                                   @488
	                                                                                                            
	// CheatsAreas Tutoriel~                                                                                    	
	                                                                                                            
	REPLACE_TEXTUALLY ~{"TU0015", "Baldur's Gate Estate (Tutorial starts here)"},~                              @489
	REPLACE_TEXTUALLY ~{"TU0016", "Baldur's Gate Estate (Tutorial area)"},~                                     @490
	REPLACE_TEXTUALLY ~{"TU0017", "Baldur's Gate Estate (Tutorial area)"},~                                     @491
	REPLACE_TEXTUALLY ~{"TU0018", "Baldur's Gate Estate Cellar (Tutorial area)"},~                              @492
	
	// CheatsAreas pour SoD~                                                                                            
																														
	REPLACE_TEXTUALLY ~{"BD0010", "Ducal Palace City Exterior"},~                                                       @493
	REPLACE_TEXTUALLY ~{"BD0020", "Sorcerous/Elf Song City Exterior"},~                                                 @494
	REPLACE_TEXTUALLY ~{"BD0030", "Flaming Fist City Exterior"},~                                                       @495
	REPLACE_TEXTUALLY ~{"BD0040", "Three Kegs City Exterior"},~                                                         @496
	REPLACE_TEXTUALLY ~{"BD0050", "Iron Throne City Exterior"},~                                                        @497
	REPLACE_TEXTUALLY ~{"BD0060", "Random Area - Cave Entrance"},~                                                      @498
	REPLACE_TEXTUALLY ~{"BD0061", "Random Area - Cave Interior from BD0060"},~                                          @499
	REPLACE_TEXTUALLY ~{"BD0062", "Random Area - Cave Pool from BD0061"},~                                              @500
	REPLACE_TEXTUALLY ~{"BD0063", "Random Area - Canyon Ambush"},~                                                      @501
	REPLACE_TEXTUALLY ~{"BD0064", "Random Area - Forest Paths"},~                                                       @502
	REPLACE_TEXTUALLY ~{"BD0065", "Random Area - Wilderness Open Area"},~                                               @503
	REPLACE_TEXTUALLY ~{"BD0066", "Random Area - Wilderness Hole to BD0067"},~                                          @504
	REPLACE_TEXTUALLY ~{"BD0067", "Random Area - Cave Interior from BD0066"},~                                          @505
	REPLACE_TEXTUALLY ~{"BD0070", "The Scrying Pool - The Hooded Man Cutscene"},~                                       @506
	REPLACE_TEXTUALLY ~{"BD0071", "The Scrying Pool - Caelar Cutscene"},~                                               @507
	REPLACE_TEXTUALLY ~{"BD0100", "Ducal Palace  Second Floor"},~                                                       @508
	REPLACE_TEXTUALLY ~{"BD0101", "Ducal Palace  Leaving BG"},~                                                         @509
	REPLACE_TEXTUALLY ~{"BD0102", "Ducal Palace  First Floor"},~                                                        @510
	REPLACE_TEXTUALLY ~{"BD0103", "Ducal Palace  Third Floor"},~                                                        @511
	REPLACE_TEXTUALLY ~{"BD0104", "Flaming Fist HQ"},~                                                                  @512
	REPLACE_TEXTUALLY ~{"BD0105", "Flaming Fist HQ  Basement"},~                                                        @513
	REPLACE_TEXTUALLY ~{"BD0106", "Three Old Kegs  First Floor"},~                                                      @514
	REPLACE_TEXTUALLY ~{"BD0107", "Three Old Kegs  Second Floor"},~                                                     @515
	REPLACE_TEXTUALLY ~{"BD0108", "Three Old Kegs  Third Floor"},~                                                      @516
	REPLACE_TEXTUALLY ~{"BD0109", "Elfsong Tavern  First Floor"},~                                                      @517
	REPLACE_TEXTUALLY ~{"BD0110", "Elfsong Tavern  Second Floor"},~                                                     @518
	REPLACE_TEXTUALLY ~{"BD0111", "Iron Throne Floor  First Floor"},~                                                   @519
	REPLACE_TEXTUALLY ~{"BD0112", "Baldur s Gate East"},~                                                               @520
	REPLACE_TEXTUALLY ~{"BD0113", "Underground Cavern Wyrms"},~                                                         @521
	REPLACE_TEXTUALLY ~{"BD0114", "Spider Cave"},~                                                                      @522
	REPLACE_TEXTUALLY ~{"BD0115", "Vampire Cavern"},~                                                                   @523
	REPLACE_TEXTUALLY ~{"BD0116", "Ducal Palace, Basement"},~                                                           @524
	REPLACE_TEXTUALLY ~{"BD0117", "Iron Throne  Basement"},~                                                            @525
	REPLACE_TEXTUALLY ~{"BD0118", "The Scrying Pool - Imoen Cutscene"},~                                                @526
	REPLACE_TEXTUALLY ~{"BD0120", "Tomb Safehouse  First Floor"},~                                                      @527
	REPLACE_TEXTUALLY ~{"BD0121", "Sorcerous Sundries  First Floor"},~                                                  @528
	REPLACE_TEXTUALLY ~{"BD0122", "Sorcerous Sundries  Second Floor"},~                                                 @529
	REPLACE_TEXTUALLY ~{"BD0130", "Tomb Safehouse  Second Floor"},~                                                     @530
	REPLACE_TEXTUALLY ~{"BD1000", "Coast Way Crossing"},~                                                               @531
	REPLACE_TEXTUALLY ~{"BD1010", "Cave (generic)"},~                                                                   @532
	REPLACE_TEXTUALLY ~{"BD1100", "The Dig"},~                                                                          @533
	REPLACE_TEXTUALLY ~{"BD1200", "Lich Outpost"},~                                                                     @534
	REPLACE_TEXTUALLY ~{"BD2000", "Boareskyr Bridge & Bridgefort"},~                                                    @535
	REPLACE_TEXTUALLY ~{"BD2010", "Cave (generic)"},~                                                                   @536
	REPLACE_TEXTUALLY ~{"BD2100", "Bridgefort Interior"},~                                                              @537
	REPLACE_TEXTUALLY ~{"BD3000", "Allied Siege Camp"},~                                                                @538
	REPLACE_TEXTUALLY ~{"BD4000", "Dragonspear Castle  Exterior"},~                                                     @539
	REPLACE_TEXTUALLY ~{"BD4100", "Dragonspear Castle Keep  First Floor"},~                                             @540
	REPLACE_TEXTUALLY ~{"BD4300", "Dragonspear Castle Basement"},~                                                      @541
	REPLACE_TEXTUALLY ~{"BD4400", "Avernus"},~                                                                          @542
	REPLACE_TEXTUALLY ~{"BD4500", "Avernus Bridge"},~                                                                   @543
	REPLACE_TEXTUALLY ~{"BD4600", "Avernus Interior"},~                                                                 @544
	REPLACE_TEXTUALLY ~{"BD4601", "Avernus Elevator"},~                                                                 @545
	REPLACE_TEXTUALLY ~{"BD4700", "Avernus Roof"},~                                                                     @546
	REPLACE_TEXTUALLY ~{"BD5000", "Underground River Entrance"},~                                                       @547
	REPLACE_TEXTUALLY ~{"BD5100", "Underground River"},~                                                                @548
	REPLACE_TEXTUALLY ~{"BD5110", "Ettin Ghost Cave"},~                                                                 @549
	REPLACE_TEXTUALLY ~{"BD5200", "The Warrens"},~                                                                      @550
	REPLACE_TEXTUALLY ~{"BD5300", "Kanaglym"},~                                                                         @551
	REPLACE_TEXTUALLY ~{"BD6000", "Abandoned Sewers & Caverns"},~                                                       @552
	REPLACE_TEXTUALLY ~{"BD6200", "Sewers Exit"},~                                                                      @553
	REPLACE_TEXTUALLY ~{"BD6100", "The Ambush"},~                                                                       @554
	REPLACE_TEXTUALLY ~{"BD7000", "Coast Way Forest"},~                                                                 @555
	REPLACE_TEXTUALLY ~{"BD7100", "Troll Forest"},~                                                                     @556
	REPLACE_TEXTUALLY ~{"BD7110", "Troll Cave"},~                                                                       @557
	REPLACE_TEXTUALLY ~{"BD7200", "Forest of Wyrms"},~                                                                  @558
	REPLACE_TEXTUALLY ~{"BD7210", "Wyrm Cave"},~                                                                        @559
	REPLACE_TEXTUALLY ~{"BD7220", "Bugbear Stronghold"},~                                                               @560
	REPLACE_TEXTUALLY ~{"BD7230", "Temple of Cyric"},~                                                                  @561
	REPLACE_TEXTUALLY ~{"BD7300", "Dead Man s Pass"},~                                                                  @562
	REPLACE_TEXTUALLY ~{"BD7310", "Hidden Cellar/Treasure Stash"},~                                                     @563
	REPLACE_TEXTUALLY ~{"BD7400", "Bloodbark Grove"},~                                                                  @564
	REPLACE_TEXTUALLY ~{"BD7410", "Vampire Hideout"},~                                                                  @565
                                                                                                                        
	// CheatsAreas SoA                                                                                                  	
																														
	REPLACE_TEXTUALLY ~{"AR0011", "Candlekeep Dream 1 (Do you remember Candlekeep\?)"},~                                 @566
	REPLACE_TEXTUALLY ~{"AR0012", "Candlekeep Library (Main Door Trigger)"},~                                           @567
	REPLACE_TEXTUALLY ~{"AR0013", "Candlekeep Library (Stairway Triggers Up and Down)"},~                               @568
	REPLACE_TEXTUALLY ~{"AR0014", "Candlekeep Library (Stairway Trigger Down)"},~                                       @569
	REPLACE_TEXTUALLY ~{"AR0020", "City Gates"},~                                                                       @570
	REPLACE_TEXTUALLY ~{"AR0021", "Crooked Crane 1st Floor"},~                                                          @571
	REPLACE_TEXTUALLY ~{"AR0022", "Crooked Crane 2nd Floor"},~                                                          @572
	REPLACE_TEXTUALLY ~{"AR0028", "Candlekeep Dream (After PC Soultheft)"},~                                            @573
	REPLACE_TEXTUALLY ~{"AR0041", "Random Encounter City"},~                                                            @574
	REPLACE_TEXTUALLY ~{"AR0042", "Random Encounter Outdoor"},~                                                         @575
	REPLACE_TEXTUALLY ~{"AR0043", "Random Encounter Outdoor (With rocks)"},~                                            @576
	REPLACE_TEXTUALLY ~{"AR0044", "Random Encounter Outdoor (sand)"},~                                                  @577
	REPLACE_TEXTUALLY ~{"AR0045", "Random Encounter City"},~                                                            @578
	REPLACE_TEXTUALLY ~{"AR0046", "Random Encounter City (bridge)"},~                                                   @579
	REPLACE_TEXTUALLY ~{"AR0060", "Empty (Triggers, Doors... are there but no area)"},~                                 @580
	REPLACE_TEXTUALLY ~{"AR0061", "Empty (Triggers, Doors... are there but no area)"},~                                 @581
	REPLACE_TEXTUALLY ~{"AR0062", "Empty (Triggers, Doors... are there but no area)"},~                                 @582
	REPLACE_TEXTUALLY ~{"AR0063", "Empty (Triggers, Doors... are there but no area)"},~                                 @583
	REPLACE_TEXTUALLY ~{"AR0064", "Empty (Triggers, Doors... are there but no area)"},~                                 @584
	REPLACE_TEXTUALLY ~{"AR0065", "Empty (Triggers, Doors... are there but no area)"},~                                 @585
	REPLACE_TEXTUALLY ~{"AR0069", "Government Building (Cowled Cutscene -- 'Why is this man not gagged\?')"},~           @586
	REPLACE_TEXTUALLY ~{"AR0070", "Spellhold (Irenicus Cutscene -- 'I cannot be caged...')"},~                          @587
	REPLACE_TEXTUALLY ~{"AR0071", "Spellhold (Imoen Soultheft Cutscene -- 'Silence do, you have no purpose...')"},~     @588
	REPLACE_TEXTUALLY ~{"AR0072", "Ust Natha Temple (Irenicus/Bodhi, Ardula/Phaere Cutscene)"},~                        @589
	REPLACE_TEXTUALLY ~{"AR0082", "Lich Grave in Bridge District Inn"},~                                                @590
	REPLACE_TEXTUALLY ~{"AR0083", "Candlekeep Library (Dream: PC learns to control the Slayer)"},~                      @591
	REPLACE_TEXTUALLY ~{"AR0084", "Candlekeep Library (Stairway trigger down)"},~                                       @592
	REPLACE_TEXTUALLY ~{"AR0085", "Tree of Life"},~                                                                     @593
	REPLACE_TEXTUALLY ~{"AR0086", "Wooded Area"},~                                                                      @594
	REPLACE_TEXTUALLY ~{"AR0087", "Elven Dining Room"},~                                                                @595
	REPLACE_TEXTUALLY ~{"AR0201", "Leading to ghoul village and beholder lair (Temple District)"},~                     @596
	REPLACE_TEXTUALLY ~{"AR0202", "The Unseeing Eye Cult Hideout"},~                                                    @597
	REPLACE_TEXTUALLY ~{"AR0203", "Temple of the Forgotten God -- Amaunator (Unseeing Eye Plot)"},~                     @598
	REPLACE_TEXTUALLY ~{"AR0204", "The Forgotten Believers -- Temple City (Unseeing Eye Plot)"},~                       @599
	REPLACE_TEXTUALLY ~{"AR0205", "The Beholder Hideout (Unseeing Eye Plot)"},~                                         @600
	REPLACE_TEXTUALLY ~{"AR0206", "Ghoul village (Temple District)"},~                                                  @601
	REPLACE_TEXTUALLY ~{"AR0300", "The Docks"},~                                                                        @602
	REPLACE_TEXTUALLY ~{"AR0301", "Mae'Var's Hide Out"},~                                                               @603
	REPLACE_TEXTUALLY ~{"AR0302", "Mae'Var's Inn 1st Floor -- Entrance"},~                                              @604
	REPLACE_TEXTUALLY ~{"AR0303", "Mae'Var's Inn 2nd Floor -- Training Area"},~                                         @605
	REPLACE_TEXTUALLY ~{"AR0304", "Mae'Var's Inn 3rd Floor -- Edwin"},~                                                 @606
	REPLACE_TEXTUALLY ~{"AR0305", "Shadow Thieves Guild Entrance"},~                                                    @607
	REPLACE_TEXTUALLY ~{"AR0306", "Renal Bloodscalp's Hideout"},~                                                       @608
	REPLACE_TEXTUALLY ~{"AR0307", "Aran Linvail's Hideout"},~                                                           @609
	REPLACE_TEXTUALLY ~{"AR0308", "Harper's 1st Floor"},~                                                               @610
	REPLACE_TEXTUALLY ~{"AR0309", "Harper's 2nd Floor"},~                                                               @611
	REPLACE_TEXTUALLY ~{"AR0310", "Pirates' Hideout in Sea Bounty Tavern"},~                                            @612
	REPLACE_TEXTUALLY ~{"AR0311", "Living Room (Entry points outside and up) -- Gaelan\?"},~                             @613
	REPLACE_TEXTUALLY ~{"AR0312", "Sleeping Room (Entry point down) -- Arledrian"},~                                    @614
	REPLACE_TEXTUALLY ~{"AR0313", "Sea Bounty Tavern 1st Floor"},~                                                      @615
	REPLACE_TEXTUALLY ~{"AR0314", "Sea Bounty Tavern 2nd Floor"},~                                                      @616
	REPLACE_TEXTUALLY ~{"AR0315", "Living Room (Favour for Edwin -- Mae'Var Plot)"},~                                   @617
	REPLACE_TEXTUALLY ~{"AR0316", "Sleeping Room (Favour for Edwin -- Mae'Var Plot)"},~                                 @618
	REPLACE_TEXTUALLY ~{"AR0317", "Sleeping Room (Favour for Edwin -- Mae'Var Plot)"},~                                 @619
	REPLACE_TEXTUALLY ~{"AR0318", "Storage Room"},~                                                                     @620
	REPLACE_TEXTUALLY ~{"AR0319", "Temple of Oghma"},~                                                                  @621
	REPLACE_TEXTUALLY ~{"AR0321", "Thief Stronghold (Hideout)"},~                                                       @622
	REPLACE_TEXTUALLY ~{"AR0322", "Thief Stronghold (1st Floor)"},~                                                     @623
	REPLACE_TEXTUALLY ~{"AR0323", "Thief Stronghold (2nd Floor)"},~                                                     @624
	REPLACE_TEXTUALLY ~{"AR0324", "Thief Stronghold (3rd Floor)"},~                                                     @625
	REPLACE_TEXTUALLY ~{"AR0325", "Corthala House 1st Floor"},~                                                         @626
	REPLACE_TEXTUALLY ~{"AR0326", "Corthala House 2nd Floor"},~                                                         @627
	REPLACE_TEXTUALLY ~{"AR0327", "Shadow Thief Entrance (sided with Bodhi)"},~                                         @628
	REPLACE_TEXTUALLY ~{"AR0328", "Shadow Thief 1st Floor (sided with Bodhi)"},~                                        @629
	REPLACE_TEXTUALLY ~{"AR0329", "Aran's Hideout (sided with Bodhi)"},~                                                @630
	REPLACE_TEXTUALLY ~{"AR0330", "House 1st Floor (Kangaxx)"},~                                                        @631
	REPLACE_TEXTUALLY ~{"AR0331", "House Cellar (Kangaxx)"},~                                                           @632
	REPLACE_TEXTUALLY ~{"AR0332", "Barracks in the Docks"},~                                                            @633
	REPLACE_TEXTUALLY ~{"AR0333", "Barracks in the Docks"},~                                                            @634
	REPLACE_TEXTUALLY ~{"AR0334", "Cromwell's Shop"},~                                                                  @635
	REPLACE_TEXTUALLY ~{"AR0335", "Sleeping Room"},~                                                                    @636
	REPLACE_TEXTUALLY ~{"AR0400", "Slums"},~                                                                            @637
	REPLACE_TEXTUALLY ~{"AR0401", "Jansen Cellar"},~                                                                    @638
	REPLACE_TEXTUALLY ~{"AR0402", "Jansen 1st Floor"},~                                                                 @639
	REPLACE_TEXTUALLY ~{"AR0403", "Jansen 2nd Floor"},~                                                                 @640
	REPLACE_TEXTUALLY ~{"AR0404", "Sewers beneath Coronet -- Lilarcor"},~                                               @641
	REPLACE_TEXTUALLY ~{"AR0405", "Slaver's Ship Building"},~                                                           @642
	REPLACE_TEXTUALLY ~{"AR0406", "Copper Coronet"},~                                                                   @643
	REPLACE_TEXTUALLY ~{"AR0407", "Prebek's House"},~                                                                   @644
	REPLACE_TEXTUALLY ~{"AR0408", "Temple of Ilmater"},~                                                                @645
	REPLACE_TEXTUALLY ~{"AR0409", "Living Room (Ployer's home)"},~                                                      @646
	REPLACE_TEXTUALLY ~{"AR0410", "Sphere: Navigator's room -- Lavok's Hideout"},~                                      @647
	REPLACE_TEXTUALLY ~{"AR0411", "Sphere: Entrance floor"},~                                                           @648
	REPLACE_TEXTUALLY ~{"AR0412", "Sphere: Ice and Fire Room"},~                                                        @649
	REPLACE_TEXTUALLY ~{"AR0413", "Sphere: Enginge Room"},~                                                             @650
	REPLACE_TEXTUALLY ~{"AR0414", "Sphere: Demon Plane"},~                                                              @651
	REPLACE_TEXTUALLY ~{"AR0415", "Living Room 1st Floor"},~                                                            @652
	REPLACE_TEXTUALLY ~{"AR0416", "Living Room 2nd Floor"},~                                                            @653
	REPLACE_TEXTUALLY ~{"AR0417", "Living Room"},~                                                                      @654
	REPLACE_TEXTUALLY ~{"AR0418", "Myconids"},~                                                                         @655
	REPLACE_TEXTUALLY ~{"AR0419", "Myconid"},~                                                                          @656
	REPLACE_TEXTUALLY ~{"AR0420", "Sphere: Lizardmen Hideout"},~                                                        @657
	REPLACE_TEXTUALLY ~{"AR0500", "Bridge District"},~                                                                  @658
	REPLACE_TEXTUALLY ~{"AR0501", "Tanner's Hideout 1st Floor"},~                                                       @659
	REPLACE_TEXTUALLY ~{"AR0502", "Tanner's Hideout Cellar"},~                                                          @660
	REPLACE_TEXTUALLY ~{"AR0503", "Tanner's Hideout Dock"},~                                                            @661
	REPLACE_TEXTUALLY ~{"AR0504", "Saerk's House 1st Floor"},~                                                          @662
	REPLACE_TEXTUALLY ~{"AR0505", "Saerk's House 2nd Floor"},~                                                          @663
	REPLACE_TEXTUALLY ~{"AR0506", "Noble House 1st Floor"},~                                                            @664
	REPLACE_TEXTUALLY ~{"AR0507", "Kidnappers' Hideout 1st Floor"},~                                                    @665
	REPLACE_TEXTUALLY ~{"AR0508", "Kidnappers' Hideout 2nd Floor"},~                                                    @666
	REPLACE_TEXTUALLY ~{"AR0509", "Five Flagons Inn 1st Floor"},~                                                       @667
	REPLACE_TEXTUALLY ~{"AR0510", "Five Flagons Inn Theater"},~                                                         @668
	REPLACE_TEXTUALLY ~{"AR0511", "Five Flagons Inn 2nd Floor"},~                                                       @669
	REPLACE_TEXTUALLY ~{"AR0512", "Temple of Helm"},~                                                                   @670
	REPLACE_TEXTUALLY ~{"AR0513", "Calbor's Inn at Bridge District 1st Floor"},~                                        @671
	REPLACE_TEXTUALLY ~{"AR0514", "Inn at Bridge District 2nd Floor"},~                                                 @672
	REPLACE_TEXTUALLY ~{"AR0515", "Inn at Bridge District 3rd Floor"},~                                                 @673
	REPLACE_TEXTUALLY ~{"AR0516", "Planar Prison"},~                                                                    @674
	REPLACE_TEXTUALLY ~{"AR0517", "Planar Prison Cell"},~                                                               @675
	REPLACE_TEXTUALLY ~{"AR0518", "Planar Prison Cell"},~                                                               @676
	REPLACE_TEXTUALLY ~{"AR0519", "Planar Prison Cell"},~                                                               @677
	REPLACE_TEXTUALLY ~{"AR0520", "Planar Prison Cell"},~                                                               @678
	REPLACE_TEXTUALLY ~{"AR0521", "Planar Prison Cell"},~                                                               @679
	REPLACE_TEXTUALLY ~{"AR0522", "Five Flagons Inn (Stronghold)"},~                                                    @680
	REPLACE_TEXTUALLY ~{"AR0523", "Five Flagons Theater (Stronghold)"},~                                                @681
	REPLACE_TEXTUALLY ~{"AR0525", "House 1st Floor"},~                                                                  @682
	REPLACE_TEXTUALLY ~{"AR0526", "Sarcophagus Cellar"},~                                                               @683
	REPLACE_TEXTUALLY ~{"AR0527", "House 1st Floor"},~                                                                  @684
	REPLACE_TEXTUALLY ~{"AR0528", "House 2nd Floor"},~                                                                  @685
	REPLACE_TEXTUALLY ~{"AR0529", "Neb's Hideout"},~                                                                    @686
	REPLACE_TEXTUALLY ~{"AR0530", "Storehouse"},~                                                                       @687
	REPLACE_TEXTUALLY ~{"AR0531", "Commoner House"},~                                                                   @688
	REPLACE_TEXTUALLY ~{"AR0600", "Circus Tent (phased)"},~                                                             @689
	REPLACE_TEXTUALLY ~{"AR0601", "Air Plane in Irenicus's Dungeon"},~                                                  @690
	REPLACE_TEXTUALLY ~{"AR0602", "Irenicus's Dungeon 1st Floor"},~                                                     @691
	REPLACE_TEXTUALLY ~{"AR0603", "Irenicus's Dungeon 2nd Floor"},~                                                     @692
	REPLACE_TEXTUALLY ~{"AR0604", "Circus Tent 1st Floor"},~                                                            @693
	REPLACE_TEXTUALLY ~{"AR0605", "Circus Tent 2nd Floor"},~                                                            @694
	REPLACE_TEXTUALLY ~{"AR0606", "Circus Tent 3rd Floor"},~                                                            @695
	REPLACE_TEXTUALLY ~{"AR0607", "Circus Tent restored"},~                                                             @696
	REPLACE_TEXTUALLY ~{"AR0700", "Waukeen's Promenade"},~                                                              @697
	REPLACE_TEXTUALLY ~{"AR0701", "The Sewers"},~                                                                       @698
	REPLACE_TEXTUALLY ~{"AR0702", "Adventurer's Mart"},~                                                                @699
	REPLACE_TEXTUALLY ~{"AR0703", "Temple of Ilmater"},~                                                                @700
	REPLACE_TEXTUALLY ~{"AR0704", "Mithrest Inn"},~                                                                     @701
	REPLACE_TEXTUALLY ~{"AR0705", "Mekrath's Hideout in the Sewers (Haer'Dalis Plot)"},~                                @702
	REPLACE_TEXTUALLY ~{"AR0706", "Armourer/Fletcher"},~                                                                @703
	REPLACE_TEXTUALLY ~{"AR0707", "Enge's Shop"},~                                                                      @704
	REPLACE_TEXTUALLY ~{"AR0708", "Cernd's former home"},~                                                              @705
	REPLACE_TEXTUALLY ~{"AR0709", "Den of the Seven Vales 1st Floor"},~                                                 @706
	REPLACE_TEXTUALLY ~{"AR0710", "Fennecia's Home"},~                                                                  @707
	REPLACE_TEXTUALLY ~{"AR0711", "Illithid Hideout in the Sewers (The Hidden Plot)"},~                                 @708
	REPLACE_TEXTUALLY ~{"AR0712", "Den of the Seven Vales 2nd Floor"},~                                                 @709
	REPLACE_TEXTUALLY ~{"AR0713", "Store or Inn at Promenade"},~                                                        @710
	REPLACE_TEXTUALLY ~{"AR0714", "Debris at Waukeen's Promenade (Irenicus Cutscene in the beginning)"},~               @711
	REPLACE_TEXTUALLY ~{"AR0800", "Graveyard"},~                                                                        @712
	REPLACE_TEXTUALLY ~{"AR0801", "Bodhi's Hideout (sided with Aran)"},~                                                @713
	REPLACE_TEXTUALLY ~{"AR0802", "Netherscroll, Korgan's Book, Edwin"},~                                               @714
	REPLACE_TEXTUALLY ~{"AR0803", "Bodhi's Lair (sided with Aran)"},~                                                   @715
	REPLACE_TEXTUALLY ~{"AR0804", "Pai'Na's Hideout"},~                                                                 @716
	REPLACE_TEXTUALLY ~{"AR0805", "Crypt"},~                                                                            @717
	REPLACE_TEXTUALLY ~{"AR0806", "Crypt"},~                                                                            @718
	REPLACE_TEXTUALLY ~{"AR0807", "Crypt"},~                                                                            @719
	REPLACE_TEXTUALLY ~{"AR0808", "Bodhi's Hideout (Abduction Plot, getting Imoen's soul)"},~                           @720
	REPLACE_TEXTUALLY ~{"AR0809", "Bodhi's Lair (Abduction Plot, getting Imoen's soul)"},~                              @721
	REPLACE_TEXTUALLY ~{"AR0810", "Crypt"},~                                                                            @722
	REPLACE_TEXTUALLY ~{"AR0811", "Crypt"},~                                                                            @723
	REPLACE_TEXTUALLY ~{"AR0812", "Crypt"},~                                                                            @724
	REPLACE_TEXTUALLY ~{"AR0813", "Crypt"},~                                                                            @725
	REPLACE_TEXTUALLY ~{"AR0900", "Temple District"},~                                                                  @726
	REPLACE_TEXTUALLY ~{"AR0901", "Temple of Helm"},~                                                                   @727
	REPLACE_TEXTUALLY ~{"AR0902", "Temple of Lathander"},~                                                              @728
	REPLACE_TEXTUALLY ~{"AR0903", "Order of the Radiant Heart"},~                                                       @729
	REPLACE_TEXTUALLY ~{"AR0904", "Temple of Talos"},~                                                                  @730
	REPLACE_TEXTUALLY ~{"AR0905", "Pimlico's Estate"},~                                                                 @731
	REPLACE_TEXTUALLY ~{"AR0906", "Guarded Compound 1st Floor"},~                                                       @732
	REPLACE_TEXTUALLY ~{"AR0907", "Guarded Compound 2nd Floor"},~                                                       @733
	REPLACE_TEXTUALLY ~{"AR1000", "Government District"},~                                                              @734
	REPLACE_TEXTUALLY ~{"AR1001", "Delryn's Estate"},~                                                                  @735
	REPLACE_TEXTUALLY ~{"AR1002", "Councel Building"},~                                                                 @736
	REPLACE_TEXTUALLY ~{"AR1003", "Firecam's Estate"},~                                                                 @737
	REPLACE_TEXTUALLY ~{"AR1004", "Deril's Estate (Cernd Plot)"},~                                                      @738
	REPLACE_TEXTUALLY ~{"AR1005", "Prison"},~                                                                           @739
	REPLACE_TEXTUALLY ~{"AR1006", "Jysstev's Estate (Oisig Plot)"},~                                                    @740
	REPLACE_TEXTUALLY ~{"AR1007", "Noble House"},~                                                                      @741
	REPLACE_TEXTUALLY ~{"AR1008", "Twisted Rune"},~                                                                     @742
	REPLACE_TEXTUALLY ~{"AR1009", "Noble House (Isaea Roenall's)"},~                                                    @743
	REPLACE_TEXTUALLY ~{"AR1010", "Temple of Waukeen"},~                                                                @744
	REPLACE_TEXTUALLY ~{"AR1100", "Umar Hills"},~                                                                       @745
	REPLACE_TEXTUALLY ~{"AR1101", "Valygar's Cabin"},~                                                                  @746
	REPLACE_TEXTUALLY ~{"AR1102", "Merella's Cabin"},~                                                                  @747
	REPLACE_TEXTUALLY ~{"AR1103", "Jermien's Cabin"},~                                                                  @748
	REPLACE_TEXTUALLY ~{"AR1104", "Mayor Lloyd's Cabin"},~                                                              @749
	REPLACE_TEXTUALLY ~{"AR1105", "Imnesvale Inn"},~                                                                    @750
	REPLACE_TEXTUALLY ~{"AR1106", "Umar's Cave"},~                                                                      @751
	REPLACE_TEXTUALLY ~{"AR1107", "Ranger-Protector's Cabin (Stronghold)"},~                                            @752
	REPLACE_TEXTUALLY ~{"AR1200", "Windspear Hills"},~                                                                  @753
	REPLACE_TEXTUALLY ~{"AR1201", "Firkraag's Entrance"},~                                                              @754
	REPLACE_TEXTUALLY ~{"AR1202", "Firkraag's Maze"},~                                                                  @755
	REPLACE_TEXTUALLY ~{"AR1203", "Firkraag's Hideout"},~                                                               @756
	REPLACE_TEXTUALLY ~{"AR1204", "Garren Windspear's Cabin"},~                                                         @757
	REPLACE_TEXTUALLY ~{"AR1300", "De'Arnise Keep Destroyed"},~                                                         @758
	REPLACE_TEXTUALLY ~{"AR1301", "De'Arnise Cellar"},~                                                                 @759
	REPLACE_TEXTUALLY ~{"AR1302", "De'Arnise Keep 1st Floor"},~                                                         @760
	REPLACE_TEXTUALLY ~{"AR1303", "De'Arnise Keep 2nd Floor (Destroyed)"},~                                             @761
	REPLACE_TEXTUALLY ~{"AR1304", "De'Arnise Keep (Restored, Stronghold)"},~                                            @762
	REPLACE_TEXTUALLY ~{"AR1305", "De'Arnise Keep (Stronghold)"},~                                                      @763
	REPLACE_TEXTUALLY ~{"AR1306", "De'Arnise Keep (Stronghold)"},~                                                      @764
	REPLACE_TEXTUALLY ~{"AR1307", "De'Arnise Keep (Stronghold)"},~                                                      @765
	REPLACE_TEXTUALLY ~{"AR1400", "Shadow Temple Land (restored, Ranger)"},~                                            @766
	REPLACE_TEXTUALLY ~{"AR1401", "Shadow Temple"},~                                                                    @767
	REPLACE_TEXTUALLY ~{"AR1402", "Shadow Dragon Hideout"},~                                                            @768
	REPLACE_TEXTUALLY ~{"AR1403", "Wolfwere Hideout"},~                                                                 @769
	REPLACE_TEXTUALLY ~{"AR1404", "Shadow Temple Land shadowed"},~                                                      @770
	REPLACE_TEXTUALLY ~{"AR1500", "Spellhold"},~                                                                        @771
	REPLACE_TEXTUALLY ~{"AR1501", "Cave (Spellhold Test)"},~                                                            @772
	REPLACE_TEXTUALLY ~{"AR1502", "Fire Room (Spellhold Test)"},~                                                       @773
	REPLACE_TEXTUALLY ~{"AR1503", "Spore Room (Spellhold Test)"},~                                                      @774
	REPLACE_TEXTUALLY ~{"AR1504", "Crushing Trap Room (Spellhold Test)"},~                                              @775
	REPLACE_TEXTUALLY ~{"AR1505", "Lever Room (Spellhold Test)"},~                                                      @776
	REPLACE_TEXTUALLY ~{"AR1506", "Troll Cave (Spellhold Test)"},~                                                      @777
	REPLACE_TEXTUALLY ~{"AR1507", "Kobold Room (Spellhold Test)"},~                                                     @778
	REPLACE_TEXTUALLY ~{"AR1508", "Final Judgement Spellhold Test"},~                                                   @779
	REPLACE_TEXTUALLY ~{"AR1509", "Myconid Room (Spellhold Test)"},~                                                    @780
	REPLACE_TEXTUALLY ~{"AR1510", "Sahuagin Room (Spellhold Test)"},~                                                   @781
	REPLACE_TEXTUALLY ~{"AR1511", "Elven Table while Spellhold Test"},~                                                 @782
	REPLACE_TEXTUALLY ~{"AR1512", "Bodhi's Hunt Level 1"},~                                                             @783
	REPLACE_TEXTUALLY ~{"AR1513", "Bodhi's Hunt Level 2"},~                                                             @784
	REPLACE_TEXTUALLY ~{"AR1514", "Bodhi's Hunt Level 3 (1st Slayer Change Happens here)"},~                            @785
	REPLACE_TEXTUALLY ~{"AR1515", "Spellhold (Irenicus's Living Room)"},~                                               @786
	REPLACE_TEXTUALLY ~{"AR1516", "Spellhold (Soultheft Level)"},~                                                      @787
	REPLACE_TEXTUALLY ~{"AR1600", "Brynnlaw"},~                                                                         @788
	REPLACE_TEXTUALLY ~{"AR1601", "Desharik's Estate"},~                                                                @789
	REPLACE_TEXTUALLY ~{"AR1602", "Brynnlaw's Inn"},~                                                                   @790
	REPLACE_TEXTUALLY ~{"AR1603", "Brynnlaw's Shop"},~                                                                  @791
	REPLACE_TEXTUALLY ~{"AR1604", "Temple of Umberlee"},~                                                               @792
	REPLACE_TEXTUALLY ~{"AR1605", "CW's House"},~                                                                       @793
	REPLACE_TEXTUALLY ~{"AR1606", "House of Desharik's Lover"},~                                                        @794
	REPLACE_TEXTUALLY ~{"AR1607", "Githyanki Assault"},~                                                                @795
	REPLACE_TEXTUALLY ~{"AR1608", "Cellar of Brothel"},~                                                                @796
	REPLACE_TEXTUALLY ~{"AR1609", "Courtesan Room"},~                                                                   @797
	REPLACE_TEXTUALLY ~{"AR1610", "Brothel Prison"},~                                                                   @798
	REPLACE_TEXTUALLY ~{"AR1611", "Brothel"},~                                                                          @799
	REPLACE_TEXTUALLY ~{"AR1612", "Brothel Kitchen"},~                                                                  @800
	REPLACE_TEXTUALLY ~{"AR1613", "Brothel HQ"},~                                                                       @801
	REPLACE_TEXTUALLY ~{"AR1700", "Small Teeth Pass"},~                                                                 @802
	REPLACE_TEXTUALLY ~{"AR1800", "North Forest"},~                                                                     @803
	REPLACE_TEXTUALLY ~{"AR1900", "Druid Grove Area"},~                                                                 @804
	REPLACE_TEXTUALLY ~{"AR1901", "Druid Grove"},~                                                                      @805
	REPLACE_TEXTUALLY ~{"AR1902", "Storehouse (Ihtafeer's Storehouse)"},~                                               @806
	REPLACE_TEXTUALLY ~{"AR1904", "Troll Hill"},~                                                                       @807
	REPLACE_TEXTUALLY ~{"AR1905", "Store Tower"},~                                                                      @808
	REPLACE_TEXTUALLY ~{"AR2000", "Trademeet"},~                                                                        @809
	REPLACE_TEXTUALLY ~{"AR2001", "The Smithy"},~                                                                       @810
	REPLACE_TEXTUALLY ~{"AR2002", "Fentan's House"},~                                                                   @811
	REPLACE_TEXTUALLY ~{"AR2006", "Tiri's Home"},~                                                                      @812
	REPLACE_TEXTUALLY ~{"AR2007", "High Merchant's Estate"},~                                                           @813
	REPLACE_TEXTUALLY ~{"AR2008", "Temple of Waukeen"},~                                                                @814
	REPLACE_TEXTUALLY ~{"AR2009", "High Merchant Prison"},~                                                             @815
	REPLACE_TEXTUALLY ~{"AR2010", "Trademeet's Inn"},~                                                                  @816
	REPLACE_TEXTUALLY ~{"AR2011", "Alibakkar's Estate"},~                                                               @817
	REPLACE_TEXTUALLY ~{"AR2012", "Lurraxol's Estate"},~                                                                @818
	REPLACE_TEXTUALLY ~{"AR2013", "Trademeet Crypt"},~                                                                  @819
	REPLACE_TEXTUALLY ~{"AR2014", "Djinni's Tent"},~                                                                    @820
	REPLACE_TEXTUALLY ~{"AR2015", "Merchant Tent"},~                                                                    @821
	REPLACE_TEXTUALLY ~{"AR2016", "Raffee's Tent"},~                                                                    @822
	REPLACE_TEXTUALLY ~{"AR2017", "Courtesan Tent"},~                                                                   @823
	REPLACE_TEXTUALLY ~{"AR2018", "Tent (no exit)"},~                                                                   @824
	REPLACE_TEXTUALLY ~{"AR2100", "Underdark"},~                                                                        @825
	REPLACE_TEXTUALLY ~{"AR2101", "Beholder Cave in Underdark"},~                                                       @826
	REPLACE_TEXTUALLY ~{"AR2102", "Adalon's Cave"},~                                                                    @827
	REPLACE_TEXTUALLY ~{"AR2200", "Ust Natha"},~                                                                        @828
	REPLACE_TEXTUALLY ~{"AR2201", "Temple in Ust Natha"},~                                                              @829
	REPLACE_TEXTUALLY ~{"AR2202", "Inn in Ust Natha 1st Floor"},~                                                       @830
	REPLACE_TEXTUALLY ~{"AR2203", "Inn in Ust Natha; 2nd Floor"},~                                                      @831
	REPLACE_TEXTUALLY ~{"AR2204", "House in Ust Natha"},~                                                               @832
	REPLACE_TEXTUALLY ~{"AR2205", "House in Ust Natha"},~                                                               @833
	REPLACE_TEXTUALLY ~{"AR2206", "Qilue's House in Ust Natha"},~                                                       @834
	REPLACE_TEXTUALLY ~{"AR2207", "Deirex's Tower in Ust Natha"},~                                                      @835
	REPLACE_TEXTUALLY ~{"AR2208", "Jarlaxle's House wherever"},~                                                        @836
	REPLACE_TEXTUALLY ~{"AR2209", "Jae'llat's House"},~                                                                 @837
	REPLACE_TEXTUALLY ~{"AR2210", "Deirex's Cave"},~                                                                    @838
	REPLACE_TEXTUALLY ~{"AR2300", "Sahuagin City"},~                                                                    @839
	REPLACE_TEXTUALLY ~{"AR2400", "Mind Flayers in Underdark"},~                                                        @840
	REPLACE_TEXTUALLY ~{"AR2401", "Cave Between Underdark and Exit from Underdark"},~                                   @841
	REPLACE_TEXTUALLY ~{"AR2402", "Kuo Toa in Underdark"},~                                                             @842
	REPLACE_TEXTUALLY ~{"AR2500", "Elven Temple at Underdark Exit"},~                                                   @843
	REPLACE_TEXTUALLY ~{"AR2600", "Thetyr Wood"},~                                                                      @844
	REPLACE_TEXTUALLY ~{"AR2601", "Meet Drizzt Do'Urden"},~                                                             @845
	REPLACE_TEXTUALLY ~{"AR2602", "Cave in Woods to Suldanessellar"},~                                                  @846
	REPLACE_TEXTUALLY ~{"AR2603", "Coran's Cabin"},~                                                                    @847
	REPLACE_TEXTUALLY ~{"AR2700", "Ancient Spirits\?"},~                                                                 @848
	REPLACE_TEXTUALLY ~{"AR2800", "Suldanessellar"},~                                                                   @849
	REPLACE_TEXTUALLY ~{"AR2801", "House of High Priestess of Suldanessellar"},~                                        @850
	REPLACE_TEXTUALLY ~{"AR2802", "House in Suldanessellar"},~                                                          @851
	REPLACE_TEXTUALLY ~{"AR2803", "Rillifane Temple"},~                                                                 @852
	REPLACE_TEXTUALLY ~{"AR2804", "To the Tree of Life (Entrance Hidden)"},~                                            @853
	REPLACE_TEXTUALLY ~{"AR2805", "To the Tree of Life (Entrance Revealed)"},~                                          @854
	REPLACE_TEXTUALLY ~{"AR2806", "Tree of Life"},~                                                                     @855
	REPLACE_TEXTUALLY ~{"AR2807", "Black Dragon's Hideout"},~                                                           @856
	REPLACE_TEXTUALLY ~{"AR2808", "House in Suldanessellar"},~                                                          @857
	REPLACE_TEXTUALLY ~{"AR2809", "House in Suldanessellar - Puzzle Box"},~                                             @858
	REPLACE_TEXTUALLY ~{"AR2810", "House in Suldanessellar"},~                                                          @859
	REPLACE_TEXTUALLY ~{"AR2811", "House in Suldanessellar"},~                                                          @860
	REPLACE_TEXTUALLY ~{"AR2812", "Temple of Rillifane after the Battle"},~                                             @861
	REPLACE_TEXTUALLY ~{"AR2900", "The Abyss"},~                                                                        @862
	REPLACE_TEXTUALLY ~{"AR2901", "Fear (Abyss)"},~                                                                     @863
	REPLACE_TEXTUALLY ~{"AR2902", "Pride (Abyss)"},~                                                                    @864
	REPLACE_TEXTUALLY ~{"AR2903", "Greed (Abyss)"},~                                                                    @865
	REPLACE_TEXTUALLY ~{"AR2904", "Selfish (Abyss)"},~                                                                  @866
	REPLACE_TEXTUALLY ~{"AR2905", "Sarevok (Abyss)"},~                                                                  @867
	REPLACE_TEXTUALLY ~{"AR2906", "Jon Battle \?"},~                                                                     @868
	REPLACE_TEXTUALLY ~{"OH4000", "Rasaad - The Amphitheater"},~                                                        @869
	REPLACE_TEXTUALLY ~{"OH4010", "Rasaad - Tears of Selune battle encounter"},~                                        @870
	REPLACE_TEXTUALLY ~{"OH4100", "Rasaad - Dark Moon Heretic Temple"},~                                                @871
	REPLACE_TEXTUALLY ~{"OH4101", "Rasaad - Dark Moon Heretic Temple Interior"},~                                       @872
	REPLACE_TEXTUALLY ~{"OH5000", "Dorn - Radiant Heart (Wedding)"},~                                                   @873
	REPLACE_TEXTUALLY ~{"OH5100", "Dorn - Resurrection Gorge"},~                                                        @874
	REPLACE_TEXTUALLY ~{"OH5110", "Dorn - Resurrection Gorge Cave"},~                                                   @875
	REPLACE_TEXTUALLY ~{"OH5120", "Dorn - Resurrection Gorge Tree Interior"},~                                          @876
	REPLACE_TEXTUALLY ~{"OH5200", "Dorn - Resurrection Gorge Interior"},~                                               @877
	REPLACE_TEXTUALLY ~{"OH5300", "Dorn - Helmite Camp"},~                                                              @878
	REPLACE_TEXTUALLY ~{"OH6000", "Neera - The Wild Forest"},~                                                          @879
	REPLACE_TEXTUALLY ~{"OH6010", "Neera - Random Encounter in Athkatla"},~                                             @880
	REPLACE_TEXTUALLY ~{"OH6100", "Neera - The Hidden Refuge"},~                                                        @881
	REPLACE_TEXTUALLY ~{"OH6200", "Neera - The Hidden Refuge (Destroyed)"},~                                            @882
	REPLACE_TEXTUALLY ~{"OH6300", "Neera - Red Wizard Enclave"},~                                                       @883
	REPLACE_TEXTUALLY ~{"OH7000", "Hexxat - Top Left Quarter (Dragomir)"},~                                             @884
	REPLACE_TEXTUALLY ~{"OH7100", "Hexxat - Bottom Left Quarter (Shou Lung)"},~                                         @885
	REPLACE_TEXTUALLY ~{"OH7200", "Hexxat - Bottom Right Quarter (Zakhara)"},~                                          @886
	                                                                                                                    
	// CheatsAreas pour Les Gladiateurs de Thay                                                                         	
																														
	REPLACE_TEXTUALLY ~{"OH8000", "TBP2 - Suzail Tavern"},~                                                             @887
	REPLACE_TEXTUALLY ~{"OH8100", "TBP2 - Staging Area Map"},~                                                          @888
	REPLACE_TEXTUALLY ~{"OH8200", "TBP2 - Arena 1"},~                                                                   @889
	REPLACE_TEXTUALLY ~{"OH8300", "TBP2 - Arena 2"},~                                                                   @890
	REPLACE_TEXTUALLY ~{"OH8400", "TBP2 - Arena 3"},~                                                                   @891
	                                                                                                                    
	// CheatsAreas pour ToB : La Tour de Garde                                                                          	
																														
	REPLACE_TEXTUALLY ~{"AR3000", "Watcher's Keep"},~                                                                   @892
	REPLACE_TEXTUALLY ~{"AR3001", "Watcher's Keep -- Altar level"},~                                                    @893
	REPLACE_TEXTUALLY ~{"AR3003", "Watcher's Keep -- Compass level"},~                                                  @894
	REPLACE_TEXTUALLY ~{"AR3004", "Watcher's Keep"},~                                                                   @895
	REPLACE_TEXTUALLY ~{"AR3005", "Watcher's Keep -- tieflings"},~                                                      @896
	REPLACE_TEXTUALLY ~{"AR3006", "Watcher's Keep -- Succubus"},~                                                       @897
	REPLACE_TEXTUALLY ~{"AR3007", "Watcher's Keep --Cambion"},~                                                         @898
	REPLACE_TEXTUALLY ~{"AR3008", "Watcher's Keep -- Baalor (Paladin Sword)"},~                                         @899
	REPLACE_TEXTUALLY ~{"AR3009", "Watcher's Keep -- Wild Magic \?"},~                                                   @900
	REPLACE_TEXTUALLY ~{"AR3010", "Watcher's Keep -- Tanar'ri -- Obelisk"},~                                            @901
	REPLACE_TEXTUALLY ~{"AR3011", "Watcher's Keep -- Bard's Gloves, Manman's Journal"},~                                @902
	REPLACE_TEXTUALLY ~{"AR3012", "Watcher's Keep -- Tahazzar"},~                                                       @903
	REPLACE_TEXTUALLY ~{"AR3013", "Watcher's Keep -- Ka'rashur"},~                                                      @904
	REPLACE_TEXTUALLY ~{"AR3014", "Watcher's Keep -- White Dragon Scales"},~                                            @905
	REPLACE_TEXTUALLY ~{"AR3015", "Watcher's Keep -- Aesgareth"},~                                                      @906
	REPLACE_TEXTUALLY ~{"AR3016", "Watcher's Keep -- Chromatic Demon; Elementalist Level"},~                            @907
	REPLACE_TEXTUALLY ~{"AR3017", "Watcher's Keep -- Carston and the machine"},~                                        @908
	REPLACE_TEXTUALLY ~{"AR3018", "Watcher's Keep -- Saladrex (Dragon)"},~                                              @909
	REPLACE_TEXTUALLY ~{"AR3019", "Watcher's Keep -- Helmite Level -- Last Seals"},~                                    @910
	REPLACE_TEXTUALLY ~{"AR3020", "Watcher's Keep -- Imprisoned One"},~                                                 @911
	REPLACE_TEXTUALLY ~{"AR3021", "Watcher's Keep -- Illithids"},~                                                      @912
	REPLACE_TEXTUALLY ~{"AR3022", "Watcher's Keep -- Anti-Paladins"},~                                                  @913
	REPLACE_TEXTUALLY ~{"AR3023", "Watcher's Keep -- 'Adventure Level' (Mini Map!!!)"},~                                @914
	REPLACE_TEXTUALLY ~{"AR3024", "Watcher's Keep -- Dragon -- Fear Challenge"},~                                       @915
	REPLACE_TEXTUALLY ~{"AR3025", "Watcher's Keep -- Orcs -- Ixil's Nail"},~                                            @916
	REPLACE_TEXTUALLY ~{"AR3026", "Watcher's Keep -- Imp -- Game"},~                                                    @917
	REPLACE_TEXTUALLY ~{"AR3027", "Watcher's Keep -- Crypt -- Demi-Lich"},~                                             @918
	                                                                                                                    
	// CheatsAreas pour ToB	                                                                                            	
																														
	REPLACE_TEXTUALLY ~{"AR4000", "Spirit Heads"},~                                                                     @919
	REPLACE_TEXTUALLY ~{"AR4500", "Pocket Plane"},~                                                                     @920
	REPLACE_TEXTUALLY ~{"AR5000", "Saradush"},~                                                                         @921
	REPLACE_TEXTUALLY ~{"AR5001", "Gromnir 1st Level"},~                                                                @922
	REPLACE_TEXTUALLY ~{"AR5002", "Gromnir's Hideout"},~                                                                @923
	REPLACE_TEXTUALLY ~{"AR5003", "Saradush Tavern (Tankard Tree)"},~                                                   @924
	REPLACE_TEXTUALLY ~{"AR5004", "Temple of Waukeen"},~                                                                @925
	REPLACE_TEXTUALLY ~{"AR5005", "Gromnir's Barracks"},~                                                               @926
	REPLACE_TEXTUALLY ~{"AR5006", "Saradush Prison"},~                                                                  @927
	REPLACE_TEXTUALLY ~{"AR5007", "Basement Entrance to Gromnir's Hideout"},~                                           @928
	REPLACE_TEXTUALLY ~{"AR5008", "Kiser's Home"},~                                                                     @929
	REPLACE_TEXTUALLY ~{"AR5009", "House (no exit\?)"},~                                                                 @930
	REPLACE_TEXTUALLY ~{"AR5010", "Countess Santele's Home"},~                                                          @931
	REPLACE_TEXTUALLY ~{"AR5011", "Arcana Archives"},~                                                                  @932
	REPLACE_TEXTUALLY ~{"AR5012", "House"},~                                                                            @933
	REPLACE_TEXTUALLY ~{"AR5013", "Sewers beneath Saradush"},~                                                          @934
	REPLACE_TEXTUALLY ~{"AR5014", "Kiser's Home -- Cellar"},~                                                           @935
	REPLACE_TEXTUALLY ~{"AR5015", "Saradush Militia Entrance"},~                                                        @936
	REPLACE_TEXTUALLY ~{"AR5016", "Saradush Castle Jail (Kiser Plot)"},~                                                @937
	REPLACE_TEXTUALLY ~{"AR5200", "Fire Giant Entrance Area"},~                                                         @938
	REPLACE_TEXTUALLY ~{"AR5201", "Fire Giant Keep"},~                                                                  @939
	REPLACE_TEXTUALLY ~{"AR5202", "Nyalee's Hideout; Gorion Wraith"},~                                                  @940
	REPLACE_TEXTUALLY ~{"AR5203", "Yaga-Shura's Camp"},~                                                                @941
	REPLACE_TEXTUALLY ~{"AR5204", "Yaga-Shura's Keep"},~                                                                @942
	REPLACE_TEXTUALLY ~{"AR5500", "Amkethran"},~                                                                        @943
	REPLACE_TEXTUALLY ~{"AR5501", "Amkethran Inn"},~                                                                    @944
	REPLACE_TEXTUALLY ~{"AR5502", "Kerrick the Smith's House"},~                                                        @945
	REPLACE_TEXTUALLY ~{"AR5503", "Chyil's House"},~                                                                    @946
	REPLACE_TEXTUALLY ~{"AR5504", "Smuggler Cave"},~                                                                    @947
	REPLACE_TEXTUALLY ~{"AR5505", "Balthazar's Home"},~                                                                 @948
	REPLACE_TEXTUALLY ~{"AR5506", "Commoner's Home"},~                                                                  @949
	REPLACE_TEXTUALLY ~{"AR5507", "Empty Home"},~                                                                       @950
	REPLACE_TEXTUALLY ~{"AR5508", "Faheed's Home"},~                                                                    @951
	REPLACE_TEXTUALLY ~{"AR5509", "Amkethran Crypt"},~                                                                  @952
	REPLACE_TEXTUALLY ~{"AR6000", "Abazigal's Entrance"},~                                                              @953
	REPLACE_TEXTUALLY ~{"AR6001", "Abazigal's Lair Entrance Hall"},~                                                    @954
	REPLACE_TEXTUALLY ~{"AR6002", "Abazigal's Lair -- Cells"},~                                                         @955
	REPLACE_TEXTUALLY ~{"AR6003", "Abazigal's Lair -- Iycanth the Mad, Bondari"},~                                      @956
	REPLACE_TEXTUALLY ~{"AR6004", "Abazigal's Lair -- Fll'Yissetat"},~                                                  @957
	REPLACE_TEXTUALLY ~{"AR6005", "Abazigal's Hideout"},~                                                               @958
	REPLACE_TEXTUALLY ~{"AR6008", "Frost Salamander Cave"},~                                                            @959
	REPLACE_TEXTUALLY ~{"AR6011", "Orbs and Gauth"},~                                                                   @960
	REPLACE_TEXTUALLY ~{"AR6012", "Pool Home -- breath under water"},~                                                  @961
	REPLACE_TEXTUALLY ~{"AR6100", "Area outside Sendai's Hideout"},~                                                    @962
	REPLACE_TEXTUALLY ~{"AR6101", "Main Entrance Sendai's Lair"},~                                                      @963
	REPLACE_TEXTUALLY ~{"AR6102", "Sendai's Lair -- Slavemaster"},~                                                     @964
	REPLACE_TEXTUALLY ~{"AR6103", "Sendai's Lair -- Spiders"},~                                                         @965
	REPLACE_TEXTUALLY ~{"AR6104", "Sendai's Lair -- Crossway"},~                                                        @966
	REPLACE_TEXTUALLY ~{"AR6105", "Sendai's Lair -- Diaytha, Abishai"},~                                                @967
	REPLACE_TEXTUALLY ~{"AR6106", "Sendai's Lair -- Captain Egeissag"},~                                                @968
	REPLACE_TEXTUALLY ~{"AR6107", "Sendai's Lair -- Mithykyl"},~                                                        @969
	REPLACE_TEXTUALLY ~{"AR6108", "Sendai's Lair -- Sendai"},~                                                          @970
	REPLACE_TEXTUALLY ~{"AR6109", "Sendai's Lair -- Drow"},~                                                            @971
	REPLACE_TEXTUALLY ~{"AR6110", "Sendai's Lair -- Odamaron"},~                                                        @972
	REPLACE_TEXTUALLY ~{"AR6111", "Woodcutter's House -- Sendai's Area"},~                                              @973
	REPLACE_TEXTUALLY ~{"AR6200", "The Throne of Bhaal"},~                                                              @974
	REPLACE_TEXTUALLY ~{"AR6300", "Oasis in Tethyr"},~                                                                  @975
	REPLACE_TEXTUALLY ~{"AR6400", "River Area"},~                                                                       @976
	REPLACE_TEXTUALLY ~{"OH4200", "Rasaad - Dwarven Clanhold Exterior"},~                                               @977
	REPLACE_TEXTUALLY ~{"OH4210", "Rasaad - Dwarven Clanhold Interior"},~                                               @978
	REPLACE_TEXTUALLY ~{"OH4220", "Rasaad - Dwarven Mines"},~                                                           @979
	REPLACE_TEXTUALLY ~{"OH4230", "Rasaad - Plane of Shadow"},~                                                         @980
	REPLACE_TEXTUALLY ~{"OH4290", "Rasaad - Sharran Ambush"},~                                                          @981
	REPLACE_TEXTUALLY ~{"OH5400", "Dorn - Forest Clearing"},~                                                           @982
	REPLACE_TEXTUALLY ~{"OH5500", "Dorn - Lunia"},~                                                                     @983
	REPLACE_TEXTUALLY ~{"OH6400", "Neera - Wilderness Clearing"},~                                                      @984
	REPLACE_TEXTUALLY ~{"OH6450", "Neera - The Black Pits: Arena"},~                                                    @985
	REPLACE_TEXTUALLY ~{"OH6460", "Neera - The Black Pits: Staging Area"},~                                             @986
	REPLACE_TEXTUALLY ~{"OH6500", "Neera - Thayan Estate"},~                                                            @987
	REPLACE_TEXTUALLY ~{"OH7300", "Hexxat - Completed Maze (Korkorran)"},~                                              @988
	REPLACE_TEXTUALLY ~{"OH7310", "Hexxat - Scene with L"},~                                                            @989
	
END
